### ISSUE TITLE
Glitching with Sublime Text

### ISSUE THREAD

**Issue by Flashwalker** [yshui/compton#1012]
Glitching with Sublime Text
if i set in Sublime settings:
```
"hardware_acceleration": "opengl",
```

### Platform
Pop!_OS 22.04 LTS

### GPU, drivers, and screen setup

NVIDIA GP107M [GeForce GTX 1050 Mobile]
driver:470.161.03

### Environment

Xfce 4.18

### picom version

vgit-1b7f7
<details>
<summary>Diagnostics</summary>
$ picom --experimental-backends --diagnostics
**Version:** vgit-1b7f7

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/user/.config/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
</details>

### Configuration:  
<details>
    <summary>Configuration file: </summary>
</details>
[picom.conf](https://fars.ee/xoOG)

### Steps of reproduction

1. Run Sublime Text
2. Switch between windows

### Current Behavior
Glitching

### Other details

https://user-images.githubusercontent.com/2188215/215326579-272872c0-2720-4ad4-8d38-3ba4be58c07d.mp4

**Comment by absolutelynothelix** [comment]
your picom is pretty outdated. test picom built from the latest commit and report back if the issue is still here.

**Comment by Flashwalker** [comment]
noup, wasn't helpfull

**Comment by absolutelynothelix** [comment]
you have a pretty big configuration file. does it happen when picom is started as `picom --config=/dev/null --backend=glx`? you can also try the new `egl` backend.

**Comment by Flashwalker** [comment]
Tested with `picom --config=/dev/null --backend=glx`  - the same.  
Tested with `picom --config=/dev/null --backend=egl` - it's better, mach less glitches in Sublime... But it's completely unusable because i can't input anything with the mouse or keyboard anywhere. I can only switch windows.

**Comment by absolutelynothelix** [comment]
ok, i'll note this and take a look later. just a couple more tests to isolate the issue. could you test if the issue is still here if you start picom as:
1) `picom --config=/dev/null --legacy-backends --backend=glx`
2) `picom --config=/dev/null --legacy-backends --backend=glx --glx-no-rebind-pixmap`

**Comment by Flashwalker** [comment]
ok

Tested 1.: same glithes
```
$ picom --config=/dev/null --legacy-backends --backend=glx
[ 01.02.2023 17:00:36.658 x_create_picture_with_pictfmt_and_pixmap ERROR ] failed to create picture (X error 8 MATCH request 139 minor 4 serial 6479)
[ 01.02.2023 17:00:36.659 x_log_error WARN ] X error 8 MATCH request 152 minor 22 serial 6482
[ 01.02.2023 17:00:36.659 x_log_error WARN ] X error 9 DRAWABLE request 156 minor 4 serial 6483
[ 01.02.2023 17:00:36.659 x_log_error WARN ] X error 161 GLX_BAD_PIXMAP request 152 minor 16 serial 0
```

Tested2 2.: same glithes
```
$ picom --config=/dev/null --legacy-backends --backend=glx --glx-no-rebind-pixmap
[ 01.02.2023 17:02:08.197 x_create_picture_with_pictfmt_and_pixmap ERROR ] failed to create picture (X error 8 MATCH request 139 minor 4 serial 6548)
[ 01.02.2023 17:02:08.198 x_log_error WARN ] X error 8 MATCH request 152 minor 22 serial 6551
[ 01.02.2023 17:02:08.198 x_log_error WARN ] X error 9 DRAWABLE request 156 minor 4 serial 6552
[ 01.02.2023 17:02:08.198 x_log_error WARN ] X error 161 GLX_BAD_PIXMAP request 152 minor 16 serial 0
[ 01.02.2023 17:03:44.268 x_log_error WARN ] X error 3 WINDOW request 2 minor 0 serial 48948
```

And tested again `egl` backend, and found that input/selecting/editing text is actualy works but with a huge lag (almost like not working at all) at least in Chromium and Sublime, so still unusable. And glitches do not completely disappear.

**Comment by absolutelynothelix** [comment]
can't reproduce. you didn't specify the sublime text version you're using, so i installed 4th one and, hopefully, properly enabled hardware acceleration:
![image](https://user-images.githubusercontent.com/52252283/221988648-c9c2e37a-4903-4794-af85-1a6637342886.png)

same as in the #1028: have you tried upgrading your gpu driver? it seems pretty old.

**Comment by Flashwalker** [comment]
Thanks for help.
# UPD:
I installed nvidia 525 driver.
Now edl backend works fine.
