### ISSUE TITLE
[Feature request] Whitelist options

### ISSUE THREAD

**Issue by tupo2** [yshui/compton#1019]
These options:
```
--rounded-corners-exclude <CONDITION>
--shadow-exclude <CONDITION>
--fade-exclude <CONDITION>
--focus-exclude <CONDITION>
--blur-background-exclude <CONDITION>
```
Example the following options will whitelist conditions excluded previously:
```
--rounded-corners-include <CONDITION>
--shadow-include <CONDITION>
--fade-include <CONDITION>
--focus-include <CONDITION>
--blur-background-include <CONDITION>
```

**Comment by absolutelynothelix** [comment]
so you want to exclude something and then include it back?..

**Comment by tupo2** [comment]
Yes, that's what i want to do:
```
rounded-corners-exclude = [
  "window_type = 'popup_menu'" # Claws-mail and others are involved here
];
rounded-corners-include = [
  "class_g *?= 'Claws-mail'"
];
```

**Comment by absolutelynothelix** [comment]
you can achieve this using only the `rounded-corners-exclude` option (as well as any other `-exclude` option):
```
rounded-corners-exclude = [
    "window_type = 'popup_menu' && class_g != 'Claws-mail'"
];
```

**Comment by servimo** [comment]
He wants to exlude "popup_menu" but not all.

**Comment by tupo2** [comment]
> you can achieve this using only the `rounded-corners-exclude` option (as well as any other `-exclude` option):
> 
> ```
> rounded-corners-exclude = [
>     "window_type = 'popup_menu' && class_g != 'Claws-mail'"
> ];
> ```
That's it, thanks.
