### ISSUE TITLE
Shadow lines in terminal with blur(any type)

### ISSUE THREAD

**Issue by siyia2** [yshui/compton#103]
### Platform
gentoo/arch

### GPU, drivers, and screen setup
vega 3 , radeon 535
mesa 18.3.2 llvm 7.0.1
### Environment
xfce4 4.12.5

### Compton version
v5/stable
### Compton configuration:
```
# Shadow
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;
 #shadow-red = 1.0;
 #shadow-green = 0.0;
 #shadow-blue = 0.0;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'VirtualBox'",
	"class_g = 'Chromium'",
	"class_g = 'Firefox'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"! name~=''",
	"_GTK_FRAME_EXTENTS@:c"
];

inactive-dim = 0.2;

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];

#Blur
#resize-damage = 2;
blur-background = true;
blur-background-frame = true;
blur-kern = "5x5gaussian"
#blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
#blur-background-fixed = true;
blur-background-exclude = [
	"window_type = 'dock'",
	"_GTK_FRAME_EXTENTS@:c"
];


# Other
backend = "glx";
#backend = "xrender";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 60;
vsync = "opengl-swc";
sw-opti = true;
unredir-if-possible = true;
unredir-if-possible-exclude = [ "class_g = 'smplayer'",
"class_g = 'firefox'", "class_g = 'mb_warband_linux'" ];
#,"class_g = 'Medieval2'"
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];


#Xrender backend
#xrender-sync-fence = true;
#vsync = "opengl";

# GLX backend
vsync-use-glfinish= true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
glx-swap-method = "buffer-age";


# Window type settings
wintypes:
{ 
  dropdown_menu = {opacity=0.87};
  popup_menu = {opacity=0.87};
  tooltip = { fade = true; shadow = true; opacity = true; focus = true; };
};
```

### Steps of reproduction

1.enable blur with buffer-age
2.open a terminal drag it and then write into it

### Expected behavior
No shadow lines to appear
### Current Behavior
shadow lines appear in the terminal

### Other details
if i set glx-swap-method to anything else 0/1/3 etc no shadow lines
issue is inherited  from old compton

https://github.com/chjj/compton/issues/476

**Comment by yshui** [comment]
Please remember to quote your configuration file.

Also, please provide a screenshot since that will help me understand the problem you are having.

**Comment by siyia2** [comment]
![screenshot_2019-02-01_19-00-37](https://user-images.githubusercontent.com/46220960/52137585-90809e00-2653-11e9-80e6-6781d13357fb.png)

**Comment by yshui** [comment]
This is known, see #50 .

A workaround would be `--resize-damage=7`

**Comment by siyia2** [comment]
another proposed workaround was glx-swap-method=0/1/2/3 is there a disadvantage to using instead that of buffer-age?

**Comment by yshui** [comment]
buffer-age is supposed to have slightly better performance.

I will close this as a duplicate.
