### ISSUE TITLE
Rounded corners feels blocky

### ISSUE THREAD

**Issue by musjj** [yshui/compton#1042]
Rounded corners produced by `corner-radius`, just doesn't feel very _round_. It feels more like the corner is chopped off with a straightedge.

This is what it looks like right now, with `corner-radius = 15`:

![image](https://user-images.githubusercontent.com/72612857/228677697-f694a9e4-e6fa-4190-9641-5576d3f620ae.png)

And this is what I think an ideal round corner should look like (done using GTK's css: `border-radius: 15px;` ):

![image](https://user-images.githubusercontent.com/72612857/228677634-1320d07a-ff97-4efb-809a-d1cb6be427ca.png)

It just looks so much more smoother.

**Comment by alanpq** [comment]
What is the height of both bars? It looks like both pictures have the same corner radius, but the GTK screenshot has a shorter overall height, making it look rounder.
![image](https://user-images.githubusercontent.com/2752274/228945057-ec0c2d8f-da41-47b4-b00b-57e0c83af39d.png)

**Comment by tupo2** [comment]
Same issue here since I switched to the new backends. `corner-radius` are much better with the `--legacy-backends`.

**Comment by musjj** [comment]
@alanpq 
The height are identical, the cropping of my screenshot was just slightly different.

**Comment by absolutelynothelix** [comment]
see #1021

**Comment by absolutelynothelix** [comment]
should be fixed in 0585e3172d271914efa5e25fd0296b7d481f820b, 6b858b89a0927a3645a1648a7dd0310f7d4c839f and f4fcedc470d39ce21caae4d1d0f73dd7f0b2600e (included in [the v12-rc2 pre-release](https://github.com/yshui/picom/releases/tag/v12-rc2)). see #609 if you'd like even more roundness and smoothness.

closing as fixed.
