### ISSUE TITLE
glx shader opacity behaves weird

### ISSUE THREAD

**Issue by quantenzitrone** [yshui/compton#1054]
### Platform
NixOS 23.05.20230419.645bc49 (Stoat)

### GPU, drivers, and screen setup

NVIDIA GeForce GTX 1050 Mobile (Laptop) with Proprietary Drivers v530.41.03
& Intel integrated Graphics
<details>
<summary>$ glxinfo -B</summary>
$ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 630 (KBL GT2) (0x591b)
    Version: 23.0.1
    Accelerated: yes
    Video memory: 15890MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
</details>

### Environment
i3wm

### picom version
v10
<details>
<summary>Diagnostics</summary>
**Version:** v10

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /etc/xdg/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)

### Config
```
backend = "glx"
corner-radius = 25
fading = false
vsync = true
one of the following
# active-opacity = 0.6
# window-shader-fg = "/etc/xdg/picom/shader.glsl";
```
### shader
```glsl
#version 330
in vec2 texcoord;
uniform sampler2D tex;
uniform float corner_radius;
uniform float border_width;
vec4 default_post_processing(vec4 c);
vec4 window_shader() {
	vec4 c = texelFetch(tex, ivec2(texcoord), 
	if (c.a < 1);
	else if (c.r > 0.9 && c.g > 0.9 && c.b > 0.9) c = vec4(0.6,0.6,0.6,0);
	return default_post_processing( c );
}
```
</details>

### Expected behavior
nice transparency like with `active-opacity = 0.6`:
![image](https://user-images.githubusercontent.com/74491719/234084423-09d8ff5c-1b2d-4fe6-9a0a-66777d674877.png)

### Current Behavior
ugly transparency when using transparency from shaders:
![image](https://user-images.githubusercontent.com/74491719/234084551-650b55b4-f814-43d0-a582-c73f65ec9668.png)

### Other details
I honestly don't really understand glx, but as far as i understood it, glx shaders render the opacity in a way, where the alpha value applies to a \#000 background and the rgb values are overlayed over this background.
This is probably just how glx works and not picoms fault.
I don't really know if this is actually an issue. On the other hand if i just understood glx totally wrong, i would like some help.

I'll try to work out the exact conversion formula to find out if that changes anything.

**Comment by quantenzitrone** [comment]
Ok, i figured it out, it's pretty simple, once you understand:
- the rgba color representation that is used by picom and is more common is called `straight alpha`
- the rgba color representation and combination used by glx is `premultiplied alpha`
- this is according to [Wikipedia](https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied) a little bit more efficient due to fewer needed multiplications.
- the conversion to premultiplied is simple:
   - keep the alpha value
   - multiply the color values (rgb) by the straight alpha value each

With this knowledge, i was able to get transparency that fades to opaque for darker colors
Specifically, i applied an opacity of 0.8 for everything that is \#fff with a linear gradient to about \#e5e5e5 (0.9) fading to fully opaque:
![image](https://user-images.githubusercontent.com/74491719/234148915-0431b07f-8ee0-4001-8e5c-c56191fea37f.png)

This is my shader:
```glsl
#version 330
in vec2 texcoord;
uniform sampler2D tex;
uniform float corner_radius;
uniform float border_width;
vec4 default_post_processing(vec4 c);
vec4 premultiply_alpha(vec3 c, float a) {
	return vec4(c.r*a,c.g*a,c.b*a,a);
}
vec4 window_shader() {
	vec4 c = texelFetch(tex, ivec2(texcoord), 0);
	if (c.a == 1 && c.r > 0.9 && c.g > 0.9 && c.b > 0.9) {
		c.a = (1 - (c.r + c.g + c.b)/3)*2+0.8;
		c.rgb *= c.a;
	}
	return default_post_processing( c );
}

```
I will probably tweak this a bit more to have a non-linear gradient.

**Comment by Quantenzitrone** [comment]
ok this is what i got now, it might use more cpu than a basic picom would, not sure:
```glsl
#version 330
in vec2 texcoord;
uniform sampler2D tex;
uniform float corner_radius;
uniform float border_width;
vec4 default_post_processing(vec4 c);
vec4 premultiply_alpha(vec3 c, float a) {
	return vec4(c.r*a,c.g*a,c.b*a,a);
}
vec4 window_shader() {
	vec4 c = texelFetch(tex, ivec2(texcoord), 0);
	// define stuff
	float opacity = 0.8;
	float opaqueAt = 0.8;
	int power = 6;
	if (c.a == 1 && c.r > opaqueAt && c.g > opaqueAt && c.b > opaqueAt) {
		float diff = (c.r + c.g + c.b)/3-opaqueAt;
		float grad = pow(1/(1-opaqueAt),power-1)*pow(diff,power);
		c.a = 1-grad*(opaqueAt/opacity);
		c.rgb *= c.a;
	}
	return default_post_processing( c );
}
```

You can change `opacity`, `opaqueAt` and `power`, to get a gradient from `white` to `opaqueAt` of opacity in range of `opacity` and fully opaque. Power defines the gradient curve. 
You can play around with the values pretty easy to get the gradient you desire.

**Comment by quantenzitrone** [comment]
https://github.com/ikz87/picom-shaders for more shaders
