### ISSUE TITLE
Dithering artefacts where it shouldn't be

### ISSUE THREAD

**Issue by yshui** [yshui/compton#1064]
I noticed the firefox window is _sometimes_ dithered. There is no blending or dimming going on, so there shouldn't be any dithering. This only happens to certain parts of a webpage, most notable example is probably the YouTube video player.

This is difficult to debug because firefox windows are basically impossible to capture with apitrace...

**Comment by absolutelynothelix** [comment]
1. dithering like… grainy? or lower color depth?
2. is it possible to capture such behavior on a screenshot?
3. does it happen only in firefox?
4. are there any examples that trigger this behavior more often than others?
5. is it constant dithering (i.e. it starts, goes for some time and ends) or it’s flickering?
6. what’s your config?

**Comment by yshui** [comment]
1. i don't know exactly how to describe it, you can see it if you know what to look for. try moving your head towards and away from your monitor, you might notice vertical stripes appearing and disappearing, this might also depend on what kind of monitor you have.
2. unsure
3. so far i only noticed it in firefox
4. try the youtube video player
5. yeah

**Comment by yshui** [comment]
it's more noticeable if the video is bright

**Comment by absolutelynothelix** [comment]
nice one! i was thinking about `dithered-present`, however, i've been using it since the day it was introduced and haven't seen odd dithering.
