### ISSUE TITLE
Unable to build picom on Ubuntu 23.04 

### ISSUE THREAD

**Issue by shahriar0247** [yshui/compton#1065]
### Platform

Ubuntu Desktop 23.04
### GPU, drivers, and screen setup

AMD GPU (but doesnt matter)
### Environment

using i3
### picom version

<details>
<summary>Diagnostics</summary>
Im not able to build picom, i did install all dependencies and also built like 5 other picoms
![image](https://user-images.githubusercontent.com/47810596/236858254-4c20c8da-8f6d-4638-a138-18e00ac38d72.png)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
// Paste your configuration here
```
</details>

### Steps of reproduction

1.
2.

**Comment by shahriar0247** [comment]
![image](https://user-images.githubusercontent.com/47810596/236858417-4e8626bb-adb9-4b6e-af86-ae21ab1bb2bf.png)
fatal error: sys/event.h: No such file or directory
    9 | #include <sys/event.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by absolutelynothelix** [comment]
you did `meson setup` before `ninja -C`, what's the output of it? you may append `--wipe` to it to reconfigure, i.e. `meson setup ... --wipe`.

**Comment by absolutelynothelix** [comment]
closing as stale.
