### ISSUE TITLE
Advanced CONDITION config/workaround

### ISSUE THREAD

**Issue by cab-1729** [yshui/compton#1070]
Is there a way to make a condition apply for a different application than the one where the feature is applied?

For example:
I want to blur my terminal window but I want to disable/change blur if MPV is running on the system. Is this possible using Picom? If so, how? I am willing to implement complicated workarounds for this if such a feature is not supported directly.

**Comment by EndChapter** [comment]
I think you are looking for something this: 
```

# Exclude conditions for background blur.
# blur-background-exclude = []
blur-background-exclude = [
  "class_g ?= 'mpv'"
];
```
You can check [arch wiki](https://wiki.archlinux.org/title/picom) or my dotfiles for further configuration options.

**Comment by servimo** [comment]
@EndChapter He wants to disable blur on terminal when mpv is running.

**Comment by barbiefan** [comment]
I bet you could write a script, that watches 'pgrep mpv' and if its running it substitutes some lines in your picom config, then watches pgrep again till there's no MPV running, then substitutes again. I think it would work since picom reloads when config file is changed

**Comment by barbiefan** [comment]
something like that:  
in picom.conf  
```
opacity-rule = [
...
"50:class_g = 'Alacritty'",
...
]
```  

script:
```bash
#!/bin/bash

while true
do
  sleep 1
  if pgrep -f mpv
  then
    echo "mpv launched"
    sed -i "s/\"50:class_g = 'Alacritty'\",/\"100:class_g = 'Alacritty'\",/g" "$HOME/.config/picom.conf"
    while true
    do
      sleep 1
      if ! pgrep -f mpv
      then
        echo "mpv stopped"
        sed -i "s/\"100:class_g = 'Alacritty'\",/\"50:class_g = 'Alacritty'\",/g" "$HOME/.config/picom.conf"
        break
      fi
    done
  fi
done
```

**Comment by cab-1729** [comment]
So there's no way to do this directly, without changing the config or running a different daemon?

**Comment by barbiefan** [comment]
I can't know for sure, but for me it seems not possible since conditions are just that - conditions.  
The operation is applied to a window based on whether IT fits any of specified list of conditions.  
So you can't really write something like:  
```bash
"if this windows name is Xterm AND somewhere there is a window with name mpv"  
```   
you can only mention properties of window or frame to which operation is applied.  

**But I'm not a picom developer, maybe there is a hack that could do what you want, but I doubt that.**

**Comment by cab-1729** [comment]
Ok, closing this issue.
