### ISSUE TITLE
Blurred windows not accounting for rounded edges

### ISSUE THREAD

**Issue by Jordan-Jay** [yshui/compton#1097]
### Platform
Debian 12

### GPU, drivers, and screen setup

Nvidia RTX 2080 Super, nvidia-drivers 525.105, one monitor configured with xrandr

Output of glxinfo -B:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7654 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.105.17
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 525.105.17
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.105.17
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20 
```

### Environment
BSPWM 0.9.10

### picom version
`picom --version` v9.1
<details>
<summary>Diagnostics</summary>
[ 10/07/23 14:53:17.094 get_cfg WARN ] Dual-kawase blur is not implemented by the legacy backends, you must use the `experimental-backends` option.
[ 10/07/23 14:53:17.169 init_render WARN ] Old backends only support blur method "kernel". Your blur setting will not be applied
**Version:** v9.1

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/jordan/.config/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
log-level = "warn";

active-opacity = 1.0;
inactive-opacity = 0.75;

blur-background = false;
blur-strength = 19;
blur-radius = 1;
blur-method = "dual_kawase";

blur-background-frame = true;
blur-background-fixed = false;
blur-background-exclude = [
    "class_g ?= 'gnome-screenshot'",
    "_GTK_FRAME_EXTENTS@:c"
];

opacity-rule = [
    "85:class_g = 'Rofi'"
];

fading = true;
fade-delta = 3;
fade-in-step = 0.02;
fade-out-step = 0.02;
fade-exclude = [ ];

mark-wmwin-focused = true;
mark-ovredir-focused = false;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
vsync = true;
dbe = false;
unredir-if-possible = false;
focus-exclude = [ ];
detect-transient = true;
detect-client-leader = true;

wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.9; focus = true;};
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.9; }
  dropdown_menu = { opacity = 0.9; }
};

shadow-opacity = 0.25;

xrender-sync-fence = true;

use-damage = false;

round-borders = 1;
corner-radius = 20.0;
round-corners-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
]
```
</details>

### Steps of reproduction

1. Enable blur strength = (anything above 1)
2. Use rounded corners

### Expected behavior

The expected behavior should be windows having rounded corners without showing the blur on the edges where
the corners are supposed to be rounded.

### Current Behavior

The current behavior is the corners of windows if you're using blur will show the blur on the edges which it doesn't round.

![Selection_005](https://github.com/yshui/picom/assets/81544597/94ad83f4-3e29-412e-855a-b4838f9d291a)

**Comment by absolutelynothelix** [comment]
you have an outdated and misconfigured picom. consider either upgrading to the latest stable picom (v10.2 at the moment of writing) or building picom from the latest commit in the next branch first.

**Comment by absolutelynothelix** [comment]
closing as stale.
