### ISSUE TITLE
xscreensaver doesn't show the screensaver when picom is enabled

### ISSUE THREAD

**Issue by killertofus** [yshui/compton#1098]
### Platform

arch linux 6.4.3-arch1-2
### Environment

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
### picom version

vgit-b700a
<details>
<summary>Diagnostics</summary>

</details>
**Version:** vgit-b700a

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/killertofus/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 4600 (HSW GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: crocus
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 4600 (HSW GT2)
### Configuration:
<details>
    <summary>Configuration file</summary>

```
https://github.com/killertofus/awesome/blob/main/Config/picom.conf
```

</details>

### Steps of reproduction

1) try to preview a xscreensaver screensaver 
2) see that it doesn't work 

### Expected behavior
to show the screensaver
### Current Behavior
don't see the screensaver it's still there but can't see the screensaver

**Comment by killertofus** [comment]
here is a video of the error

https://github.com/yshui/picom/assets/16343162/e785725f-3388-4db0-9625-7655ac199d9b

**Comment by absolutelynothelix** [comment]
the screensaver window type is `_NET_WM_WINDOW_TYPE_NOTIFICATION` and the `"0:_NET_WM_WINDOW_TYPE@[*]:32a = '_NET_WM_WINDOW_TYPE_NOTIFICATION'"` opacity rule in your configuration file makes it completely transparent:
```
[ 09/02/2023 18:56:16.766 paint_preprocess TRACE ] Window 0x02a00001 (XScreenSaver) will not be painted because it has 0 opacity
```
