### ISSUE TITLE
picom totally freezes (hangs) after `xset dpms force off` in NVIDIA with nouveau

### ISSUE THREAD

**Issue by ZhymabekRoman** [yshui/compton#1119]
### Platform
Arch Linux, amd64

### GPU, drivers, and screen setup
GeForce GT 710, xf86-video-nouveau 1.0.17-2, mesa 1:23.1.6-1

<details>
<summary>sudo lspci -v</summary>

```
01:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation GK208B [GeForce GT 710]
	Flags: bus master, fast devsel, latency 0, IRQ 24
	Memory at ea000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=128M]
	Memory at e8000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 2000 [size=128]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Kernel driver in use: nouveau
	Kernel modules: nouveau
```
</details>

<details>
<summary>glxinfo -B</summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa (0x10de)
    Device: NV106 (0x128b)
    Version: 23.1.6
    Accelerated: yes
    Video memory: 2040MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 4.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1632 MB, largest block: 1632 MB
    VBO free aux. memory - total: 838860 MB, largest block: 838860 MB
    Texture free memory - total: 1632 MB, largest block: 1632 MB
    Texture free aux. memory - total: 838860 MB, largest block: 838860 MB
    Renderbuffer free memory - total: 1632 MB, largest block: 1632 MB
    Renderbuffer free aux. memory - total: 838860 MB, largest block: 838860 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2040 MB
    Total available memory: 1050615 MB
    Currently available dedicated video memory: 1632 MB
OpenGL vendor string: Mesa
OpenGL renderer string: NV106
OpenGL core profile version string: 4.3 (Core Profile) Mesa 23.1.6
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.3 (Compatibility Profile) Mesa 23.1.6
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
</details>

### Environment
`bspwm` with `polybar`

### picom version
`picom --version`
<details>
<summary>Diagnostics</summary>

*Version:** vgit-b700a

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /etc/xdg/picom.conf

### Drivers (inaccurate):

nouveau

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Mesa
* GL renderer: NV106
* Accelerated: 1

### Backend: egl

libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: nouveau
 * GL: Mesa
* GL renderer: NV106
</details>

### Configuration:
I use standard config from Arch

<details>
<summary>.xinitrc</summary>

```
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

picom &
xterm
```
</details>

### Steps of reproduction
1. `startx`
2. `xset dpms force off`
3. checking with mouse
4. mouse is moving, all windows is shown, but not accessible

### Expected behavior
No hangs

### Current Behavior
mouse is moving, all windows is shown, but not accessible

### Stack trace
No trace info, only in stdout:
```
Xlib: ignoring invalid extension event 161
Xlib: ignoring invalid extension event 161
Xlib: ignoring invalid extension event 161
Xlib: ignoring invalid extension event 161
```

**Comment by ZhymabekRoman** [comment]
I compared two Xorg logs without and with picom. Here are the changes:
```bash
  Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
- (==) Log file: "/home/roman/.local/share/xorg/Xorg.0.log", Time: Tue Aug 29 15:18:04 2023
+ (==) Log file: "/home/roman/.local/share/xorg/Xorg.0.log", Time: Tue Aug 29 15:18:39 2023
  (==) Using system config directory "/usr/share/X11/xorg.conf.d"
  (==) No Layout section.  Using the first Screen section.
  (==) No screen section available. Using defaults.
@@ -693,18 +693,6 @@ X Protocol Version 11, Revision 0
  (II) NOUVEAU(0): Modeline "1152x864"x0.0  108.00  1152 1216 1344 1600  864 865 868 900 +hsync +vsync (67.5 kHz e)
  (II) NOUVEAU(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
  (II) NOUVEAU(0): Modeline "1280x960"x0.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
- (WW) NOUVEAU(0): PRESENT: Wait for VBlank failed: Invalid argument
  (**) Option "fd" "23"
  (II) event1  - Power Button: device removed
  (**) Option "fd" "26"
```

**Comment by ZhymabekRoman** [comment]
Possible similar bug: [Disabling an output can cause vblank events to be missed](https://bugs.launchpad.net/ubuntu/natty/+source/compiz/+bug/740126)

**Comment by absolutelynothelix** [comment]
try picom built from the latest commit in the next branch.

**Comment by ZhymabekRoman** [comment]
Same problem. I tried to specify backends, and seems to be problem appears when selecting `xrender`.

**Comment by ZhymabekRoman** [comment]
I also tried the `--no-vsync` flag, and there seems to be no bug there. `--monitor-repaint --debug-mode' also doesn't trigger any bugs either.

**Comment by ZhymabekRoman** [comment]
- Debug logs:
[picom_debug_no_vsync.txt](https://github.com/yshui/picom/files/12470936/picom_debug_no_vsync.txt)
[picom_debug_with_vsync.txt](https://github.com/yshui/picom/files/12470940/picom_debug_with_vsync.txt)

In `vsync` enabled logs, I fond that it has `Screen is now off` triggers, but without `vsync` does not appear (maybe that's problem idk).

**Comment by ZhymabekRoman** [comment]
Trace logs:
[picom_trace_no_vsync.txt](https://github.com/yshui/picom/files/12470987/picom_trace_no_vsync.txt)
[picom_trace_with_vsync.txt](https://github.com/yshui/picom/files/12470989/picom_trace_with_vsync.txt)

**Comment by absolutelynothelix** [comment]
does it happen without the `xf86-video-nouveau` package installed?

**Comment by ZhymabekRoman** [comment]
Hmmm, yes, the problem seems to be solved. Should I contact the `xf86-video-nouveau` developers regarding the issue?

**Comment by absolutelynothelix** [comment]
do you have it installed on purpose? i.e. you need some special functionality provided by it or something is broken for you without it.

**Comment by ZhymabekRoman** [comment]
Actually, I only install it because I think that `xf86-video-nouveau` package might somehow correspond to or affect X11 rendering. Anyways, thanks for helping!

**Comment by absolutelynothelix** [comment]
in general, i wouldn't recommend installing the `xf86-video-*` packages unless you need features they provide. their common functionality is provided by the modesetting driver (aka `xf86-video-modesetting`) that's, afaik, built into the x server and used by default unless other drivers are present.

see notes [here](https://wiki.archlinux.org/title/intel_graphics#Installation) and [here](https://wiki.archlinux.org/title/nouveau#Installation) for details.
