### ISSUE TITLE
Shadow opacity does not work if the shadow-color is not black (glx backend)

### ISSUE THREAD

**Issue by XoDefender** [yshui/compton#1123]
### Configuration:
shadow = true;
shadow-radius = 60;
shadow-opacity = 0.5;
shadow-offset-x = -60;
shadow-offset-y = -60;
shadow-color = "#6000B2"
#shadow-color-rule = ["#6576e5:class_g = 'fly-term'"];
vsync = true;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'dwm'",
  "class_g = 'chromium'",
  "class_g *?= 'slop'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = false;
fade-in-step = 0.023;
fade-out-step = 0.035;
fade-delta = 10
corner-radius = 11;
blur: {
  method = "dual_kawase";
  strength = 9;
  background = true;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Chromium'",
  "class_g = 'Discord'",
  "class_g = 'Dunst'",
  "class_g = 'Peek'",
  "class_g *?= 'slop'"];

mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = false;
detect-client-opacity = false;
use-ewmh-active-win = true;
unredir-if-possible = false;
detect-transient = true;
glx-no-stencil = true;
use-damage = true;
xrender-sync-fence = true;
window-shader-fg = "default";
transparent-clipping = false;
log-level = "warn";

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

opacity-rule = [
  "100:class_g = 'St' && focused",
  "50:class_g = 'St' && !focused",
  "100:fullscreen"];

### Steps of reproduction
1. Set the shadow-color which is not #000000
2. Set the shadow-opacity to 0.1

### Expected behavior
The shadow is 0.1 of opacity

### Current Behavior
The shadow is 1 of opacity

**Comment by XoDefender** [comment]
@yshui 
The error fixes if to use 
`ps->shadow_context = (void *)gaussian_kernel_autodetect_deviation(ps->o.shadow_radius);`

Instead of 
`ps->shadow_context = ps->backend_data->ops->create_shadow_context(ps->backend_data, ps->o.shadow_radius);`

And edit the glx.c
`.render_shadow = default_backend_render_shadow`

**Comment by absolutelynothelix** [comment]
it works but i agree that it's barely noticeable.
