### ISSUE TITLE
limits fps in games

### ISSUE THREAD

**Issue by dement6d** [yshui/compton#1132]
even with vsync turned off and with both backends picom has been limiting my fps to like 30 in all games for a while now

**Comment by Monsterovich** [comment]
Try `--no-frame-pacing`.

**Comment by absolutelynothelix** [comment]
> Try `--no-frame-pacing`.

and `--unredir-if-possible`.

**Comment by dement6d** [comment]
> Try `--no-frame-pacing`.

Seems like this fixed it, thanks. I wonder why this isn't enabled by default tho

**Comment by dement6d** [comment]
Ok so I just started using `telegram-desktop` and I noticed that animated emojis are in slow motion and the whole UI is pretty laggy
I kill picom and everything is fine. It was running with `--no-frame-pacing`, so it's laggy with that arg.
I relaunch it with `--unredir-if-possible` and I see a bit of an improvement with emojis, almost the same as without picom but the lag is still noticable on the new chat animation, when I send a message.
I try launching with both args and it's as laggy as with just `--no-frame-pacing`.
Any way to fix this including the first issue with games?

**Comment by yshui** [comment]
can you be more precise on what you meant by lag? are you experiencing frame drops with picom? or does picom lag behind your input?

what's your hardware & software setup? and can you try the latest `next` branch, as well as the `pacing-fix` branch, see if they make any differences.

**Comment by absolutelynothelix** [comment]
closing as stale.
