### ISSUE TITLE
misuse of keyword auto??

### ISSUE THREAD

**Issue by khlorghaal** [yshui/compton#1137]
auto keyword in C is NOT a type inference, its a storage specifier. when used without a type, the type is signed int.
https://stackoverflow.com/questions/76248851/c23-auto-vs-c11-auto

im seeing it used in the codebase a lot for pointer assignment. im totally unsure of my understanding of this, but just double checking that pointers arent being silently casted to int32s or something.

**Comment by absolutelynothelix** [comment]
https://github.com/yshui/picom/blob/751f30578e352f6cd37fc63cbf4643e47ab3587a/src/compiler.h#L10

**Comment by khlorghaal** [comment]
ah its a GCC macro

**Comment by khlorghaal** [comment]
ah its a GCC feature
