### ISSUE TITLE
rect_is_fullscreen does not take in account the task bar pannel heigth

### ISSUE THREAD

**Issue by XoDefender** [yshui/compton#1146]
The rect_is_fullscreen checks whether the window is full screen or not 
return (x <= 0 && y <= 0 && (x + wid) >= ps->root_width && (y + hei) >= ps->root_height);
The ps->root_height stores the height of the screen which is, for instance, 1440. If the window is full screen the function returns true only in case (y + hei + task_bar_height) >= ps->root_height.

**Comment by yshui** [comment]
this is intended. it checks if a window covers the _entire screen_. what you are describing is usually called "maximized", not "fullscreen"
