### ISSUE TITLE
picom --invert-color-include fails when the HOME env is unset

### ISSUE THREAD

**Issue by milahu** [yshui/compton#1148]
when i run picom in an environment where HOME is unset
then this does not work = the colors of chromium are not inverted

```
picom --invert-color-include 'class_g="Chromium-browser"'
```

fixed by setting HOME to an empty tempdir

picom version 10.2

<details>
<summary>
test-picom.py
</summary>

im calling picom from python, so this looks like

```py
#!/usr/bin/env python3

# required packages: tigervnc picom chromium

import os
import subprocess
import tempfile
import time

vnc_display = ":2"

args = [
    "Xvnc",
    # dont require a password
    "-SecurityTypes", "none",
    "-geometry", "1024x768", # default: 1024x768
    "-depth", "16", # default: 24
    "-FrameRate", "10", # maximum frame rate. default: 60
    "-localhost", # accept connections only from localhost
    vnc_display,
]
proc_xvnc = subprocess.Popen(
    args,
)
time.sleep(1)

args = ["vncviewer", vnc_display]
proc_vncviewer = subprocess.Popen(
    args,
)
time.sleep(1)

# minimal env: only PATH is set
custom_env = {
    "PATH": os.environ["PATH"],
    "DISPLAY": vnc_display,
    # setting HOME is required to fix "picom --invert-color-include"
    #"HOME": tempfile.mkdtemp(suffix="-temp_home"),
}

args = [
    "picom",

    # invert colors of chromium window
    "--invert-color-include", 'class_g="Chromium-browser"',

    # invert colors of all windows, also "save file" dialogs
    #"--invert-color-include", 'name ~= "."',

    # dont invert colors for the "feh" image viewer
    #"--invert-color-include", 'class_g != "feh"',

    # fix "picom --invert-color-include" with unset HOME
    "--config", "/dev/null",
]
proc_picom = subprocess.Popen(
    args,
    env=custom_env,
)
time.sleep(1)

args = ["chromium"]
proc_chromium = subprocess.Popen(
    args,
    env=custom_env,
)
time.sleep(5)

proc_vncviewer.kill()
proc_chromium.kill()
proc_picom.kill()
proc_xvnc.kill()
```

</details>

**Comment by yshui** [comment]
can you run picom with `--config /dev/null`? to make sure it's indeed the command line option being affected.

**Comment by milahu** [comment]
yes that works. i have updated the code in my first comment

**Comment by absolutelynothelix** [comment]
can't reproduce:
![image](https://github.com/yshui/picom/assets/52252283/6a9438c7-af9a-4fbf-a798-af52b7572a4b)

btw, the `class_g` of chromium is `Chromium` for me, not `Chromium-browser`.

**Comment by milahu** [comment]
> can't reproduce

remove `--config /dev/null`
then `invert-color-include` should fail

> the `class_g` of chromium is `Chromium` for me, not `Chromium-browser`

im using ungoogled-chromium...
use `--invert-color-include 'name ~= "."'` to invert colors of all windows

chromium darkmode is controlled by the `XDG_DATA_DIRS` env

**Comment by absolutelynothelix** [comment]
> remove `--config /dev/null`
> then `invert-color-include` should fail

still can't reproduce:
![image](https://github.com/yshui/picom/assets/52252283/2f349f0a-370a-421e-889b-d314546c82d2)

maybe `unset HOME` isn't enough to emulate an environment without the `HOME` environment variable set? :thinking:

btw, this is how it looks normally for a reference:
![image](https://github.com/yshui/picom/assets/52252283/1ecc6329-e69c-45f2-ac7d-d7ffddcf62b3)

**Comment by milahu** [comment]
whatabout the python script from https://github.com/yshui/picom/issues/1148#issue-2002892676

**Comment by absolutelynothelix** [comment]
oh, it actually causes a segfault :sweat_smile:

does #1157 fix the issue for you? btw, thanks for the script, it helped a lot in triggering the bug.
