### ISSUE TITLE
Picom crashes with glx backends

### ISSUE THREAD

**Issue by iiwwnnaa** [yshui/compton#1158]
### Platform

Voidlinux 6.1.69 LTS amd64
### GPU, drivers, and screen setup

i3 window manager

Intel 3rd Gen Core processor Graphics Controller (i915)
xf86-video-intel-2.99.917.20210115_2
mesa-23.3.1_1

**glxinfo -B**
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 4000 (IVB GT2) (0x166)
    Version: 23.3.1
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 4.2
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 23.3.1
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.2 (Compatibility Profile) Mesa 23.3.1
OpenGL shading language version string: 4.20
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 23.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

### picom version

v10

<details>
<summary>Diagnostics</summary>

**Version:** v10

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/xxx/.config/picom/picom.conf

### Drivers (inaccurate):

Intel

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: crocus
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

It happens with only one line config.
backend="glx"

</details>

### Steps of reproduction

run
picom --config=/dev/null --backend=glx
or
picom (with config)

### Expected behavior
Picom with glx backends running with no problem

### Current Behavior
Picom crashes with glx backends.

### Stack trace

###----------------------------------------------DEBUG BEGIN--------------------------------------------------------###
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_OPACITY is 440
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_FRAME_EXTENTS is 382
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_STATE is 370
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_NAME is 332
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_PID is 391
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_NAME is 39
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_CLASS is 67
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_ICON_NAME is 37
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_TRANSIENT_FOR is 68
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_WINDOW_ROLE is 373
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_CLIENT_LEADER is 371
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom WM_CLIENT_MACHINE is 36
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_ACTIVE_WINDOW is 362
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _COMPTON_SHADOW is 441
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE is 342
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_DESKTOP is 442
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_DOCK is 344
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_TOOLBAR is 347
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_MENU is 349
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_UTILITY is 346
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_SPLASH is 348
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_DIALOG is 345
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_NORMAL is 343
[ 12/26/2023 09:01:45.396 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_DROPDOWN_MENU is 350
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_POPUP_MENU is 351
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_TOOLTIP is 352
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_NOTIFICATION is 353
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_COMBO is 401
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_WINDOW_TYPE_DND is 402
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_STATE is 341
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_STATE_FULLSCREEN is 336
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_BYPASS_COMPOSITOR is 443
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom UTF8_STRING is 326
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom C_STRING is 444
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom COMPTON_VERSION is 445
[ 12/26/2023 09:01:45.397 atom_getter DEBUG ] Atom _NET_WM_CM_S0 is 389
[ 12/26/2023 09:01:45.397 init_overlay DEBUG ] overlay = 0x00000070
[ 12/26/2023 09:01:45.398 file_watch_init DEBUG ] Starting watching for file changes
[ 12/26/2023 09:01:45.398 file_watch_add DEBUG ] Adding "/dev/null" to watched files
[ 12/26/2023 09:01:45.398 file_watch_add INFO ] "/dev/null" is not a regular file, not watching it.
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x0040000d
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400002
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x0040000e
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400010
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400011
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400012
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400013
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400014
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400015
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400017
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x0040001f
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00400016
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00800001
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00a00001
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00800003
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x00800008
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x01000001
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x01000009
[ 12/26/2023 09:01:45.398 add_win DEBUG ] Adding window 0x01200004
[ 12/26/2023 09:01:45.398 session_init DEBUG ] Initial stack:
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x01200004
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x01000009
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x01000001
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00800008
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00800003
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00a00001
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00800001
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400016
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x0040001f
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400017
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400015
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400014
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400013
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400012
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400011
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400010
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x0040000e
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x00400002
[ 12/26/2023 09:01:45.398 session_init DEBUG ] 0x0040000d
[ 12/26/2023 09:01:45.398 handle_pending_updates DEBUG ] Delayed handling of events, entering critical section
[ 12/26/2023 09:01:45.398 fill_win DEBUG ] Managing window 0x01200004
[ 12/26/2023 09:01:45.398 win_set_flags DEBUG ] Set flags 1952 to window 0x01200004 ((null))
[ 12/26/2023 09:01:45.398 win_set_flags DEBUG ] Set flags 128 to window 0x01200004 ((null))
[ 12/26/2023 09:01:45.398 fill_win DEBUG ] Managing window 0x01000009
[ 12/26/2023 09:01:45.398 win_set_flags DEBUG ] Set flags 1952 to window 0x01000009 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x01000009 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x01000001
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00800008
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00800008 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00800008 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00800003
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00800003 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00800003 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00a00001
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00800001
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00400016
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00400016 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00400016 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x0040001f
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x0040001f ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x0040001f ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 64 to window 0x0040001f ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00400017
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00400017 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00400017 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00400015
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00400015 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00400015 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00400014
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 1952 to window 0x00400014 ((null))
[ 12/26/2023 09:01:45.399 win_set_flags DEBUG ] Set flags 128 to window 0x00400014 ((null))
[ 12/26/2023 09:01:45.399 fill_win DEBUG ] Managing window 0x00400013
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x00400013 ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x00400013 ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x00400012
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x00400012 ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x00400012 ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x00400011
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x00400011 ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x00400011 ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x00400010
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x00400010 ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x00400010 ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x0040000e
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x0040000e ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x0040000e ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x00400002
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1952 to window 0x00400002 ((null))
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 128 to window 0x00400002 ((null))
[ 12/26/2023 09:01:45.400 fill_win DEBUG ] Managing window 0x0040000d
[ 12/26/2023 09:01:45.400 map_win_start DEBUG ] Mapping (0x0040001f "(null)")
[ 12/26/2023 09:01:45.400 map_win_start DEBUG ] Window (0x0040001f) has type unknown
[ 12/26/2023 09:01:45.400 map_win_start DEBUG ] Window 0x0040001f has opacity 0.000000, opacity target is 1.000000
[ 12/26/2023 09:01:45.400 win_set_flags DEBUG ] Set flags 1 to window 0x0040001f ((null))
[ 12/26/2023 09:01:45.400 win_skip_fading DEBUG ] Skipping fading process of window 0x0040001f ((null))
[ 12/26/2023 09:01:45.400 win_clear_flags DEBUG ] Clear flags 64 from window 0x0040001f ((null))
[ 12/26/2023 09:01:45.400 win_recheck_client DEBUG ] (0x0040001f): client 0x01000003
[ 12/26/2023 09:01:45.400 win_on_factor_change DEBUG ] Window 0x0040001f ((null)) factor change
[ 12/26/2023 09:01:45.400 win_determine_shadow DEBUG ] Determining shadow of window 0x0040001f ((null))
[ 12/26/2023 09:01:45.400 win_determine_shadow DEBUG ] Shadow disabled by wintypes
[ 12/26/2023 09:01:45.400 win_determine_blur_background DEBUG ] Determining blur-background of window 0x0040001f ((null))
[ 12/26/2023 09:01:45.400 win_on_factor_change DEBUG ] Window mode changed to 2
[ 12/26/2023 09:01:45.401 win_update_name DEBUG ] (0x0040001f): client = 0x01000003, name = "Terminal - ", ret = 1
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window 0x0040001f (Terminal - ) factor change
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Determining shadow of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Shadow disabled by wintypes
[ 12/26/2023 09:01:45.401 win_determine_blur_background DEBUG ] Determining blur-background of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window mode changed to 2
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 32 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_set_flags DEBUG ] Set flags 9 to window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_set_flags DEBUG ] Set flags 9 to window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window 0x0040001f (Terminal - ) factor change
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Determining shadow of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Shadow disabled by wintypes
[ 12/26/2023 09:01:45.401 win_determine_blur_background DEBUG ] Determining blur-background of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window mode changed to 0
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 256 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 512 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_update_screen DEBUG ] Window 0x0040001f (Terminal - ), 15x15+1570x870, is not contained by any screen
[ 12/26/2023 09:01:45.401 win_update_name DEBUG ] (0x0040001f): client = 0x01000003, name = "Terminal - ", ret = 0
[ 12/26/2023 09:01:45.401 win_set_flags DEBUG ] Set flags 1024 to window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 128 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 128 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window 0x0040001f (Terminal - ) factor change
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Determining shadow of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Shadow disabled by wintypes
[ 12/26/2023 09:01:45.401 win_determine_blur_background DEBUG ] Determining blur-background of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window mode changed to 0
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 1024 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window 0x0040001f (Terminal - ) factor change
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Determining shadow of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_determine_shadow DEBUG ] Shadow disabled by wintypes
[ 12/26/2023 09:01:45.401 win_determine_blur_background DEBUG ] Determining blur-background of window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 win_on_factor_change DEBUG ] Window mode changed to 0
[ 12/26/2023 09:01:45.401 win_clear_flags DEBUG ] Clear flags 9 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.401 handle_pending_updates DEBUG ] Exited critical section
[ 12/26/2023 09:01:45.401 redirect_start DEBUG ] Redirecting the screen.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_SGI_video_sync.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Missing GLX extension GLX_SGI_swap_control.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_OML_sync_control.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_MESA_swap_control.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_EXT_swap_control.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_EXT_texture_from_pixmap.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_ARB_create_context.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_EXT_buffer_age.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Missing GLX extension GLX_ARB_create_context_robustness.
[ 12/26/2023 09:01:45.446 glx_has_extension INFO ] Found GLX extension GLX_MESA_query_renderer.
[ 12/26/2023 09:01:45.459 glGetUniformLocationChecked INFO ] Failed to get location of uniform 'time'. This is normal when using custom shaders.
[ 12/26/2023 09:01:45.462 gl_has_extension INFO ] Missing GL extension GL_GREMEDY_string_marker.
[ 12/26/2023 09:01:45.462 gl_init DEBUG ] GL_VENDOR = Intel
[ 12/26/2023 09:01:45.464 gl_create_kernel_blur_context INFO ] Uniform locations: 6 5 3 4 9
[ 12/26/2023 09:01:45.465 gl_create_kernel_blur_context INFO ] Uniform locations: 6 5 3 4 9
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x01200004 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x01200004 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x01000009 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x01000009 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00800008 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00800008 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00800003 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00800003 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400016 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400016 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x0040001f (Terminal - ) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400017 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400017 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400015 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400015 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400014 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400014 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400013 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400013 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400012 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400012 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400011 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400011 ((null))
[ 12/26/2023 09:01:45.465 initialize_backend DEBUG ] Marking window 0x00400010 ((null)) for update after redirection
[ 12/26/2023 09:01:45.465 win_set_flags DEBUG ] Set flags 9 to window 0x00400010 ((null))
[ 12/26/2023 09:01:45.466 initialize_backend DEBUG ] Marking window 0x0040000e ((null)) for update after redirection
[ 12/26/2023 09:01:45.466 win_set_flags DEBUG ] Set flags 9 to window 0x0040000e ((null))
[ 12/26/2023 09:01:45.466 initialize_backend DEBUG ] Marking window 0x00400002 ((null)) for update after redirection
[ 12/26/2023 09:01:45.466 win_set_flags DEBUG ] Set flags 9 to window 0x00400002 ((null))
[ 12/26/2023 09:01:45.466 atom_getter DEBUG ] Atom _XROOTPMAP_ID is 447
[ 12/26/2023 09:01:45.466 atom_getter DEBUG ] Atom _XSETROOT_ID is 448
[ 12/26/2023 09:01:45.466 redirect_start DEBUG ] Screen redirected.
[ 12/26/2023 09:01:45.466 draw_callback_impl DEBUG ] Re-run _draw_callback
[ 12/26/2023 09:01:45.466 handle_pending_updates DEBUG ] Delayed handling of events, entering critical section
[ 12/26/2023 09:01:45.466 ev_handle DEBUG ] event  MapNotify serial 0x000000e4 window 0x00000070 "(Overlay)"
[ 12/26/2023 09:01:45.466 ev_handle DEBUG ] event     Expose serial 0x000000e4 window 0x00000070 "(Overlay)"
[ 12/26/2023 09:01:45.466 win_bind_pixmap DEBUG ] New named pixmap for 0x0040001f (Terminal - ) : 0x0120001a
[ 12/26/2023 09:01:45.466 glx_find_fbconfig DEBUG ] Looking for FBConfig for RGBA8888, depth 32
[ 12/26/2023 09:01:45.467 glx_bind_pixmap DEBUG ] depth 32, rgba 1
[ 12/26/2023 09:01:45.467 win_clear_flags DEBUG ] Clear flags 2 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.467 win_clear_flags DEBUG ] Clear flags 9 from window 0x0040001f (Terminal - )
[ 12/26/2023 09:01:45.467 handle_pending_updates DEBUG ] Exited critical section
[ 12/26/2023 09:01:45.586 handle_queued_x_events FATAL ERROR ] X11 server connection broke (error 1)

###----------------------------------------------DEBUG END-------------------------------------------------------###

**Comment by absolutelynothelix** [comment]
does it happen with picom built from the latest commit in the `next` branch? also, do you have a reason to have `xf86-video-intel` installed? could you try to remove it, reboot and reproduce the issue?

**Comment by iiwwnnaa** [comment]
> does it happen with picom built from the latest commit in the `next` branch? also, do you have a reason to have `xf86-video-intel` installed? could you try to remove it, reboot and reproduce the issue?

Yes, xf86-video-intel caused problem.
I removed it and now it works!

P.S : I just installed voidlinux to test, I was on other distros due to picom issues. xD
