### ISSUE TITLE
FTBFS with -Dxinerama=false

### ISSUE THREAD

**Issue by kapsh** [yshui/compton#116]
### Platform
Exherbo amd64

### Compton version
cea010afecfe34aaf2d7f590367c4a860eea0002

### Steps of reproduction

1. `git clone`
2. `meson . build -Dxinerama=false `
3. `ninja -C build`

### Expected behavior
Builds.

### Current Behavior
```
../src/compton.c: In function 'session_init':
../src/compton.c:2420:39: error: 'xcb_xinerama_id' undeclared (first use in this function); did you mean 'xcb_generate_id'?
   xcb_prefetch_extension_data(ps->c, &xcb_xinerama_id);
                                       ^~~~~~~~~~~~~~~
                                       xcb_generate_id
```

[build.log](https://github.com/yshui/compton/files/2873346/build.log)

**Comment by kapsh** [comment]
Guarding with `ifdef` fixes this, but I don't know the code to tell about consequences.
```
diff --git a/src/compton.c b/src/compton.c
index 979ad2f..9465173 100644
--- a/src/compton.c
+++ b/src/compton.c
@@ -2417,7 +2417,9 @@ session_init(int argc, char **argv, Display *dpy, const char *config_file,
   xcb_prefetch_extension_data(ps->c, &xcb_shape_id);
   xcb_prefetch_extension_data(ps->c, &xcb_xfixes_id);
   xcb_prefetch_extension_data(ps->c, &xcb_randr_id);
+#ifdef CONFIG_XINERAMA
   xcb_prefetch_extension_data(ps->c, &xcb_xinerama_id);
+#endif
   xcb_prefetch_extension_data(ps->c, &xcb_present_id);
   xcb_prefetch_extension_data(ps->c, &xcb_sync_id);
```

**Comment by yshui** [comment]
@kapsh Is there any real reasons to disable xinerama? Because I plan to make xinerama non-optional.

**Comment by kapsh** [comment]
@yshui 	hello. No, no actual reason, but this is documented. 

I am migrating from old (chjj's) compton and the package in my distro (source-based) had option for disabling xinerama because it was adding an extra dependency on libXinerama. Currently (as in v5.1) it really doesn't change much: libxcb usually comes in single package and it's required anyway.
