### ISSUE TITLE
High CPU usage after suspend.

### ISSUE THREAD

**Issue by yagi-tan** [yshui/compton#1168]
### Platform
Debian 12
Linux debian 6.1.0-17-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

### GPU, drivers, and screen setup
GPU: NVIDIA GeForce GT 730
Driver: nvidia-tesla-470-driver 470.223.02-2~deb12u1
Setup: Single monitor desktop.

<details>
<summary>glxinfo -B</summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1750 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GT 730/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.223.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 470.223.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.223.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

### Environment
LXDE

### picom version
vgit-702e3, v11. Problem appears starting from commit a28e221.

<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-702e3

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: None

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GT 730/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GT 730/PCIe/SSE2
```

</details>

### Configuration:
```picom -b --backend glx --vsync```

### Steps of reproduction
1. Run ```picom```, then suspend/standby the system.
2. Wakeup system.

### Expected behavior
```picom``` to have low CPU usage (0-2%) like before suspend.

### Current Behavior
```picom``` high CPU usage (~85%) after suspend. Restarting the process fixes the issue.

### Log file
[picom_702e30.tar.gz](https://github.com/yshui/picom/files/14074685/picom_702e30.tar.gz)

**Comment by desbma** [comment]
I have the same exact issue, 100% CPU usage when returning from hibernation. A restart of the picom process fixes it. I also have this in my config file:
```
backend = "glx";
vsync = true;
```

I am on Arch Linux, with picom package version `11-4`. This is a recent regression, as the issue was not occurring previously.

**Comment by yshui** [comment]
does it happen without vsync?

**Comment by absolutelynothelix** [comment]
can't reproduce on an intel gpu neither with the `present` vblank scheduler nor with the `sgi_video_sync` one.

**Comment by absolutelynothelix** [comment]
can reproduce on an nvidia gpu only with the `sgi_video_sync` vblank scheduler.

**Comment by yagi-tan** [comment]
> does it happen without vsync?
> can reproduce on an nvidia gpu only with the `sgi_video_sync` vblank scheduler.

![nvidia](https://github.com/yshui/picom/assets/66814493/8b6392d2-b218-42a9-be0a-6df02174d79b)

Since there's something about vblank, should I disable this 'Sync to VBlank' config and try again without vsync?

**Comment by yshui** [comment]
@yagi-tan just set `vsync = false` in picom.conf

**Comment by yagi-tan** [comment]
Oh, ```picom --no-vsync --backend glx``` does fix the problem.

**Comment by absolutelynothelix** [comment]
@yagi-tan, you could also try `PICOM_DEBUG=force_vblank_sched=present picom --backend=glx --vsync`.

**Comment by yagi-tan** [comment]
> @yagi-tan, you could also try `PICOM_DEBUG=force_vblank_sched=present picom --backend=glx --vsync`.

@absolutelynothelix Ahh, to force using ```present``` scheduler, isn't it? Yup, tested just now and that also works. Which one is better,  ```present```+vsync or ```sgi```+no-vsync? Seems that both use similar CPU/RAM usage.

**Comment by yshui** [comment]
@yagi-tan please don't worry about the schedulers! and don't persist the `PICOM_DEBUG` environment variable, it's for debug only.

**Comment by yagi-tan** [comment]
@yshui I see. All right then, thanks all for quick responses. Feel free to close this issue.
