### ISSUE TITLE
debug logging can dead lock the X server

### ISSUE THREAD

**Issue by yshui** [yshui/compton#1173]
logging to the terminal can block, e.g. if the terminal emulator is not processing the outputs fast enough. and with debug logging enabled, picom logs in the server critical section (i.e. between XGrabServer and XUngrabServer). if picom got blocked there, it will in turn block the terminal emulator, because it will not be able to update its window when the server is grabbed. a dead lock.

this is low priority because debug logging is not usually enabled for day-to-day uses.

**Comment by yshui** [comment]
potential solution: make logging asynchronous with libev.

**Comment by absolutelynothelix** [comment]
closing as stale.
