### ISSUE TITLE
[Request] glFinish timing

### ISSUE THREAD

**Issue by Enokilis** [yshui/compton#1175]
With the GLX backend, the option to swap out glFlush with glFinish takes place before a glxSwapBuffers. There is an additional glFlush succeeding the buffer swap that cannot be toggled. If an additional parameter could decide where in the chain this GL call swap (pun not intended) occurs, latency could be reduced when the compositor is V-synced.

Observations:
With default glFinish, a window being dragged lags two frames behind the cursor.
With glFinish after a buffer swap, a window being dragged lags one frame behind the cursor.

**Comment by absolutelynothelix** [comment]
`glFinish` and `glFlush` are only used in legacy backends. default backends use neither.

**Comment by absolutelynothelix** [comment]
given what i’ve written above, could you please clarify what your request is? otherwise this issue will be closed as invalid and stale.

**Comment by Enokilis** [comment]
If those backends are not to be maintained, then consider this closed.
