### ISSUE TITLE
xinerama-shadow-crop = true results in a FATAL ERROR

### ISSUE THREAD

**Issue by ortango** [yshui/compton#118]
### Platform
archlinux x64 updated.

### GPU, drivers, and screen setup
intel, 2 monitors side by side

### Environment
bspwm

### Compton version
v5-rc4-95-gbb8fd08

### Compton configuration:
```
xinerama-shadow-crop = true;
```
xcb-xinerama is present and compton is building with it fine

### Expected behavior
compton starts with xinerama-shadow-crop = true

### Current Behavior
compton exits with `session_init FATAL ERROR ] Xinerama support not compiled in. xinerama-shadow-crop cannot be enabled`

### Reason

[this ifdef](https://github.com/yshui/compton/blob/635351c8204e683cc47ba239bea684f04f0e52b5/src/compton.c#L2593-L2599), removing it fixes the issue, unless the config is supposed to be blocked currently. (i'm not sure the option is working as expected for me after removing that ifdef)

**Comment by yshui** [comment]
Thanks!
