### ISSUE TITLE
[ session_init FATAL ERROR ] Another composite manager is already running (Ubuntu 20.04)

### ISSUE THREAD

**Issue by rabb1tl0ka** [yshui/compton#1187]
### Platform

OS: Ubuntu 20.04.6 LTS x86_64 
Host: 20UN002GPG ThinkPad X1 Nano Gen 1 
Kernel: 5.15.0-92-generic 
Uptime: 6 mins 
Packages: 2909 (dpkg), 1 (brew), 11 (flatpak), 39 (snap) 
Shell: bash 5.0.17 
Resolution: 2160x1350, 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Orchis-Purple [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i5-1130G7 (8) @ 4.000GHz 
GPU: Intel Device 9a40 
Memory: 6947MiB / 15709MiB

### picom version
picom --version
vgit-a39cd

<details>
<summary>Diagnostics</summary>

**Version:** vgit-a39cd

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/w1ldrabb1t/.config/picom/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

I'm using the sample config with the only difference being:
```
backend = "glx"
```
</details>

### Steps of reproduction
1. simply exec "picom -b" on the Ubuntu terminal

### Expected behavior
Just work? :)

### Current Behavior
[ 08/02/2024 23:04:32.355 session_init FATAL ERROR ] Another composite manager is already running

### Stack trace
No stack trace.

**Comment by rabb1tl0ka** [comment]
Forgo to mention that I tried to check what is the composer currently running but I got no results.

```
~$ pgrep -l compositor
~$ pgrep -l compos
```

**Comment by yshui** [comment]
Mutter is the compositor
