### ISSUE TITLE
How to install in ubuntu?

### ISSUE THREAD

**Issue by enanajmain** [yshui/compton#120]
Hello,
I seem to have forgotten how to install compton from source. I've done it before.
Now, I've advanced till
```
meson --buildtype=release . build
ninja -C build
```
and there is a binary at `build/src/`
But I looked at my already install compton binary, which is installed in `/usr/local/bin`, along with two other files named
```
compton-convgen.py
compton-trans
```
I don't know if these files were installed with my first official installation. So, do I just copy `compton/build/src/compton` and put it in my $PATH? Or do I need to do anything else?

**Comment by yshui** [comment]
@enanajmain Try `ninja -C build install`

**Comment by enanajmain** [comment]
Thanks. It worked. Maybe you could add this info in the README?

**Comment by yshui** [comment]
I will
