### ISSUE TITLE
frame-opacity for WINDOW_TYPE settings

### ISSUE THREAD

**Issue by BEST8OY** [yshui/compton#1204]
### Platform
Arch

### Environment
X11 , dwm suckless

### picom version
11.2

Hello
Is it possible to have that?
I couldn't eliminate this weird frame unless set the frame-opacity 0

![image](https://github.com/yshui/picom/assets/70865987/c3bd9670-1c45-409b-912e-4669b002aa93)

**Comment by absolutelynothelix** [comment]
this looks like an issue caused by window manager misconfiguration and covering it with picom instead of fixing it is a bit wrong.

**Comment by Monsterovich** [comment]
> I couldn't eliminate this weird frame unless set the frame-opacity 0

Because this frame is drawn by the window manager, the compositor has nothing to do with it. There are apps with completely transparent backgrounds: conky, plank. For them it's necessary to edit dwm source code to avoid drawing a border.
