### ISSUE TITLE
True version output

### ISSUE THREAD

**Issue by samarulmeu** [yshui/compton#1207]
I am trying to create a script that checks my version against the latest one available. The problem is that when I do `picom --version` I get `v11` instead of `v11.2` the latest compiled version. 

Could you include the correct version inside every release?

Thank you!

**Comment by absolutelynothelix** [comment]
done in 6a678cb4a1999a4baf7cc9aca4d30dd8de63564d (included in [the v12-rc3 pre-release](https://github.com/yshui/picom/releases/tag/v12-rc3)).

closing as done.
