### ISSUE TITLE
shadow-r/g/b doesn't variate after the recent versions

### ISSUE THREAD

**Issue by Trinity3e** [yshui/compton#1210]
e.g. shadow-blue=0 turns that color off, shadow-blue=1 and anything higher is treated like 255.
backend is glx.
I cannot pinpoint exactly the version it started behaving like this, sorry about that.
I can provide any other info if requested.
Thanks in advance.

**Comment by absolutelynothelix** [comment]
the `shadow-red`, `shadow-green` and `shadow-blue` options accept floating point numbers from `0` to `1`. it's stated in the man page.
