### ISSUE TITLE
BSPWM - Sending Window to other desktop breaks painting

### ISSUE THREAD

**Issue by llitz** [yshui/compton#122]
compton version: tried with ~~stable/5 and~~ next branches on 2019-02-22
backend = xrender

Running compton and sending a window to a different desktop on bspwm blurs the whole screen, when going to the other screen the window is completely invisible. If this is an extra window of firefox or urxvt, some windows back on the original desktop will be randomly painted or not.

Have tried playing with different config options in file without luck.
**Works fine on stable/5**

Attached is debug log and config file

[compton.debug.gz](https://github.com/yshui/compton/files/2895316/compton.debug.gz)
[compton.conf.gz](https://github.com/yshui/compton/files/2895321/compton.conf.gz)

**Comment by yshui** [comment]
@llitz Can you run with `log-level = trace` and attach the log again? Thanks.

**Comment by llitz** [comment]
Here we go, didn't realize we had a trace option.
[compton.debug.gz](https://github.com/yshui/compton/files/2895702/compton.debug.gz)

**Comment by yshui** [comment]
@llitz Current `next` should fix your problem, can you give it a go? 

(Related commits 8d639f4, 1005e61. Yes, this is caused by two bugs).

**Comment by llitz** [comment]
@yshui Fix worked, that was some very fast tracking, nice job
