### ISSUE TITLE
On KDE6 spectacle no longer becomes invisible while making rectangular selection

### ISSUE THREAD

**Issue by Hi-Angel** [yshui/compton#1230]
### Platform

Archlinux

### GPU, drivers, and screen setup

* Intel GPU, `modesetting`, a single monitor.
* Mesa version: `24.0.3`
* `glxinfo -B`
    <details>
        <summary>Details</summary>

    ```
    name of display: :0
    display: :0  screen: 0
    direct rendering: Yes
    Extended renderer info (GLX_MESA_query_renderer):
        Vendor: Intel (0x8086)
        Device: Mesa Intel(R) UHD Graphics (CML GT2) (0x9bc4)
        Version: 24.0.3
        Accelerated: yes
        Video memory: 15773MB
        Unified memory: yes
        Preferred profile: core (0x1)
        Max core profile version: 4.6
        Max compat profile version: 4.6
        Max GLES1 profile version: 1.1
        Max GLES[23] profile version: 3.2
    OpenGL vendor string: Intel
    OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)
    OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.3-arch1.2
    OpenGL core profile shading language version string: 4.60
    OpenGL core profile context flags: (none)
    OpenGL core profile profile mask: core profile

    OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2
    OpenGL shading language version string: 4.60
    OpenGL context flags: (none)
    OpenGL profile mask: compatibility profile

    OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.3-arch1.2
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    ```
    </details>

### Environment

KDE + i3

### picom version

11.2, `picom --version` is `vgit-89c2c`.

<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-89c2c

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/constantine/.config/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
```
</details>

### Configuration:

```
inactive-opacity = 0.85;
```

### Steps of reproduction

I don't know if it's a `picom` or Spectacle problem, but the thing is, it does not reproduce if I disable `picom`. So it may be a regression in Spectacle, but it also might be a Picom bug that was hidden so far. So [I reported the problem to KDE](https://bugs.kde.org/show_bug.cgi?id=484652) and now I'm creating a report here. It appeared after upgrading to KDE6 whereas `picom` **has not** been upgraded.

-----------

1. Create config: `echo 'inactive-opacity = 0.85;' > ~/.config/picom.conf`
2. Run `picom`
3. Execute `spectacle`
4. Press `Rectangular Region` button, which will start the process of making rectangular selection

### Expected behavior

For the duration of making the selection the window will disappear

### Current Behavior

Spectacle window either does not disappear, or it may partially disappear leaving a transparent rectangle behind, in which case pressing Escape and `Rectangular Region` again would make the next time full window appear rather than gray rectangle.

### Other details

Screencast of the problem:

https://github.com/yshui/picom/assets/7935057/e452a26b-c93e-459e-8d17-85a1ac871fef

**Comment by yshui** [comment]
Can you try the linked PR?

**Comment by Hi-Angel** [comment]
> Can you try the linked PR?

Sure, just tried, nothing seems to have changed, `spectacle` is still visible while making rectangular selection.

**Comment by yshui** [comment]
oh, didn't realize you weren't running the latest git version.

I think I have hit this problem before. IIRC, spectacle captures the screen first then lets you crop a region out of it, if spectacle captures the screen too quickly, it will capture the screen with itself still in it.

What if you use a 1 seconds delay, does that help?

**Comment by Hi-Angel** [comment]
> What if you use a 1 seconds delay, does that help?

Haha, yes, in fact it does, I too found this workaround yesterday

> I think I have hit this problem before. IIRC, spectacle captures the screen first then lets you crop a region out of it, if spectacle captures the screen too quickly, it will capture the screen with itself still in it.

Hmm, interesting. But that leave me wondering: why the problem stops happening if Picom isn't running?

**Comment by Hi-Angel** [comment]
Yo, I found out where the regression has happened in Spectacle! Ha! It was in commit https://github.com/KDE/spectacle/commit/efc267076 and the reason being is that Spectacle has always been setting a 80ms timeout after making its window invisible and before making a screenshot. However, that commit changed the condition which results in the timeout always being zero.

@yshui you are amazing, thank you very much! I would have never found it out wasn't it for you comment! Will send a fix to Spectacle then

**Comment by Hi-Angel** [comment]
For posterity: a Spectacle merge request https://invent.kde.org/graphics/spectacle/-/merge_requests/342

**Comment by raphaelbastide** [comment]
I have a similar issue with Spectacle’s Rectangular Region mode. The window is getting screenshot for me too. 1-second delay solves the problem for me too. However, I don’t know what `picom` is and don’t hav it installed on my system.
I run Spectacle 23.08.5

**Comment by Hi-Angel** [comment]
@raphaelbastide please create a report on [KDE bugzilla](https://bugs.kde.org/enter_bug.cgi).

I seem to recall something similar lately, but got almost no spare time, so unable to look at it. Though, you can try debugging the Spectacle issue by using the linked MR changes as an analogy 😊
