### ISSUE TITLE
RealTime option astounding

### ISSUE THREAD

**Issue by UrbanDesimator** [yshui/compton#1243]
### picom version

<details>
<summary>Diagnostics</summary>

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
// Paste your configuration here
```
</details>

### Steps of reproduction

1.
2.

**Comment by UrbanDesimator** [comment]
This isn't an issue it's just to say the --realtime startup option is outstanding, 
on a MSi Geforce GTX660 Ti  with nouveau driver. pleased to see a huge boost in performance compared to same .conf without --realtime. I'm using the sample picom.conf set to glx backend, shadows enabled, fading disabled and opacity only on dropdown_menu and popup_menu.
  Thank You for all the hard work coding and testers.

**Comment by absolutelynothelix** [comment]
thanks for the feedback. we were considering to remove this option as we were unsure about it's performance impact but this makes us reconsider.

**Comment by MR-Diamond** [comment]
I vote to keep this option; I noticed that Picom is more smooth, with the `--realtime` flag.
