### ISSUE TITLE
Picom not launcing no matter what. Instead i get this error:

### ISSUE THREAD

**Issue by Not1shanlol** [yshui/compton#1275]
~ > picom
[ 06/18/2024 21:44:37.325 parse_config_libconfig WARN ] Please use xrender-sync-fence instead of xrender-sync.
free(): double free detected in tcache 2
fish: Job 1, 'picom' terminated by signal SIGABRT (Abort)

~>

**Comment by Not1shanlol** [comment]
i have not gotten a solution for this in WEEKS btw

**Comment by absolutelynothelix** [comment]
it would be helpful to know what picom version you're running and what's your configuration file at least.

**Comment by Not1shanlol** [comment]
> it would be helpful to know what picom version you're running and what's your configuration file at least.

my bad, its the latest one. https://aur.archlinux.org/picom-git.git
im on arch + i3

here is my config file in .config/picom/picom.conf

`backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;

#glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;`

**Comment by yshui** [comment]
@Not1shanlol that warning message you saw has long been removed (it was [4 years ago](https://github.com/yshui/picom/commit/17831a7be3ecf02b874738009fbb2e244de6bd67)), you are running an exceedingly old version of picom
