### ISSUE TITLE
`id` pattern does not work in picom.conf `opacity-rule`

### ISSUE THREAD

**Issue by 513ry** [yshui/compton#1285]
### Platform
Arch Linux intel64

### GPU, drivers, and screen setup
    Intel(R) UHD Graphics 620 (WHL GT2), two monitors configured side-by-side with xrandr
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
    Version: 24.1.2
    Accelerated: yes
    Video memory: 3783MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.2-arch1.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.2-arch1.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.2-arch1.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
 ```

### Environment
I run i3, version 4.23. Main windows are alacritty and firefox.

### picom version
vgit-89c2c

<details>
<summary>Diagnostics</summary>

```
$ picom --diagnostics
```

**Version:** vgit-89c2c

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/lr/.config/picom.conf

### Drivers (inaccurate):

Intel

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
inactive-opacity = 0.80;
active-opacity = 0.90;
frame-opacity = 0.80;

blur: {
  method = "dual_kawase";
  strength = 20;
  background = false;
  background-frame = false;
  background-fixed = false;
}

opacity-rule = [
  "80:class_g = 'alacritty' && !_NET_WM_STATE@:32a",
  "0:_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[2]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[3]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[4]:32a *= '_NET_WM_STATE_HIDDEN'",
  "100:class_g = 'firefox' && focused",
  "100:class_g = 'firefox' && !focused",
  "100:class_g = 'feh' && focused",
  "100:class_g = 'feh' && !focused",
  "100:id = 0xe00003",
];
```
</details>

### Steps of reproduction
I don't know if this problem is not specific to my system and picom version.  So in the config above the most important part is the body of `opacity-rule`. You can see I have defined a few applications by `class_g` (and  it works, firefox and feh turn solid) and one by id "0xe00003".

### Expected behavior
I expect windows with id "0xe00003" (as can be obtained by xwininfo) to be 100% solid.

### Current Behavior
The window specified by id keeps previous set opacity.

**Comment by absolutelynothelix** [comment]
try picom built from the latest commit in the `next` branch.

**Comment by absolutelynothelix** [comment]
closing as stale.

**Comment by 513ry** [comment]
Sorry, I did not look into that. After compiling picom 12 my previous config just crashed picom (even without the id directive). Was there any breaking changes from 11 to 12?

**Comment by 513ry** [comment]
Actually, I checked this now and even after deleting my config picom 12 is still crashing, even the one packaged by arch linux.

**Comment by absolutelynothelix** [comment]
@513ry, post the backtrace.

**Comment by 513ry** [comment]
Yes, I'm a big dum dum. So, after closer look it does run without config, the problem was that I deleted the config but left the empty "~/.config/picom.conf" file, which probably caused picom to not look for it's default config.

Anyways, here is the config I used for picom 11:

```
inactive-opacity = 0.80;
active-opacity = 0.90;
frame-opacity = 0.80;

blur: {
  method = "dual_kawase";
  strength = 20;
  background = false;
  background-frame = false;
  background-fixed = false;
}

opacity-rule = [
  "80:class_g = 'alacritty' && !_NET_WM_STATE@:32a",
  "0:_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[2]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[3]:32a *= '_NET_WM_STATE_HIDDEN'",
  "0:_NET_WM_STATE@[4]:32a *= '_NET_WM_STATE_HIDDEN'",
  "100:class_g = 'Gimp' && focused",
  "100:class_g = 'Gimp' && !focused",
];
```

**Comment by 513ry** [comment]
@absolutelynothelix Can you help me figure out how to get a backtrack when I start picom on x server via `startx`?

**Comment by 513ry** [comment]
The exact picom version at arch is `12.1-3`

**Comment by yshui** [comment]
what did picom print when it crashes?

**Comment by 513ry** [comment]
I don't see `startx` giving me any information when picom crashes. I just see that picom is not running after I start x

**Comment by absolutelynothelix** [comment]
@513ry, it seems that picom is not crashing, it just doesn't start because you didn't explicitly specify a backend:
```
workstation:~/Work/picom-upstream$ build/src/picom --config=1285.conf
...
[ 10/08/2024 16:56:17.942 sanitize_options ERROR ] Backend not specified. You must choose one explicitly. Valid ones are: 
[ 10/08/2024 16:56:17.942 sanitize_options ERROR ] 	dummy
[ 10/08/2024 16:56:17.942 sanitize_options ERROR ] 	xrender
[ 10/08/2024 16:56:17.942 sanitize_options ERROR ] 	egl
[ 10/08/2024 16:56:17.942 sanitize_options ERROR ] 	glx
[ 10/08/2024 16:56:17.942 session_init FATAL ERROR ] Failed to get configuration, usually mean you have specified invalid options.
[ 10/08/2024 16:56:17.942 main FATAL ERROR ] Failed to create new session.
```
> Was there any breaking changes from 11 to 12?

yes, the "notable changes" section of [the changelog for v12-rc1](https://github.com/yshui/picom/releases/tag/v12-rc1) says:
> * `backend` is now a required option. picom will not start if one is not specified explicitly.

**Comment by 513ry** [comment]
Thank you, that fix the problem with converting to new version. The issue is still the same, I can't set window opacity rule by id.

I tried both hexadecimal and decimal notation for id value and nothing happens.

**Comment by yshui** [comment]
@513ry `id` pattern is no longer supported in v12. how was you using id anyway? it's not a reliable way of matching windows, you will get much better results with name/class/etc.

**Comment by yshui** [comment]
i do worry that our deprecation messages are not visible enough... i guess this issue is a good example where people miss the deprecation warning because it's only printed on console.

**Comment by 513ry** [comment]
Is there no way to select a window by `id` currently? Can I still find a version that does support it? I need that for a wm interface to temperately set windows transparency selected by user.

**Comment by yshui** [comment]
can you explain your use case further? if you really want to set opacity by window id, you can always use `picom-trans`.

**Comment by 513ry** [comment]
Yes, `picom-trans` was exactly what I been trying to implement just around using the config file. Thank you!

**Comment by yshui** [comment]
still i would advice against hardcoding window IDs. you are using it with a wm window so it's a bit more predictable, but if there is any non-determinism in how your wm starts up, the IDs can change and your setup will break.

if you can match the window with anything you should use that instead of `picom-trans`.

**Comment by 513ry** [comment]
Ow no, hardcoding IDs would a terrible idea, but thank you for advice c:
