### ISSUE TITLE
Unable to ban rounded corners on gnome apps

### ISSUE THREAD

**Issue by traditionalgithub** [yshui/compton#1296]
I am not able to disable rounded corners on windows of gnome apps, even if i try to do it explicitly.  My ~/.config/picom.conf is as below : 
~~~ bash
detect-rounded-corners = false;
corner-radius = 0 
rounded-corners-exclude = [ 
  "class_g = 'file-roller'",
  "window_type = 'normal'", 
  "window_type = 'dialog'", 
  "window_type = 'desktop'", 
  "window_type = 'unknown'",
  "window_type = 'dock'",
  "window_type = 'combo'",
  "window_type = 'dnd'"
];
blur-background-frame = false;
vsync = true;
xrender-sync-fence = false;
backend = "xrender";
~~~
The image below is what it looks like when picom is absence :
![image](https://github.com/user-attachments/assets/1eefba9e-fa46-4a56-ae9c-d58f376a332e)

This is my intented result, because the mouse cursor recognizes the borders of such rectangle windows as resizable, and it is much clearer to see when stacked on light backgrounds.

However, with the .conf file mentioned above, i get the window as the below image instead when picom is running : 
![image](https://github.com/user-attachments/assets/ffff6522-c41c-4449-80fc-deaccc1265ad)
The mouse cursor does not regnize such window borders as resizable when hovering over it, and it is harder to be distinguished from light backgronds.

### Platform

EndeavourOS x86_64 (Up-to-date)
### GPU, drivers, and screen setup

GPU 1: Intel HD Graphics 630 @ 1.10 GHz [Integrated]
GPU 2: NVIDIA GeForce GTX 1060 Mobile [Discrete]
Display (eDP-1): 1920x1080 @ 60 Hz in 16″ [Built-in]
### Environment

DE: LXQt 2.0.0
WM: Openbox (X11)
### picom version

picom version 11.2-1
vgit-89c2c from running picom --version
<details>
<summary>Diagnostics</summary>
picom --diagnostics
**Version:** vgit-89c2c

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/???/.config/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) HD Graphics 630 (KBL GT2)

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
detect-rounded-corners = false;
corner-radius = 0 
rounded-corners-exclude = [ 
  "class_g = 'file-roller'",
  "window_type = 'normal'", 
  "window_type = 'dialog'", 
  "window_type = 'desktop'", 
  "window_type = 'unknown'",
  "window_type = 'dock'",
  "window_type = 'combo'",
  "window_type = 'dnd'"
];
blur-background-frame = false;
vsync = true;
xrender-sync-fence = false;
backend = "xrender";
```
</details>

### Steps of reproduction

Please see above.

**Comment by absolutelynothelix** [comment]
i have a feeling that the application is rounding it's corners itself when a compositor is present. does it happen with `xcompmgr`?

**Comment by traditionalgithub** [comment]
@absolutelynothelix Yes, it does, you are right. Seemingly not a picom problem?

**Comment by yaaama** [comment]
> @absolutelynothelix Yes, it does, you are right. Seemingly not a picom problem?

Did you manage to find a workaround? I have the same problem.

**Comment by Monsterovich** [comment]
> > @absolutelynothelix Yes, it does, you are right. Seemingly not a picom problem?
> 
> Did you manage to find a workaround? I have the same problem.

The workaround is to not use GTK4.
