### ISSUE TITLE
`transparent-clipping` doesn't seem to work with picom-12-RC

### ISSUE THREAD

**Issue by wimstefan** [yshui/compton#1317]
### Platform
Gentoo Base System release 2.15 (~amd64)

### GPU, drivers, and screen setup
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 4465 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 555.58.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 555.58.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 555.58.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
awesome v: 4.3-1655-gad0290bc-dirty

### picom version
vgit-19b43
<details>
<summary>Diagnostics</summary>
**Version:** vgit-19b43

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file specified: /home/swimmer/.config/picom/awesomewm.conf
* Config file used: /home/swimmer/.config/picom/awesomewm.conf

### Drivers (inaccurate):

NVIDIA

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
backend = "glx";
vsync = true;
detect-client-opacity = true;
detect-client-leader = true;
detect-transient = true;
transparent-clipping = true;
use-damage = true;

shadow = true;
shadow-radius = 24;
shadow-offset-x = -4;
shadow-offset-y = -4;
shadow-opacity = 0.4;

fading = true;
fade-in-step = 0.02;
fade-out-step = 0.02;

detect-rounded-corners = true;
corner-radius = 6;

blur: {
  method = "dual_kawase";
  strength = 8;
};

animations = ({
  triggers = [ "open", "close", "show", "hide" ];
  preset = "appear";
  scale = 0.8;
  duration = 0.4;
})

rules: (
  {
    match = "window_type = 'normal'";
    dim = 0.3;
  },
  {
    match = "focused || group_focused";
    opacity = 1;
    dim = 0;
    shadow = true;
    full-shadow = true;
  },
  {
    match = "window_type = 'tooltip'";
    opacity = 1;
    focus = true;
    shadow = true;
    full-shadow = true;
  },
  {
    match = "window_type = 'dock'";
    shadow = true;
    full-shadow = true;
    clip-shadow-above = false;
  },
  {
    match = "window_type = 'dnd'";
    shadow = false;
  },
  {
    match = "name = 'Notification'";
    full-shadow  = true;
  },
  {
    match = "name = 'popup_menu' || "
            "name = 'dropdown_menu'";
    opacity = 1;
  },
  {
    match = "class_g = '[mM]ixxx' || "
            "class_g = '[dD]arktable' || "
            "window_type = 'dock' || "
            "window_type = 'menu' || "
            "window_type = 'dropdown_menu' || "
            "window_type = 'popup_menu' || "
            "window_type = 'tooltip'";
    round-borders = false;
  },
  {
    match = "class_g = 'Gimp' || "
            "class_g = 'Rofi' || "
            "window_type = 'Desktop'";
    focus = false;
  },
  {
    match = "class_g = 'scribus'";
    focus = false;
    round-borders = false;
    shadow = false;
  }
)
```
</details>

### Steps of reproduction
1. run picom with defined config file
2. open a terminal window (Wezterm) and a browser window
3. switch to the terminal window

### Expected behavior
The terminal is opaque with the defined opacity and shows the wallpaper as a background.

### Current Behavior
The terminal is opaque with the defined opacity but shows the underlying browser window as background.

**Comment by yshui** [comment]
Fixed!

**Comment by wimstefan** [comment]
Wow that was fast 😃
Thanks a lot for this fix!
