### ISSUE TITLE
Rounded corners do not disappear when in fullscreen when having rules in the config.

### ISSUE THREAD

**Issue by p4rfait** [yshui/compton#1323]
### Platform
Artix Linux

### Environment
dwm (no patches)

### picom version
Bug happens for: `vgit-bc455e` (https://github.com/yshui/picom/commit/bc455e866e253c822324244df1c2aeb5c7f8c620)
Bug present for the first time for: `vgit-0a6af` (https://github.com/yshui/picom/commit/0a6af58bb83580e63f4dd1a13d6bd790efac2d0f)
Bug free for: `vgit-882f2` (https://github.com/yshui/picom/commit/882f21b34aa7e9a402564300920bf814f4a8a2cb)

<details>
<summary>Diagnostics</summary>

**Version:** vgit-0a6af

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No

* Config file specified: /home/p4rfait/.config/picom/picom.problem.conf
* Config file used: /home/p4rfait/.config/picom/picom.problem.conf

### Drivers (inaccurate):

modesetting
[ 08/22/2024 10:21:10.660 egl_init WARN ] The egl backend is still experimental, use with care.

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) Xe Graphics (TGL GT2)

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
* Accelerated: 1
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
backend = "glx"

corner-radius = 90

rules: ({
  # It is not necessary to set any rule to reproduce this bug, 
  # simply having braces inside parentheses is enough to produce it.
  # `rules:()`  does not reproduce the bug
})
```
</details>

### Steps of reproduction
1.  Start picom having “rules({})” set in the configuration file.
2. Open anything in fullscreen, like a video or firefox.

### Expected behavior
No rounded corners on fullscreen 

### Current Behavior
Rounded corners remains in fullscreen 

### Other details
![image](https://github.com/user-attachments/assets/1edf576b-c5f7-4670-9ef3-7bd5b800646d)
Firefox in fullscreen with picom vgit-acef3

**Comment by yshui** [comment]
errr, i don't think we claimed anywhere fullscreened window won't have rounded corners?

**Comment by p4rfait** [comment]
I know, but I don't see the relation between having or not having rounded corners in full screen with simply having rules in the config file. If this is expected behavior, how can i have rules and no rounded corners in fullscreen at the same time?

**Comment by yshui** [comment]
Ah, so what you are saying is if you have any rules then fullscreen windows will lose rounded corners?

**Comment by p4rfait** [comment]
Yep, sorry if I didn't explain myself well. 

Edit: No, having rules in the config file causes the corners to remain when in fullscreen, when there are no rules in the config file the rounded corners disappear in full screen (which I understand is the expected behavior, or at least that's how it behaved in previous versions) ...srry english is hard T-T

**Comment by p4rfait** [comment]
https://github.com/user-attachments/assets/f69dab59-ee29-4de5-9b14-4b6208fbb9d8

**Comment by yshui** [comment]
i see what's going on. the old system does disable rounded corners for fullscreen windows automatically, i did miss that.

but after some thought i think we don't want to replicate this in the new system, instead we will give user the full control. i will update the documentation to reflect that.

if you want to have the old behavior, you can use this rule:

```
{
    match = "fullscreen";
    corner-radius = 0;
}
```

**Comment by Abdel-2020** [comment]
Thank you so much this was a great help for a similar issue I was having!
