### ISSUE TITLE
Only focused window have opacity = 1

### ISSUE THREAD

**Issue by servimo** [yshui/compton#1324]
I updated my picom to latest git.  Now all windows have "opacity = 1".  How to make the inative windows have an opacity of 0.90? I tried using the "rules" but didn't quite understand what I have to do. Is there an inative exclude?
If possible can I have a complete example "rule" for this?

**Comment by yshui** [comment]
inactive opacity should still work as long as you don't have `rules` in your config.

**Comment by servimo** [comment]
> inactive opacity should still work as long as you don't have `rules` in your config.

I want to use rules. I disable all the lines that picom messaged in the console. It's not available yet? I do a complete clean up in my config.

**Comment by yshui** [comment]
you can have a rule without `match`, so it will match all windows.

> match
>
> &nbsp;&nbsp;&nbsp;&nbsp;The condition string to match windows with. See the [FORMAT OF CONDITIONS](https://picom.app/#_format_of_conditions) section below for the syntax of condition strings. **If not specified, the rule will always match.**

or you can match all none focused windows with `!focused && !group_focused`.

these are all documented in man page: https://picom.app/#_migrating_old_rules

**Comment by servimo** [comment]
> !focused && !group_focused

This do the trick. Thanks!
