### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by MaayerAli** [yshui/compton#1325]
I use linux mint and I tried installing picom i did the installion steps and I also git cloned the repo. I pasted ninja -C build but it did this in respose: ninja: error: loading 'build.ninja': No such file or directory
![Screenshot_2024-08-24_17-34-18](https://github.com/user-attachments/assets/a224076e-e926-4c53-b315-74a0402c368a)
Using xfce4-terminal.

**Comment by MaayerAli** [comment]
My hardware is this:
OS:Linux Mint 22
Kernel: 6.8.0-40-generic
Window manager: i3wm
Terminal: xfce4-terminal
Laptop: Surface Pro 3
CPU: Intel i5-4300U
Memory: 7846MiB

**Comment by absolutelynothelix** [comment]
apparently you missed the `meson setup build` step.

**Comment by MaayerAli** [comment]
No I did the meson build step

**Comment by MaayerAli** [comment]
It still had this issue

**Comment by absolutelynothelix** [comment]
post the output of `meson setup build --wipe`.

**Comment by MaayerAli** [comment]
![Uploading Screenshot_2024-08-24_17-49-17.png…]()

**Comment by MaayerAli** [comment]
Sorry my bad turns out I did not have cmake installed

**Comment by MaayerAli** [comment]
I tried it again with cmake and it worked

**Comment by MaayerAli** [comment]
Here is the screenshot you wanted btw
![Uploading Screenshot_2024-08-24_17-49-17.png…]()

**Comment by absolutelynothelix** [comment]
closing as resolved.
