### ISSUE TITLE
Build instructions for man pages

### ISSUE THREAD

**Issue by ryanthomas-org** [yshui/compton#1329]
Just successfully built picom-12-rc3 on Linux Mint 21,1 5.15.0-91-generic

Can you please provide specific instructions for building the man pages? "No manual entry for picom" 

1. The instructions in the main readme say "to build the documents, you need asciidoc" but it looks like "asciidoctor" is needed and this seems to be a different program. 

2. I have now installed asciidoctor but that does not install the man pages automatically. It may be super obvious to people who work with ninja often but it's not spelled out anywhere here. I see the *.adoc files in the man directory but can anyone provide precise step-by-step instructions for how to convert them properly? 

Thanks

**Comment by yshui** [comment]
oh right, i need to update readme to say asciidoctor.

to enable man page, pass `-Dwith_docs=true` to meson

**Comment by ryanthomas-org** [comment]
That did the trick, thanks a bunch
