### ISSUE TITLE
Lag with git version, 11.2 fine

### ISSUE THREAD

**Issue by Cheesemassacre** [yshui/compton#1330]
### Platform
Arch Linux

### GPU, drivers, and screen setup
13th gen igpu, latest updates

### Environment
dwm

### picom version
picom-git from aur, latest

### Config
Only things changed:
 blur-strength = 1.5
 blur-background = true

### Problem
I'm sometimes getting lag while switching workspaces, terminal is slower. For example ctrl + c in terminal is laggy, vim is slower, neofetch is taking longer to show. Very weird. GUI apps are fine I think. It's random. 11.2 release version is fine. No lag or slowdowns. This has been happening for some time now, at least since June.

**Comment by emanuelamaral** [comment]
Same here: picom (vgit-89c2c). My fading its very lagged too

**Comment by yshui** [comment]
It's hard for me to visualize exactly what you mean, do you have a recording?

And if you are sure 11.2 is fine, can you do a bisect to see at which point did it start happening?

**Comment by yshui** [comment]
probably same problem as #1345, try the `fix-1345` branch

**Comment by Cheesemassacre** [comment]
> probably same problem as #1345, try the `fix-1345` branch

It now works fine
