### ISSUE TITLE
Non-functional _NET_WM_WINDOW_TYPE_DESKTOP when configuring shadows via the rules section

### ISSUE THREAD

**Issue by raven2cz** [yshui/compton#1331]
According to the documentation:
```
-c, --shadow
    Enables client-side shadows on windows. Note that desktop windows (windows with _NET_WM_WINDOW_TYPE_DESKTOP) never receive shadows, unless explicitly requested using the wintypes option.
```

This applies to the standard older configuration. However, if you use a new configuration with shadow, defined via `rules`, then `_NET_WM_WINDOW_TYPE_DESKTOP` no longer applies and everything gets shadows, which is incorrect.

I have to add rule:
```
 {
   match = "_NET_WM_WINDOW_TYPE = '_NET_WM_WINDOW_TYPE_DESKTOP'";
   shadow = false;
 },
```

**Comment by Monsterovich** [comment]
How about `match = "window_type = 'desktop'"`?
