### ISSUE TITLE
Single transparent window - question 

### ISSUE THREAD

**Issue by alexzk1** [yshui/compton#1332]
Is it possible to use `--unredir-if-possible` in such way so it "unredirs" for exact 1 window ?

My scenario is: I have full screen game which I want to "unredir". I have other software which draws window as overlay - I want this window to remain transparent.

When I add this extra sw to the exclusion list it does nothing. Extra software does the call as ` XSetClassHint(display, w, classHint);` and string used to build `classHint` is passed to filter as
```
unredir-if-possible-exclude = [
"class_i = 'edmc_linux_overlay_class'",
"class_g = 'edmc_linux_overlay_class'",
]

```

**Comment by Monsterovich** [comment]
That's how I do it:

```
unredir-if-possible-exclude = [
    "_NET_WM_STATE@:a != '_NET_WM_STATE_FULLSCREEN' && (name *= 'gl-gsync-demo' || name *= 'flameshot') || class_g ?= 'xviewer'",
    "name *= 'Stellaris'",
    "name *= 'mpv'"
];
```

**Comment by alexzk1** [comment]
> That's how I do it:
> 
> ```
> unredir-if-possible-exclude = [
>     "_NET_WM_STATE@:a != '_NET_WM_STATE_FULLSCREEN' && (name *= 'gl-gsync-demo' || name *= 'flameshot') || class_g ?= 'xviewer'",
>     "name *= 'Stellaris'",
>     "name *= 'mpv'"
> ];
> ```

Can you explain or give a link for the syntax of those conditions ?

**Comment by Monsterovich** [comment]
@alexzk1 

> Can you explain or give a link for the syntax of those conditions ?

I reread your post. I think that if you want to have a transparent window on top of a full screen window, then unredir will be useless in that regard. The settings above make it so that if there is only one full screen window, compositing is automatically disabled.

For example, when I do alt+tab or show an notification, compositing is enabled and therefore transparency on overlay windows works.

**Comment by alexzk1** [comment]
> For example, when I do alt+tab or show an notification, compositing is enabled and therefore transparency on overlay windows works.

I write app with overlay, so if I will do overlay full screen too somehow, this will work ?
How picom do detect fullscreen ? I can try to play with overlay window.

**Comment by yshui** [comment]
> My scenario is: I have full screen game which I want to "unredir". I have other software which draws window as overlay - I want this window to remain transparent.

that's not how it works. unredir is all or nothing. nothing can be transparent if screen is unredirected
