### ISSUE TITLE
Latest 12.1 release fails to build on 32bit (i686 arch)

### ISSUE THREAD

**Issue by david-geiger** [yshui/compton#1346]
Hi,

On Mageia Cauldron latest release (12.1) fails to build now on i686 arch with the following build issue:

> In file included from ../src/transition/script.h:5,
                 from ../src/wm/win.h:21,
                 from ../src/opengl.h:10,
                 from ../src/vsync.c:11:
../src/transition/script.h:48:1: error: static assertion failed: "double/unsigned has unexpected alignment"
   48 | static_assert(alignof(double) > alignof(unsigned), "double/unsigned has unexpected "
      | ^~~~~~~~~~~~~
In file included from ../src/wm/wm.h:15,
                 from ../src/wm/win.h:24:
../src/wm/wm.h:77:1: error: static assertion failed: "wm_treeid alignment is not 8 bytes"
   77 | static_assert(alignof(wm_treeid) == 8, "wm_treeid alignment is not 8 bytes");

Attached full build log:
[build.i686.0.20241001044804.log](https://github.com/user-attachments/files/17212396/build.i686.0.20241001044804.log)

**Comment by yshui** [comment]
Pushed a fix, I don't have a 32bit system for testing so let me know if you still have this problem.

**Comment by david-geiger** [comment]
You fixed one of the two build issue, now there is still this one:

`In file included from ../src/transition/script.h:5,
                 from ../src/wm/win.h:21,
                 from ../src/picom.h:24,
                 from ../src/diagnostic.c:13:
../src/transition/script.h:48:1: error: static assertion failed: "double/unsigned has unexpected alignment"
   48 | static_assert(alignof(double) > alignof(unsigned), "double/unsigned has unexpected "`

**Comment by yshui** [comment]
ok i've gotten rid of that too.

honestly i don't know if picom even works on 32bit anymore.
