### ISSUE TITLE
v12.1 freezes desktop and then crashes 

### ISSUE THREAD

**Issue by Celibistrial** [yshui/compton#1347]
### Platform
NixOS
### GPU, drivers, and screen setup
NVIDIA 560.35.03
❯ glxinfo -b
33
### Environment
i3wm

### picom version
❯ picom --version
v12.1
<details>
<summary>Diagnostics</summary>
❯ picom --diagnostics
[ 02/10/24 19:04:36.186 c2_parse_target WARN ] Type specifier is deprecated. Type "c" specified on target "_GTK_FRAME_EXTENTS" will be ignored, you can remove it.
[ 02/10/24 19:04:36.186 c2_parse_target WARN ] Type specifier is deprecated. Type "c" specified on target "_GTK_FRAME_EXTENTS" will be ignored, you can remove it.
**Version:** v12.1

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No

* Config file specified: None
* Config file used: /home/gaurav/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA, modesetting
[ 02/10/24 19:04:36.225 egl_init WARN ] The egl backend is still experimental, use with care.

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
[ 02/10/24 19:04:36.389 glx_init ERROR ] Failed to enable vsync.

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Mesa
* GL renderer: llvmpipe (LLVM 18.1.8, 256 bits)
* Accelerated: 0

(You are using a software renderer. Unless you are doing this
intentionally, this means you don't have a graphics driver
properly installed. Performance will suffer. Please fix this
before reporting your issue.)
</details>

**Comment by yshui** [comment]
do you have a stack trace for the crash? any logs?

**Comment by yshui** [comment]
Oh, never mind, you are using llvmpipe:

> (You are using a software renderer. Unless you are doing this
intentionally, this means you don't have a graphics driver
properly installed. Performance will suffer. Please fix this
before reporting your issue.)

**Comment by Celibistrial** [comment]
Only after updating my system did it start using software renderer, not sure what the cause could be.

I tried
1. downgraded only gpu drivers with v12.1 of picom 
2. downgrade only picom
3. downgrade picom and gpu drivers
None of the above worked, could it be some other dependency of picom?
