### ISSUE TITLE
Tearing problem with the modesetting driver on Intel only fixable through deprecated options

### ISSUE THREAD

**Issue by ryshglene** [yshui/compton#135]
Today, I tried building and testing the latest version of Compton from this repo in order to try out the new 'experimental' backends. Unfortunately, I immediately ran into two issues based on my configuration, so my testing became less focused on that, and more on these issues:

    [ 03/17/2019 15:33:29.814 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "opengl-swc" is interpreted as "true" for compatibility, but this will stop working soon
    [ 03/17/2019 15:33:29.858 swopti_init WARN ] --sw-opti is going to be deprecated. If you get real benefits from using this option, please open an issue to let us know.

Apparently, the two options I use `vsync` and `sw-opti` are going to be removed. So I figured now I'll have to either stop using those options, or stick to an older (and likely soon, 'outdated') version of compton.

Of course, I did the former first. However, that only resulted into why I used those options in the first place: it was badly tearing. I'm using the Xorg `modesetting` driver and both the `glx` and `xrender` backend had tearing. I also tried using the experimental backends, but with the `glx` backend, compton crashes as soon as I try to do anything complicated with my windows. The `xrender` backend was a bit more stable but the tearing persisted.

As a result, I thought I had to resort to using the old Intel Xorg driver. Without using any of the custom driver configurations, I then tested my compton configuration with the two backends. It gave me very similar results, although the tearing was less intrusive IMO. I also tested the experimental backends, and surprisingly enough, one of them was actually able to remove tearing the completely (in the same way the two previously mentioned options did). It was the `glx` backend and no longer did it exhibit any of the crashing problems I mentioned earlier with the `modesetting` driver. The `xrender` backend was a completely different story though, showing the same tearing problems as it did on the non-experimental backend.

I could have ended my testing there as I had found that the experimental `glx` backend completely removed the tearing, but I thought it might be useful to test compton with the Intel driver's `TearFree` option, since so many people who don't use compositors seem to mention it. 

Here, I had much better results than with the previous two driver configurations. I didn't experience any tearing with both the `glx` and `xrender` backends, though I think it was because the driver was already handling the tearing for compton. Of course I also had to try the experimental backends. They gave me slightly interesting results, with the experimental `glx` backend working very similar to the non-experimental one, but the experimental `xrender` backend giving me varying results. The experimental `xrender` backend shows tearing even with the `TearFree` option, but the non-experimental one seems to handle it just fine. As I wrote this post, it seems that the experimental `xrender` backend has removed the tearing problem, but further testing shows that this isn't a reproducible behavior. So I'm very confused.

I'm sorry if this is all very confusing as well, as I'm not really a good writer and this is my first time posting an issue on GitHub. That said, I hope this short table might help illustrate some of my findings:

    [Xorg Driver]       [Backend]               [Tearing]
    modesetting         glx                     yes
    modesetting         xrender                 yes
    modesetting         glx (experimental)      yes
    modesetting         xrender (experimental)  yes
    intel               glx                     yes
    intel               xrender                 yes
    intel               glx (experimental)      no
    intel               xrender (experimental)  yes
    intel with TearFree glx                     no
    intel with TearFree xrender                 no
    intel with TearFree glx (experimental)      no
    intel with TearFree xrender (experimental)  yes

I think should mention that the hardware I used for this testing was an old ThinkPad with the Intel i5-2520M processor and an Intel HD 3000 GPU. It's running bspwm on Arch Linux with mesa 18.3.4 and Xorg 1.20.4. The Intel Xorg driver I tested with is 2.99.917+863+g6afed33b. Other than the options I mentioned (`TearFree`), I wasn't using any other graphics driver settings. The compton version is v6-rc1-10-g0a32c81, whereas the last "working" version is 5.1 (if that matters). The compton configuration file I used to test is the following:

    backend = "glx";
    glx-no-stencil = true;
    glx-copy-from-front = false;
    #glx-swap-method = "undefined";
    
    # Shadows
    shadow = true;
    shadow-radius = 4;
    shadow-offset-x = -4;
    shadow-offset-y = -4;
    shadow-opacity = 0.4;
    shadow-exclude = [
        "! name~=''",
        "class_g = 'Tor Browser' && argb",
        "_GTK_FRAME_EXTENTS@:c",
        "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
    ];
    shadow-ignore-shaped = false;
    
    # Opacity
    inactive-opacity = 1;
    active-opacity = 1;
    frame-opacity = 1;
    inactive-opacity-override = false;
    blur-background-fixed = false;
    blur-background-exclude = [
        "window_type = 'dock'",
        "window_type = 'desktop'"
    ];
    
    # Fading
    #fading = true;
    fade-delta = 4;
    fade-in-step = 0.03;
    fade-out-step = 0.03;
    no-fading-openclose = true;
    fade-exclude = [ ];
    
    # Other
    mark-wmwin-focused = true;
    mark-ovredir-focused = true;
    use-ewmh-active-win = true;
    detect-rounded-corners = true;
    detect-client-opacity = true;
    refresh-rate = 0;
    #vsync = "opengl-swc";
    dbe = false;
    #sw-opti = true;
    unredir-if-possible = false;
    focus-exclude = [ ];
    detect-transient = true;
    detect-client-leader = true;
    wintypes:
    {
        tooltip =
        {
            fade = true;
            shadow = false;
            opacity = 0.85;
            focus = true;
        };
    };
    xrender-sync-fence = true;

For the xrender tests, I had to pass `--backend xrender`, while the experimental backends needed `--experimental-backends`. Also, if you need a copy of the `glxinfo` output, it's posted [here](https://pastebin.com/d15pXwLK). 

I know this issue sounds like it's mostly been solved because `intel` with the `TearFree` option apparently fixes tearing already, but I'm still posting it here in order to report the problems I encountered with the modesetting driver. Do we really have to start moving back to the old Intel driver if we want to get rid of the tearing problem? I'm not sure if this is the best move going forward considering a lot of distros recommend using to the new modesetting driver instead. So I implore you guys to reconsider deprecating those options. If not, at least look into the issues I mentioned.

Thanks again for you work! :)

**Comment by yshui** [comment]
So `vsync` is not going to be removed. It's just going to take boolean from now on. So, `vsync = true` to enable vsync, false to disable.

**Comment by ryshglene** [comment]
Ah, I had completely forgotten that commenting `vsync` meant disabling it entirely. So that's why it was tearing badly across so many configurations. Can confirm uncommmenting `vsync` and setting it to `true` makes all warnings go away as well as fixes my issue.

**Comment by yshui** [comment]
@ryshglene Can this be closed then?

**Comment by ryshglene** [comment]
Yes 👍

**Comment by vn-ki** [comment]
@ryshglene What was your solution? This is happening to me.

With vsync=on, I get tearing.
With sw-opti=on, I get tearing.

With vsync=off, tearing is much more pronounced.

With backend="xr_glx_hybrid", tearing is a bit less, but is still annoying.
