### ISSUE TITLE
picom overriding .desktop file when updating

### ISSUE THREAD

**Issue by mardevour** [yshui/compton#1362]
Hi! first of all i wanted to thank everyone for the work, really love picom!

I have this problem and i'm really not sure if it's a bug, but anyway, couldn't find anything about this.

So I use picom with xfce and the way it launches picom is with a `picom.desktop` on `/etc/xdg/autostart/`. This file has: `Exec=picom`. Now because of the way I have my picom's config on my setup I actually need to launch it with `--backend glx`, so i did that, edited the .desktop file to have `Exec=picom --backend glx`. The problem is that every time picom updates it changes it back to `Exec=picom`, so after that, at the next boot (or login) my system is very laggy and some of picom's effects are broken (i.e. rounded borders), and every time I have to manually change it back and restart the session.

I probably could find another way to launch it but I think this shouldn't happen.

**Comment by yshui** [comment]
this depends on how your distros package manager install files, not something we have control over. 

you need to report this to your distro.

**Comment by yshui** [comment]
and, you know, picom does support config files... you can put `backend=` there.

**Comment by mardevour** [comment]
of course 😅 sorry for bothering you
