### ISSUE TITLE
Cannot compile, FAILED: src/picom.p/picom.c.o 

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [yshui/compton#1363]
### Platform

Ubuntu Desktop 20.04 amd64

### GPU, drivers, and screen setup

GPU: NVidia RTX 3070
Driver: 560.35.03-0ubuntu0~gpu20.04.4
glxinfo -B:
```name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 12282 MB
    Total available memory: 12282 MB
    Currently available dedicated video memory: 11467 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 560.35.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 560.35.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 560.35.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```    

### Environment

Plasma  + i3wm

### picom version

can't find version with ```picom --version``` since i can't compile I am trying to compile the latest commit

<details>
<summary>Diagnostics</summary>

can't run `picom --diagnostics`  since picom won't compile

Build log:    
https://pastebin.com/QUeZRXes     
</details>

### Configuration:
<details>

    <summary>Configuration file</summary>

no configuration

</details>

### Steps of reproduction

1. $ git clone https://github.com/yshui/picom.git
2. $ meson setup --buildtype=release build
3. $ ninja -C build
4. Error

### Expected behavior

picom finish compiling

### Current Behavior

Build log:
https://pastebin.com/QUeZRXes

**Comment by absolutelynothelix** [comment]
`ninja -C | grep -i error`

**Comment by yshui** [comment]
your gcc version is too old
