### ISSUE TITLE
Stuttery scrolling with NVIDIA and GLX backend after v12.3 (regression)

### ISSUE THREAD

**Issue by bubbleguuum** [yshui/compton#1368]
Sorry to be again the bringer of bad NVIDIA news :/

After you fixed #1265, I compiled latest `next` branch and... scrolling is noticeably stuttery, while it was silk smooth with v12.3 (config: GLX backend with vsync enabled). That issue is of course not caused by the #1265 fix.

Digging into it, I would not be surprised it is caused by this large commit a54adb62dad8c7c7466b082c492d5e62a5175881.

I thought this could be the removal of `libdrm` but that's not it, I tested that v12.3 compiled with or without it is identically smooth.

**Comment by yshui** [comment]
were you using the legacy backends?

**Comment by bubbleguuum** [comment]
Nope, I use the same config for both v12.3 (no issue) and `next` (issue):

```
backend = "glx"
vsync = true
```

**Comment by yshui** [comment]
hmm, if that commit has caused any problems i am having a hard time to see why it would only affect nvidia :thinking: because the rendering code path should be unchanged.

**Comment by bubbleguuum** [comment]
It's very well possible it is not NVIDIA specific. Let me try picom compiled before and after that commit to check if it is the cause.

**Comment by bubbleguuum** [comment]
Looks like it is a latter commit after all. Will have to git bisect to find it but I'll have to learn how to use it first.

**Comment by bubbleguuum** [comment]
It seems to be caused by 8065c1fabed26c3ef1783d4beda75912a605909c

**Comment by yshui** [comment]
ah, yep, that commit is wrong. that probably also explains why picom is using a bit more cpu over here. thanks for catching this.
