### ISSUE TITLE
Fade is not applied if option is set to false but in rules is true

### ISSUE THREAD

**Issue by gh0stzk** [yshui/compton#1369]
Hello, i am on picom v12.3 (/startdir/picom revision 1b27f3e)

My question is about the behavior of the fade option. I set shadows and fade to false but i made a rule for normal wintype windows that set shadows and fade to true.

Shadows works as expected is applied only to normal wintype windows but the fade isnt.

Is this how it should work? or there is something wrong...?

My picom.conf:

```ini
## ----- Shadows ----- ##

shadow = false;

shadow-radius = 7;
#shadow-opacity = .6
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-color = "#000000"

## ----- Fading ----- ##

fading = false;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5
no-fading-openclose = true
no-fading-destroyed-argb = false

## ----- Transparency ----- ##

frame-opacity = 1.0;

# inactive-dim-fixed = true

## ----- Corners ----- ##

corner-radius = 6

#################################
#       General Settings        #
#################################

# Available backends "xrender" "glx" "egl"
backend = "glx"

dithered-present = false;
vsync = true;

detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;

use-damage = false;
# xrender-sync-fence = false
# transparent-clipping = false

@include "picom-rules.conf"
```

My picom-rules.conf

```ini
rules: (

{
	match = "window_type = 'normal'";
	fade = true;
	shadow = true;
},

)
```

Im on arch linux, tested with glx and xrender backend.

**Comment by yshui** [comment]
`fading` is a global switch, setting it to false is not setting the default fading value - it will disable fading across the board. if you want to disable fading by default, you can use a default rule (one without `match`) to set fade to false.

**Comment by gh0stzk** [comment]
Ohh ok!! Thanks!! i will try.
