### ISSUE TITLE
Huge "invisible" leak of `anon_inode:i915.gem`

### ISSUE THREAD

**Issue by Hi-Angel** [yshui/compton#1378]
### Platform

Archlinux

### GPU, drivers, and screen setup

* Single screen, laptop.
* Mesa: `24.2.4`
* Xorg driver: `modesetting`

GPUs:

* Primary: `CometLake-H GT2`
  * driver iris
* Discrete, unused in context of the report: `NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile]`
  * driver nouveau

*  `glxinfo -B`
  ```
  name of display: :0
  display: :0  screen: 0
  direct rendering: Yes
  Extended renderer info (GLX_MESA_query_renderer):
      Vendor: Intel (0x8086)
      Device: Mesa Intel(R) UHD Graphics (CML GT2) (0x9bc4)
      Version: 24.2.4
      Accelerated: yes
      Video memory: 7822MB
      Unified memory: yes
      Preferred profile: core (0x1)
      Max core profile version: 4.6
      Max compat profile version: 4.6
      Max GLES1 profile version: 1.1
      Max GLES[23] profile version: 3.2
  OpenGL vendor string: Intel
  OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)
  OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.2.4-arch1.1
  OpenGL core profile shading language version string: 4.60
  OpenGL core profile context flags: (none)
  OpenGL core profile profile mask: core profile

  OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.4-arch1.1
  OpenGL shading language version string: 4.60
  OpenGL context flags: (none)
  OpenGL profile mask: compatibility profile

  OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.2.4-arch1.1
  OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
  ```

### Environment

Plasma + i3wm

### picom version

`picom --version`: `v12.3 (/startdir/picom revision 1b27f3e)`

<details>
<summary>Diagnostics</summary>

```
[ 01.11.2024 00:34:20.498 parse_config_libconfig WARN ] The refresh-rate option has been deprecated. Please remove it from your configuration file. If you encounter any problems without this feature, please feel free to open a bug report
**Version:** v12.3 (/startdir/picom revision 1b27f3e)

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file specified: None
* Config file used: /home/constantine/.config/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
* Accelerated: 1
[ 01.11.2024 00:34:20.631 egl_init WARN ] The egl backend is still experimental, use with care.

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
```
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-red = 0.0;
shadow-green = 0.0;
shadow-blue = 255;
shadow-exclude = [ "name = 'Notification'", "class_g = 'Notify-osd'"];
shadow-ignore-shaped = false;
inactive-opacity = 0.85;
inactive-opacity-override = false;
blur-background-exclude = [ "window_type = 'dock'", "window_type = 'desktop'" ];
opacity-rule = [ "100:focused" ];
fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];
backend = "xrender"
mark-wmwin-focused = true;
detect-rounded-corners = true;
detect-client-opacity = false;
refresh-rate = 0;
vsync = true;
dbe = false;
detect-transient = true;
detect-client-leader = false;
invert-color-include = [ ];
glx-no-rebind-pixmap = true;
use-damage = true
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.80; focus = true; };
  dnd     = { fade = true; shadow = false; opacity = 0.80; focus = true; };
  dock    = { fade = true; shadow = false; opacity = 1; focus = true; };
  popup_menu    = { fade = true; shadow = true; opacity = 1; focus = true; };
  dropdown_menu = { fade = true; shadow = true; opacity = 0.80; focus = true; };
};
```
</details>

### Details

This was first discussed on the [linux-mm kernel ML](https://lore.kernel.org/linux-mm/CAJD7tka9Vh7+Q38Q_rm-6TnOB73QU5RD-6OX4ZpxpkQW1NdHRQ@mail.gmail.com/T/#u).

Long story short: I found that in runtime Xorg steadily increases SWAP usage. There's a catch though: that's basically invisible unless you know exactly what to look for! Neither `smem` nor `/proc/$(pgrep -x Xorg)/smaps` would show you increase in Xorg memory usage. That's because those leaking "inodes" are accounted as `shmem`, and for some reason `shmem` is not being accounted in "process swap usage" counters. The leak however is so huge that at some point it triggers OOM.

Before writing this report, on my system:

* Amount of Xorg inodes:
  ```
  λ sudo grep -c 'anon_inode:i915.gem' /proc/$(pgrep Xorg)/smaps
  687
  ```
* Memory taken by them is 1.8G:
  ```
  λ sudo grep -A1 'anon_inode:i915.gem' /proc/$(pgrep Xorg)/smaps | grep Size: | awk '{total += $2} END {print total " kB"}'
  1855996 kB
  ```

I almost reported that to Xorg, but then I realized that these `inodes` might be related to clients opened. And indeed, `killall picom` dropped amount `687` → `131`.

So ultimately, it's Picom not freeing some resources.

### Steps of reproduction

I don't have anything specific, in my case just typical usage of the system leads to steady increase of the `sudo grep -c 'anon_inode:i915.gem' /proc/$(pgrep Xorg)/smaps` count.

**Comment by absolutelynothelix** [comment]
try picom built from the latest commit in the `next` branch.

**Comment by Hi-Angel** [comment]
I think it fixed the problem, thanks! I've used for ½ a day latest `picom`, and so far saw no increase in Xorg inodes amount, nor SWAP usage.

**Comment by Hi-Angel** [comment]
@absolutelynothelix that commit should go to stable/12, right?

**Comment by absolutelynothelix** [comment]
it's already there.

btw, this leak isn't really invisible. if you tracked a memory leak down to the x server, use `xrestop` to find the responsible client, it's pretty much visible there.

**Comment by Hi-Angel** [comment]
> btw, this leak isn't really invisible. if you tracked a memory leak down to the x server, use `xrestop` to find the responsible client, it's pretty much visible there.

Tracking it down first is the problem 😉 It is "invisible" *(note the quotes)* because you won't find it through the usual means of `free` + "whatever utility that shows swap usage per process". You'd have to notice first that there is a gap between what `free` reports and the amounts of swap per process.

**Comment by absolutelynothelix** [comment]
this particular leak can be tracked down to the x server using gpu vendor's tools. an example for intel using `intel_gpu_top`:
![image](https://github.com/user-attachments/assets/0d076b3d-3d73-4aa2-8171-68b17eda769c)

for nvidia's proprietary driver it'd be `nvidia-smi`. not sure how universal this way is though.
