### ISSUE TITLE
Issue with the ability to exclude animation for specific window types

### ISSUE THREAD

**Issue by denysok** [yshui/compton#1380]
Hello!

I would like to inquire whether it is possible in picom to exclude animation for specific types of windows, such as **menu**, **popup_menu**, and **dropdown_menu**. Currently, animations are applied to all windows, and I would like the ability to set animations separately for these window types or completely disable them.

This feature would be very helpful for improving the user experience, especially when using context menus and pop-up windows, where animation may be unnecessary or cause delays.

**Thank you for your time and for creating this wonderful project!**

**Comment by Fabrice-Bernes** [comment]
The following example makes windows slide as they change positions, fade-in as they are created or un-minimized, and fly-out into the bottom of the screen when they are closed or minimized:
```
animations = (
    {
        triggers = [ "geometry" ];
        preset = "geometry-change";
        duration = 0.2;
    },
    {
        triggers = [ "open", "show" ];
        preset = "appear";
        scale = 0.5;
        duration = 0.5;
    },
    {
        triggers = [ "close", "hide" ];
        preset = "fly-out";
        direction = "down";
        duration = 0.1;
    }
)
```
If I want notification to not have any kind of animation, I would add animations for them, with duration set to zero:
```
rules: ({
  match = "window_type = 'notification'";
  animations = (
    {
        triggers = [ "open", "show" ];
        duration = 0;
    },
    {
        triggers = [ "close", "hide" ];
        duration = 0;
    }
  );
})
```
Is this what you were looking for? I got it from the `WINDOW RULES` section in picom's manpage

**Comment by denysok** [comment]
> The following example makes windows slide as they change positions, fade-in as they are created or un-minimized, and fly-out into the bottom of the screen when they are closed or minimized:
> 
> ```
> animations = (
>     {
>         triggers = [ "geometry" ];
>         preset = "geometry-change";
>         duration = 0.2;
>     },
>     {
>         triggers = [ "open", "show" ];
>         preset = "appear";
>         scale = 0.5;
>         duration = 0.5;
>     },
>     {
>         triggers = [ "close", "hide" ];
>         preset = "fly-out";
>         direction = "down";
>         duration = 0.1;
>     }
> )
> ```
> 
> If I want notification to not have any kind of animation, I would add animations for them, with duration set to zero:
> 
> ```
> rules: ({
>   match = "window_type = 'notification'";
>   animations = (
>     {
>         triggers = [ "open", "show" ];
>         duration = 0;
>     },
>     {
>         triggers = [ "close", "hide" ];
>         duration = 0;
>     }
>   );
> })
> ```
> 
> Is this what you were looking for? I got it from the `WINDOW RULES` section in picom's manpage

You're a super hero! Thank you a lot 🙏
