### ISSUE TITLE
v 12.4 wrong version output

### ISSUE THREAD

**Issue by samarulmeu** [yshui/compton#1387]
As the title suggest there is a wrong output of `picom --version` in v. 12.4

**Comment by yshui** [comment]
thanks for reporting!

fixed in ab6ca6c1e41a7346a8bdaf76a604e7c9fd, git tag updated as well.

**Comment by classabbyamp** [comment]
please don't recreate the same tag in the future, it breaks downstream builds like void: https://build.voidlinux.org/#/builders/8/builds/484

**Comment by yshui** [comment]
sorry about that 😖

**Comment by samarulmeu** [comment]
@yshui So I don't start another issue. 12.4 is still labeled as latest release although there is a new one 12.5. Thank you!
