### ISSUE TITLE
dbus: calls dbus_get_local_machine_id() which has bad error-handling

### ISSUE THREAD

**Issue by rrrrrrmb** [yshui/compton#1391]
Forwarding a bug report from Debian :

> picom calls dbus_get_local_machine_id(), which has no good mechanism
> for reporting an error, and therefore will spam warnings to standard error
> (and possibly crash) if the D-Bus machine ID has not been set up correctly.
> This function should be considered deprecated.
> 
> If it is necessary to call this function, please prefer to use
> dbus_try_get_local_machine_id(), which takes a DBusError parameter and
> therefore can be used to report errors in whatever way is considered to
> be most appropriate by the caller. This has been available in upstream
> stable releases since dbus 1.12.0 (2017).
> 
> It looks as though picom only calls dbus_get_local_machine_id()
> because it's implementing the o.fd.DBus.Peer interface. I suspect
> that this might not be necessary at all, because libdbus will usually
> implement the o.fd.DBus.Peer interface for you anyway, without needing
> application-specific code to be written for it. So maybe the code that
> implements o.fd.DBus.Peer.GetMachineId and ….Peer.Ping can just be deleted?

Ref : https://bugs.debian.org/1085336

**Comment by yshui** [comment]
thanks for bringing this to my attention :+1:
