### ISSUE TITLE
Removed option --vsync-aggressive

### ISSUE THREAD

**Issue by tim241** [yshui/compton#141]
### Platform
`Arch Linux`

### Environment
`Openbox`

### Compton version
```
> ~ compton --version
v6
> ~ 
```

### Steps of reproduction
My autostart:
```
# Shadows and vsync
compton --vsync-aggressive &
```

I updated today and noticed that it isn't working anymore, it seems like the option has been removed?

### Expected behavior
It should work like normally

### Current Behavior
it just shows
```
> ~ compton --vsync-aggressive
compton: unrecognized option '--vsync-aggressive'
```

Why was it removed? It used to work fine

I couldn't find anything about it in the github issues, so I opened this issue.

**Comment by tim241** [comment]
I discovered this: https://github.com/yshui/compton/pull/130

however, when I try `compton --vsync` I still have screen tearing,

I'm on nVidia and have `ForceFullCompositionPipeline` set, however I still need `--vsync-aggressive` to fix all the tearing.

**Comment by Ropid** [comment]
In `man compton`, there's an option `--xrender-sync-fence` mentioned:

> --xrender-sync-fence
> Use X Sync fence to sync clients' draw calls, to make sure all draw calls are finished before compton starts drawing. Needed on nvidia-drivers with GLX backend for some users.

What happens if you add it to your compton command line together with `--backend glx`?

**Comment by yshui** [comment]
@tim241 
1. What setup do you have? Graphic card? How many monitors? Refresh rate?
2. Are you using glx or xrender?
3. What kind of tearing are you talking about?

**Comment by tim241** [comment]
@yshui 

# Setup
```
1x GTX 1050 2gb with driver version 418.56
1x 1080p 60 hertz monitor
```

# Backend
the default one when using `--vsync`

# Tearing
General screen tearing when switching workspace/watching youtube videos that I normally dont have when using `--vsync-aggressive`

# Extra
my intent when making this issue was rather to notify you that it broke my setup, I distro hop at times and not all distros switched to your fork, I'd like to request for the option to be re-added since it worked fine?

**Comment by yshui** [comment]
If you don't specify the backend, you are using the xrender backend. And vsync _doesn't work_ with the xrender backend. It is pure _luck_ that it worked for you before, it could have been broken by anything.

If you want vsync, please use `--backend glx`.

**Comment by tim241** [comment]
Alright, that works, thanks :heart:

**Comment by tim241** [comment]
huh, after restarting X and rebooting, the tearing is back (yes, it's in the autostart)

**Comment by yshui** [comment]
@tim241 Put `backend = "glx"` in your config file.

**Comment by tim241** [comment]
I used `compton --vsync --backend glx` and I also tried `compton --backend glx --vsync`

**Comment by tim241** [comment]
I don't have a config file, I don't want to make one either.

**Comment by yshui** [comment]
Can you make sure that you set up autostart correctly?

**Comment by tim241** [comment]
alright, just tested it *again* and it seems to work now weirdly enough. Thanks again :heart:

**Comment by yshui** [comment]
@tim241 Feel free to reopen it if it happens again. Vsync should work with NVIDIA driver + glx backend. If it doesn't it would be _really_ weird. So be sure to check if your command line flags are actually passed to compton.
