### ISSUE TITLE
Compton get 100% CPU when multihead

### ISSUE THREAD

**Issue by mrvik** [yshui/compton#145]
### Platform
ArchLinux with Linux 5.0.4-arch1-1-ARCH

### GPU, drivers, and screen setup
Intel atom N450 (integrated graphics)
Driver: i915
xf86-video-intel: `1:2.99.917+863+g6afed33b-1`
mesa: 19.0.0-1

```
>glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Pineview M  (0xa011)
    Version: 19.0.0
    Accelerated: yes
    Video memory: 384MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 1.4
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Pineview M 
OpenGL version string: 1.4 Mesa 19.0.0

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
Usually I work with the primary screen (I mean, the laptop screen), but sometimes I connect to a external monitor, so the external monitor is on the right of integrated and at it's own resolution.

### Environment
WM: i3

### Compton version
Compton version: v6
```
>compton --diagnostics
**Version:** v6

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/mrvik/.config/compton/compton.conf
```

### Compton configuration:
Please, refer to [my dotfiles](https://gitlab.com/mrvik/dotfiles/blob/master/compton/compton.conf)

### Steps of reproduction
1. Login on TTY (my default, not tested with Display Manager)
2. `xrandr --output VGA1 --auto`
3. `xrandr --output VGA1 --right-of LVDS1`
And now use `top` or `htop` to see how compton eats the CPU.
NOTE: VGA1 is the external display and LVDS1 is the integrated one. See bottom for a asciinema recording of the issue.

### Expected behavior
Compton should work only on one of the screens or on both, but should not kill CPU.

### Current Behavior
Compton uses 100% of the CPU when multihead.

### Stack trace
No stack trace as compton don't crash.

### Other details
[asciinema recording](https://asciinema.org/a/wSpRTxbBdtvFfpNm6AsOpDZCK).

Note: The call to `feh` has nothing to do with the issue, it's just a visual fix for background when the compositor exits.

**Comment by yshui** [comment]
Hmm, cannot reproduce the problem here.

It'd interesting to know where does compton spend CPU time on. Are you familiar with tools like `perf`?

**Comment by mrvik** [comment]
> Are you familiar with tools like `perf`?

No, but I could try

**Comment by mrvik** [comment]
I've started X server, then killed compton and...
- Connected and configured secondary screen
- `perf record 'compton'`
- `perf report`

There are a lot of symbols (unresolved) and the vast majority belonged to i915.
Here's a screenshot of `perf report`
![2019-03-26-163521_1024x559_scrot](https://user-images.githubusercontent.com/18632536/55011183-d91a5f00-4fe5-11e9-9e70-b147a080711f.png)

**Comment by yshui** [comment]
Looks like a driver problem then

Also I just noticed your GPU is quite old. The glx backend really need GL3 to function properly.

**Comment by mrvik** [comment]
I've changed backend to xrender and problem disappeared. Thanks
