### ISSUE TITLE
using glx-fshader-win draws all windows completely black

### ISSUE THREAD

**Issue by jvc2** [yshui/compton#146]
I should probably clarify that I'm not familiar with GLSL/OpenGL programming and I wanted to try out writing custom shaders for compton, which is why I've been struggling with this issue.

### Platform
Arch 5.0.4-arch1-1-ARCH

### GPU, drivers, and screen setup
Intel integrated graphics
`xf86-video-intel 1:2.99.917+863+g6afed33b-1`
`xf86-video-vesa 2.4.0-2`
`mesa 19.0.0-1`
```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ironlake Mobile  (0x46)
    Version: 19.0.0
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 19.0.0
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

### Environment
i3-gaps

### Compton version
```
**Version:** v6-rc1-55-g45fcb48

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: None
```

### Steps of reproduction

1. `$ compton --backend glx --glx-fshader-win "$(cat ~/scripts/compton-shader.glsl)"`

The file:
```
uniform float opacity;
uniform bool invert_color;
uniform sampler2D tex;

void main() {
	vec4 c = texture2D(tex, gl_TexCoord[0].st);
	if (invert_color)
		c = vec4(vec3(c.a, c.a, c.a) - vec3(c), c.a);
	c *= opacity;
	gl_FragColor = c;
}
```
This is the same as compton-default-fshader-win.glsl, but with `gl_TexCoord[0]` changed to `gl_TexCoord[0].st`, otherwise the shader wouldn't compile.

### Expected behavior
Windows would be rendered properly.

### Current Behavior
Everything aside from the root window background color turns black, process has to be killed for windows to be visible again.
Output:
```
[ 03/26/2019 02:04:10.993 get_cfg WARN ] --glx-fshader-win is being deprecated, and might be removed in the future. If you really need this feature, please report an issue to let us know
[ 03/26/2019 02:04:11.041 gl_has_extension ERROR ] Failed to get GL extension list.
[ 03/26/2019 02:04:11.046 glx_load_prog_main ERROR ] GLX error at line 438: GL_INVALID_ENUM
[ 03/26/2019 02:04:11.065 gl_has_extension ERROR ] Failed to get GL extension list.
[ 03/26/2019 02:04:11.076 glx_set_clip ERROR ] GLX error at line 632: GL_INVALID_ENUM
[ 03/26/2019 02:04:11.077 glx_bind_pixmap ERROR ] GLX error at line 584: GL_INVALID_ENUM
```

### Other details
When the `-f` option is passed, the black windows fade in/out when switching workspaces, as they should, so I suppose the shader applies the opacity properly at least?

**Comment by yshui** [comment]
Your GPU is too old so the glx backend might not work properly (it requires OpenGL 3.0 to be fully functional).

**Comment by jvc2** [comment]
Thanks, I also wasn't aware v6 doesn't support OpenGL < 3.0 so it was bad timing on my part to try out shaders just as it was released.

**Comment by yshui** [comment]
@jvc2 This probably won't work in earlier versions either.

**Comment by jvc2** [comment]
I'm testing it on v5.1 and shaders seem to work fine, I haven't come across any issues yet.
