### ISSUE TITLE
New Version with automatic vsync, now renders compton unuseable

### ISSUE THREAD

**Issue by 0mni** [yshui/compton#149]
With the boolean only option for vsync, this new direction you are taking has rendered compton completely unusable.  I need a specific version of vsync to work on my laptop, otherwise its screen tearing galore.  I now have no way to specify opengl-swc and because of this, this new direction that you are taking is extremely bad.  It's good idea, poor execution. please bring back the manual specification of setting vsync.

**Comment by yshui** [comment]
Setting `--vsync`, or `vsync = true` now is equivalent to `vsync = opengl-swc` previously.

If that stopped working for your, this change is not the reason.

**Comment by yshui** [comment]
I will close this as invalid since there is no response from the reporter.

Please reopen if necessary

**Comment by CyberShadow** [comment]
> Please reopen if necessary

(FYI, reporters can only reopen issues if it was them who closed it; otherwise, it can only be done by someone with write access.)

**Comment by yshui** [comment]
@CyberShadow (Thanks for pointing that out!)
