### ISSUE TITLE
"ninja -C build install" failed on Linux Mint 18.3. xcb_render related errors.

### ISSUE THREAD

**Issue by aasril** [yshui/compton#154]
### Platform
Linux Mint 18.03 amd64 (based on Ubuntu 16.04 LTS)

### GPU, drivers, and screen setup
A Lenovo G400 laptop with Intel GPU

### Environment
i3-gaps

### Compton version
Both v6 and git version

### Steps of reproduction
I ran the build with this command:
    CC=clang-7 meson --buildtype=release . build
and everything seems to be satisfied.

And then tried to install compton with this command:
    CC=clang-7 ninja -C build install
and came out with errors related to xcb_render. removing CC assignment to clang-7 on this command still produces the same errors.

Output from both commands can be found on this [gist](https://gist.github.com/aasril/15df81c78b744d87f32b814c0fcaddef).

**Comment by yshui** [comment]
Your `xcb-render` is too old.

**Comment by aasril** [comment]
Updating xcb-render and its dependencies to the packages from Ubuntu 18.04 (v 1.13-1) get rid of the errors. Not sure if that's a good idea playing with different release packages but after that the build and install ran successfully.

I'll list the packages I updated here, if it's alright, in case someone else is interested and for the sake of my documentation:
```
libpthread-stubs0-dev_0.3-4_i386.deb
libxau-dev_1.0.8-1_amd64.deb
libxau-dev_1.0.8-1_i386.deb
libxcb1_1.13-1_amd64.deb
libxcb1_1.13-1_i386.deb
libxcb1-dev_1.13-1_amd64.deb
libxcb1-dev_1.13-1_i386.deb
libxcb-render0_1.13-1_amd64.deb
libxcb-render0_1.13-1_i386.deb
libxcb-render0-dev_1.13-1_amd64.deb
libxcb-render-util0_0.3.9-1_amd64.deb
libxcb-render-util0-dev_0.3.9-1_amd64.deb
libxdmcp6_1.1.2-3_amd64.deb
libxdmcp6_1.1.2-3_i386.deb
libxdmcp-dev_1.1.2-3_amd64.deb
libxdmcp-dev_1.1.2-3_i386.deb
```

**Comment by yshui** [comment]
No problem!

Closing
