### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by Bysmyyr** [yshui/compton#156]
// The template below is for reporting bugs. For feature requests and others, feel free to delete irrelevant entries.

### Platform
Fedora 28 amd64

### GPU, drivers, and screen setup
// Example: NVidia GTX 670, nvidia-drivers 381.09, two monitors configured side-by-side with xrandr
// Please include the version of the video drivers (xf86-video-*) and mesa.
// Please also paste the output of `glxinfo -B` here.

0:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
    Version: 18.0.5
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.2

Laptop screen blank, 4k display connected through usb-c

### Environment
// Tell us something about the desktop environment you are using, for example: i3-gaps, Gnome Shell, etc.

Kde

### Compton version
// Put the output of `compton --version` here.
// If you are running compton v4 or later, please also include the output of `compton --diagnostics`
0.1-0.1.beta3.fc28

### Compton configuration:
```
// Paste your configuration here
```
compton --backend glx --glx-fshader-win "$(cat shift.glsl)" --invert-color-include id!=0

but also this has same problems:
compton --backend glx (no other conf afaik)

15:22 $ cat shift.glsl 
uniform bool invert_color;
uniform float opacity;
uniform sampler2D tex;

/**
 * This shader inverts colors smartly.
 *
 * In contrast to simple RGB negation, it keeps blue-ish colors blue,
 * red-ish colors red etc.
 *
 * In contrast to color matrix multiplication techniques,
 * it keeps the colors "rich" (they take full RGB spectrum)
 * and it precisely retains "hue" component of the color.
 * (Matrices don't do that.)
 *
 * See screenshots if in doubt. https://github.com/vn971/linux-color-inversion
 */
void main() {
        vec4 c = texture2D(tex, gl_TexCoord[0].st);
        if (invert_color) {
                // This transformation is exactly equal to rgb-negation combined with
                // HUE rotation by 180 degrees.
                //
                // It's very non-obvious that this combination leads to correct
                // colors, yet it does, and perfectly so.
                //
                // About this formula.
                //
                // Let's call "old_color" the old color,
                // "r","g","b" the components of the old color,
                // "new_color" the new color we want to derive,
                // "old_c" the old color component and
                // "new_c" the new color component.
                //
                // We have the following equasion then:
                // new_color = rgb_negation(hue_180_rotate(old_color)) <=>
                // new_c = rgb_negation(reflection_around_min_max_rgb(old_c)) <=>
                // new_c = rgb_negation(max(r,g,b) - (old_c - min(r,g,b))) <=>
                // new_c = old_alpha - (max(r,g,b) - old_c + min(r,g,b)) <=>
                // new_c = old_alpha - max(r,g,b) - min (r,g,b) + old_c

                float shift = c.a - min(c.r, min(c.g, c.b)) - max(c.r, max(c.g, c.b));
                c = vec4(shift + c.r, shift + c.g, shift + c.b, c.a);
        }
        c *= opacity;
        gl_FragColor = c;
}

### Steps of reproduction
// If you can reliably reproduce this bug, please describe the quickest way to do so
// This information will greatly help us diagnosing and fixing the issue.

1.
2.

### Expected behavior
smooth inverted view

### Current Behavior

time to time(more than 10 times per hour) everything exept mouse stops for 1 to 3 seconds

### output:
[    26.39 ] error    9 BadDrawable  request   14 minor    0 serial  19152: "BadDrawable (invalid Pixmap or Window parameter)"
glx_bind_pixmap(0x08e006ec): Failed to query Pixmap info.
win_paint_win(0x024039e3): Failed to bind texture. Expect troubles.
win_paint_win(0x024039e3): Missing painting data. This is a bad sign.
[    26.40 ] error    4 BadPixmap    request   54 minor    0 serial  19172: "BadPixmap (invalid Pixmap parameter)"
[    99.20 ] error    9 BadDrawable  request   14 minor    0 serial 137163: "BadDrawable (invalid Pixmap or Window parameter)"
glx_bind_pixmap(0x08e02a98): Failed to query Pixmap info.
win_paint_win(0x024039ee): Failed to bind texture. Expect troubles.
win_paint_win(0x024039ee): Missing painting data. This is a bad sign.
[    99.21 ] error    4 BadPixmap    request   54 minor    0 serial 137183: "BadPixmap (invalid Pixmap parameter)"
[   164.29 ] error    9 BadDrawable  request   14 minor    0 serial 205910: "BadDrawable (invalid Pixmap or Window parameter)"
glx_bind_pixmap(0x08e03f93): Failed to query Pixmap info.
win_paint_win(0x024039f9): Failed to bind texture. Expect troubles.
win_paint_win(0x024039f9): Missing painting data. This is a bad sign.
[   164.29 ] error    4 BadPixmap    request   54 minor    0 serial 205930: "BadPixmap (invalid Pixmap parameter)"
[   233.87 ] error    9 BadDrawable  request   14 minor    0 serial 248826: "BadDrawable (invalid Pixmap or Window parameter)"
glx_bind_pixmap(0x08e04ce4): Failed to query Pixmap info.
win_paint_win(0x0680001e): Failed to bind texture. Expect troubles.
win_paint_win(0x0680001e): Missing painting data. This is a bad sign.
[   233.88 ] error    4 BadPixmap    request   54 minor    0 serial 248845: "BadPixmap (invalid Pixmap parameter)"
[   389.50 ] error    9 BadDrawable  request   14 minor    0 serial 344868: "BadDrawable (invalid Pixmap or Window parameter)"
glx_bind_pixmap(0x08e06a2b): Failed to query Pixmap info.
win_paint_win(0x02403a04): Failed to bind texture. Expect troubles.
win_paint_win(0x02403a04): Missing painting data. This is a bad sign.
[   389.51 ] error    4 BadPixmap    request   54 minor    0 serial 344888: "BadPixmap (invalid Pixmap parameter)"

**Comment by yshui** [comment]
Can you update to the most recent version of compton?

**Comment by Bysmyyr** [comment]
Yep, just updating the whole system to newest fedora. I forgot to mention, this lagging started one month ago. Before that everything worked smoothly.

**Comment by yshui** [comment]
@Bysmyyr Fedora is not using the most recent version of compton

**Comment by Bysmyyr** [comment]
Looks like it is working again. SOrry for distrupt
