### ISSUE TITLE
System freezes when compton is run from i3status-rust

### ISSUE THREAD

**Issue by anowlcalledjosh** [yshui/compton#159]
### Platform

Ubuntu Desktop 18.04 amd64

### GPU, drivers, and screen setup

Intel integrated graphics, mesa 18.2.8, two monitors configured vertically with xrandr

<details><summary><code>glxinfo -B</code></summary>

```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)  (0x3e9b)
    Version: 18.2.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

### Environment

i3 4.16-123-g6f920d6dc

### Compton version

v5-rc4-72-gedb8b38ee and v6-rc1-99-gfb53ff50a, to name two

```
$ compton --diagnostics
**Version:** v5-rc4-72-gedb8b38ee

### Extensions:

* Name Pixmap: Yes
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/josh/.config/compton.conf
```

### Compton configuration:

```
# Backend ##############################################################

# Can be "xrender" or "glx"; GLX is faster (usually) but needs a sane driver.
backend = "glx";

# GLX backend ##########################################################

# Magically improve performance. Can allegedly cause issues with transparency.
glx-no-stencil = true;

# Possible big performance boost on partial screen updates, but breaks with some drivers.
glx-no-rebind-pixmap = true;

# "buffer-age" (or -1) apparently auto-detects it.
# A value between -1 and 6.
# -1 (or "buffer-age") autodetects.
# 0 is slowest, but always works.
# 1 is broken with the modesetting driver on Intel graphics.
# 2 is also broken in that configuration (but a little less so).
# 3 works.
glx-swap-method = 3;

# Vsync ################################################################

vsync = true;

# Attempt to unredirect when a fullscreen window is detected for improved performance.
unredir-if-possible = true;
# Don't unredirect windows that asked for compositing.
unredir-if-possible-exclude = [
	"_NET_WM_BYPASS_COMPOSITOR@:c = 2",
	"class_g = 'Totem'"
];

```

### Steps of reproduction

1. Have a `custom` block in [i3status-rust](https://github.com/greshake/i3status-rust) that runs compton on click:

    ```
    [[block]]
    block = "custom"
    cycle = ["echo aaa", "echo bbb; compton >/dev/null"]
    interval = 1000000000
    ```
2. Click the block

### Expected behavior

Compton should run as if it was run in the terminal

### Current Behavior

The system freezes; the mouse moves, but the cursor doesn't change, and nothing reacts to clicks. The TTYs work, but compton doesn't respond to signals and has to be `kill -9`'d (after which the system returns to normal). As far as I can tell compton doesn't produce any output, even with `--log-level trace`.

### Other details

In reality I have a small script that handles starting and stopping compton when the i3status-rust block is clicked, but the problem is reproducible without that.

I remember this working for a long time, but even after trying several old versions of both compton and i3status-rust I can't find a combination that doesn't freeze.

Presumably i3status-rust is doing something weird to make compton do this, and I nearly filed this bug against i3status-rust, but I'm justifying filing it here by saying that compton should probably not freeze the system and ignore all signals however badly the environment is broken :)

**Comment by yshui** [comment]
i3bar suspended the compton process with SIGSTOP, not a compton problem.
