### ISSUE TITLE
unredir-if-possible froze screen

### ISSUE THREAD

**Issue by alaviss** [yshui/compton#160]
### Platform
Gentoo amd64

### GPU, drivers, and screen setup
Intel HD 5500 on `modesetting` driver, mesa 18.3.6
<details>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  (0x1616)
    Version: 18.3.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

</details>

### Environment
i3-gaps

### Compton version
`compton --version`: `v6-rc1-122-g72ede42`
`compton --diagnostics`:

<details>

```
**Version:** v6-rc1-122-g72ede42

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/leorize/local/config/compton.conf

### Drivers (inaccurate):

modesetting
```

</details>

### Compton configuration:
```
unredir-if-possible: true;
```

### Steps of reproduction
1. run `compton`

### Expected behavior
Not freezing the screen

### Current Behavior
Froze the screen

**Comment by yshui** [comment]
Does the screen freeze happen immediately after you start compton? 

Also IIUC, this problem doesn't happen at all if you set `unredir-if-possible` to false?

**Comment by alaviss** [comment]
Yep, all correct.

**Comment by yshui** [comment]
Can you run compton with `--log-level=trace --log-file=compton.log`, and upload `compton.log`?

**Comment by alaviss** [comment]
Here you go: [compton.log](https://github.com/yshui/compton/files/3112473/compton.log)

**Comment by yshui** [comment]
@alaviss I added some debug prints to the `redir-debug` branch, can you get a log file with that branch?

**Comment by alaviss** [comment]
Here's the log with `redir-debug` branch: [compton.log](https://github.com/yshui/compton/files/3119473/compton.log)

**Comment by yshui** [comment]
@alaviss Should be fixed in `next`
