### ISSUE TITLE
Inkscape preferences window: 50% instead of 100% opacity

### ISSUE THREAD

**Issue by WernerFP** [yshui/compton#162]
### Platform
Distro: Arch Linux
Kernel: 5.0.9-arch1-1-ARCH x86_64

### GPU, drivers, and screen setup
Device-1: NVIDIA GK104 [GeForce GTX 770]
Driver: nvidia v: 418.56
Display: x11
Server: X.Org 1.20.4
Resolution: 2560x1440 60Hz, 2560x1440 60Hz

### Environment
Desktop: Openbox 3.6.1

### Compton version
v6.2

### Compton configuration:
```
# Backend

backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
glx-copy-from-front = false;
xrender-sync-fence = true;
use-damage = true;
vsync = true;

# Shadow

shadow = true;
shadow-radius = 16;
shadow-offset-x = -14;
shadow-offset-y = -13;
shadow-opacity = 0.3;

# Other

detect-rounded-corners = true;

shadow-exclude = [
	"_GTK_FRAME_EXTENTS@:c",
 	"g:e:Conky",
 	"class_g ?= 'Polybar'",
 	"class_g = 'Notify-osd'",
 	"class_g = 'Cairo-dock'",
 	"class_g = 'Xfce4-notifyd'",
 	"class_g = 'Xfce4-power-manager'",
	"_GTK_FRAME_EXTENTS@:c",
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# Opacity (Inkscape test)

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
detect-client-opacity = true;

# Window type settings

wintypes:
{
	utility = { full-shadow = true; };
	popup_menu = { full-shadow = true; };
	dock = { full-shadow = false; };
	dnd = { full-shadow = false; };
	desktop = { shadow = false; };
	splash = { shadow = false; };
	dialog = { inactive-opacity = 1; active-opacity = 1; }; # (Inkscape test)

};
```

### Expected behavior
If the opacity values in `~/.compton.conf` are set to `1`, the Inkscape preferences window (type dialog) should keep 100% opacity in every state.

### Current Behavior
The Inkscape preferences window (*Edit → Preferences*) becomes transparent (50% opacity) when it is moved, is inactive, or a settings menu is expanded:
```
$ xprop | grep -i opacity
_NET_WM_WINDOW_OPACITY(CARDINAL) = 2147483647
```

### Other details
Inkscape version: 0.92.4-4

**Comment by biopsin** [comment]
In Inkscape do
-> preference -> Interface -> Windows -> Dialog trancparency -> opacity when unfocused
set it to 1,0000

**Comment by WernerFP** [comment]
Ups :smiley:
Thank you @biopsin and sorry for false alarm!
I close it as solved.
