### ISSUE TITLE
GLX Support not working on older gpu

### ISSUE THREAD

**Issue by kanehekili** [yshui/compton#165]
### Platform
Arch linux amd64

### GPU, drivers, and screen setup
Card: Intel Mobile GM965/GL960 Integrated Graphics Controller, two monitors configured side-by-side with xrandr
xf86-video-intel 1:2.99.917+863+g6afed33b-1 (xorg-drivers) - X.org Intel i810/i830/i915/945G/G965+ video drivers
mesa 19.0.3-1

`glxinfo -B`:
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) 965GM  (0x2a02)
    Version: 19.0.3
    Accelerated: yes
    Video memory: 384MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 965GM 
OpenGL version string: 2.1 Mesa 19.0.3
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
### Environment
LXDE

### Compton version
Compton 6.2-2
### Compton configuration:
```
None - the errors occur even with no config
compton --backend glx --config /dev/null
```

### Steps of reproduction
1.execute without a configuration: compton --backend glx --config /dev/null 
2. 2019-05-01 23:23:56.457 gl_has_extension ERROR ] Failed to get GL extension list.
[ 2019-05-01 23:23:56.486 gl_has_extension ERROR ] Failed to get GL extension list.
[ 2019-05-01 23:23:56.495 wid_set_text_prop ERROR ] Failed to make text property: v6.2.
[ 2019-05-01 23:23:56.495 register_cm ERROR ] Failed to set COMPTON_VERSION.
[ 2019-05-01 23:23:56.790 glx_set_clip ERROR ] GLX error at line 632: GL_INVALID_ENUM
[ 2019-05-01 23:23:56.791 glx_bind_pixmap ERROR ] GLX error at line 584: GL_INVALID_ENUM

3. Reverting to an older compton version (here 1.0.1) resolves the issue.

### Expected behavior
No errors
### Current Behavior
Compton seems to run, but is sluggish and unusable

**Comment by yshui** [comment]
Please use the xrender backend if you are using an old graphic card.

**Comment by kanehekili** [comment]
Well, there are other versions of compton that (still) work. Using Xrender is not a valid solution. So your fork is useless for me. Sorry.

**Comment by yshui** [comment]
@kanehekili If other version of compton works better for you, you should use those.

Just curious, why is xrender not a valid solution?

**Comment by kanehekili** [comment]
xrender is NOT an option, since everything is unbearable sluggish. 
This fork does not seem to work with the "old" stuff. The machine I'm talking about is a Thinkpad R61. build in 2007 (12 Years ago) Sturdy and reliable.
I've gone back to the chjj version, which still works for me. 
Still I appreciate your work of maintaining this software. Keep it up!
