### ISSUE TITLE
compton.desktop reported to be broken?

### ISSUE THREAD

**Issue by arcolinuxz** [yshui/compton#17]
### Platform
ArcoLinux Xfce

### Compton version
v2.0

### Steps of reproduction
// If you can reliably reproduce this bug, please describe the quickest way to do so
// This information will greatly help us diagnosing and fixing the issue.

You can right menu click on the whiskermenu (once installed) and open menulibre to open/change the menu.
Out all applications only Compton.desktop is reported to be... you see the images.
![compton-error](https://user-images.githubusercontent.com/36679406/46619441-6a724380-cb22-11e8-8117-85fe1c7bf8db.jpg)
![compton-errors1](https://user-images.githubusercontent.com/36679406/46619442-6b0ada00-cb22-11e8-91c9-678dd4ca1fed.jpg)
![compton-errors-2](https://user-images.githubusercontent.com/36679406/46619445-6b0ada00-cb22-11e8-8f6d-67690c230f9c.jpg)
![compton-errors-3](https://user-images.githubusercontent.com/36679406/46619448-6b0ada00-cb22-11e8-851d-a91060bf3347.jpg)

I have tried to fiddle around with the .desktop file. Somewhere it must be missing something to show up on this report of menulibre.
Not urgent but annoying.

**Comment by yshui** [comment]
This is a packaging problem of your distro. They shouldn't change the `TryExec` value is the desktop file. Please report this bug to your distro.

**Comment by arcolinuxz** [comment]
You are right this is your .desktop files
```

[Desktop Entry]
Version=1.0
Type=Application
Name=compton
GenericName=X compositor
Comment=A X compositor
Categories=Utility;
TryExec=compton
Exec=compton
Icon=compton
# Thanks to quequotion for providing this file!
```

and this the one coming from Arch Linux
I suppose it is the  --xrender-sync-fence that triggers the message
```

[Desktop Entry]
Version=1.0
Type=Application
Name=compton
GenericName=X compositor
Comment=Compositor for X11
Categories=Utility;
TryExec=compton --xrender-sync-fence
Exec=compton --xrender-sync-fence
Icon=compton
# Thanks to quequotion for providing this file!
```

**Comment by yshui** [comment]
@arcolinuxz I reported the bug on Arch bug tracker. Hopefully it will propagate to Arco as well.

**Comment by yshui** [comment]
@arcolinuxz https://bugs.archlinux.org/task/60363

**Comment by yshui** [comment]
@arcolinuxz Arch updated its package.

**Comment by arcolinuxz** [comment]
yes thanks - have seen it - I can report that it works now - no more errors
