### ISSUE TITLE
"Failed to get GL extension list" error

### ISSUE THREAD

**Issue by wyjek** [yshui/compton#171]
// The template below is for reporting bugs. For feature requests and others, feel free to delete irrelevant entries.

### Platform
// Example: Ubuntu Desktop 17.04 amd64
Void Linux amd64

### GPU, drivers, and screen setup
// Example: NVidia GTX 670, nvidia-drivers 381.09, two monitors configured side-by-side with xrandr
// Please include the version of the video drivers (xf86-video-*) and mesa.
// Please also paste the output of `glxinfo -B` here.
Nvidia GeForce 7100, xf86-video-nouveau 1.0.16, mesa-nouveau-dri 19.0.3, one monitor

`glxinfo _B` output:
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NV63 (0x7e1)
    Version: 19.0.3
    Accelerated: yes
    Video memory: 117MB
    Unified memory: no
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: nouveau
OpenGL renderer string: NV63
OpenGL version string: 2.1 Mesa 19.0.3
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

### Environment
// Tell us something about the desktop environment you are using, for example: i3-gaps, Gnome Shell, etc.
I'm using i3-gaps.

### Compton version
// Put the output of `compton --version` here.
// If you are running compton v4 or later, please also include the output of `compton --diagnostics`
// Example: v1
v6

`compton --diagnostics`:
**Version:** v6

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/wyjek/.config/compton/compton.conf

### Compton configuration:
```
// Paste your configuration here
```
`backend = "glx";`

I also run compton with parameters `-b --unredir-if-possible --vsync --glx-no-stencil`.
### Steps of reproduction
// If you can reliably reproduce this bug, please describe the quickest way to do so
// This information will greatly help us diagnosing and fixing the issue.

1.
2.

### Current Behavior
When I run compton in terminal, I get that error:
`[ 14.05.2019 19:57:26.775 gl_has_extension ERROR ] Failed to get GL extension list.`
`[ 14.05.2019 19:57:26.804 gl_has_extension ERROR ] Failed to get GL extension list.`

### Stack trace
// If compton crashes, please make sure your compton is built with debug info, and provide a stack trace of compton when it crashed.
// Note, when compton crashes in a debugger, your screen might look frozen. But gdb will still handle your input if it is focused.
// Usually you can use 'bt' and press enter to get the stack trace, then 'q', enter, 'y', enter to quit gdb.

// Or, you can enable core dump, and upload the core file and the compton executable here.

### Other details
// If your problem is visual, you are encouraged to record a short video when the problem occurs and link to it here.

I'm not sure what's the problem, it could be that my GPU is outdated, looks like everything is working fine, but I'm curious if this is some serious issue and I should use `xrender` instead of `glx` or something. I'm sorry if this error was mentioned in some older issue.

**Comment by yshui** [comment]
Sorry, the glx backend requires at least GL 3.0. It might work on GL2 now, but it is not guaranteed to continue working in the future.

You can try xrender, the performance is usually not too bad.

**Comment by yshui** [comment]
The latest `next` might make the error go away, at least for now.

**Comment by wyjek** [comment]
> The latest `next` might make the error go away, at least for now.

You're right, the error is gone, but animations feel choppy, but it's already better than xrender (animations feel slowed-down). Maybe there's something wrong with the parameters I use to run compton? I just want vsync with the least of GPU usage (because it's quite old).

**Comment by yshui** [comment]
@wyjek Adding `--use-damage` might help.

**Comment by yshui** [comment]
Since the issue originally reported is fixed, I'm closing this.
