### ISSUE TITLE
sw-opti performance

### ISSUE THREAD

**Issue by Ristovski** [yshui/compton#172]
On a crude `vblank_mode=0 glxgears` benchmark, which is of course _not_ a real benchmark, enabling "sw-opti" yields a 3000FPS performance boost.

The biggest impact is on CPU usage - 44% with `sw-opti` enabled vs 68% with it disabled.

Sys info:
Haswell with xf86-video-intel/mesa from -git
Xmonad

Is there a reason for it being deprecated?

**Comment by yshui** [comment]
With sw-opti enabled, the update rate is limited to refresh rate anyway. The 3000FPS reported by glxgears doesn't mean _anything_.

If enabling sw-opti improves your CPU usage, then enabling vsync should do the same thing.

`sw-opti` is deprecated because it's pointless.
