### ISSUE TITLE
unable to compile on Debian

### ISSUE THREAD

**Issue by jEsuSdA** [yshui/compton#179]
### Platform
Debian Testing amd64

### Current Behavior

meson --buildtype=release . build
The Meson build system
Version: 0.49.2
Source dir: /tmp/000/compton-vNext
Build dir: /tmp/000/compton-vNext/build
Build type: native build
Project name: compton
Project version: 6
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Has header "stdc-predef.h" : YES
Compiler for C supports arguments -Wall: YES
Compiler for C supports arguments -Wextra: YES
Compiler for C supports arguments -Wno-unused-parameter -Wunused-parameter: YES
Compiler for C supports arguments -Wnonnull: YES
Compiler for C supports arguments -Wshadow: YES
Compiler for C supports arguments -Wno-type-limits -Wtype-limits: YES
Compiler for C supports arguments -Wimplicit-fallthrough: YES
Compiler for C supports arguments -Wno-unknown-warning-option -Wunknown-warning-option: NO
Compiler for C supports arguments -Wno-missing-braces -Wmissing-braces: YES
Compiler for C supports arguments -Wconversion: YES

meson.build:64:0: ERROR:  Failed to initialize 'subprojects/test.h':
Subproject exists but has no meson.build file

[meson-log.txt](https://github.com/yshui/compton/files/3217672/meson-log.txt)

Any suggestion?
Thanks a lot!

**Comment by yshui** [comment]
Run `git submodule update --init`
