### ISSUE TITLE
terminal flicking when opened

### ISSUE THREAD

**Issue by tuyenpm9** [yshui/compton#18]
### Platform
archlinux latest

### GPU, drivers, and screen setup
intel

### Compton version
latest from aur compton-git 2:Next.r3.g9654d0b_2018.10.04-1

### Compton configuration:
```
--backend glx
```

### Steps of reproduction
I just want to disable compton on urxvt or exterm for example, completely.

**Comment by yshui** [comment]
That's not possible, you either composite all windows or non of them.

Maybe I ask why do you want to do that?

**Comment by tuyenpm9** [comment]
I need compton to address tearing but it causes flick when I start wm with terminal, terminal has a flick when it appears.

Is there any options that can address flick?

**Comment by yshui** [comment]
@tuyenpm9 it would be nice if you can provide a recording of the flickering

**Comment by tuyenpm9** [comment]
Fixed by adding this option `--unredir-if-possible false`,

Documented in archwiki but I ignored it. closed and remove refer linked.

**Comment by yshui** [comment]
@tuyenpm9 `unredir-if-possible` is false by default, you must have that enabled somewhere in your configuration file.

**Comment by tuyenpm9** [comment]
@yshui I didn't use `.config/compton.conf`, are you sure it `false` by default with latest patches in https://aur.archlinux.org/packages/compton-git/?

**Comment by tuyenpm9** [comment]
Just test again and it still works perfect only explicitly has this in `.xinitrc`: `compton --unredir-if-possible false <other options>`

**Comment by tuyenpm9** [comment]
I think I should use "one time blink" instead of flick.

**Comment by yshui** [comment]
@tuyenpm9 I see. That is odd, I will look into this.

**Comment by tuyenpm9** [comment]
For more information, I start terminal in fullscreen mode. So archwiki does help.

**Comment by tuyenpm9** [comment]
`--unredir-if-possible false` is wrong parameter in command line, so it failed and compton weren't invoked.

I incured blink when invoke compton in `.xinitrc`, it happened less with this command `compton --backend glx` and strong blink/flick when add more options. 

Does we have solution for this issue, flick when invoke compton in terminal, calling in wm would help?
