### ISSUE TITLE
fullscreen unredirection on xfwm4 and "detect-rounded-corners" option

### ISSUE THREAD

**Issue by Ropid** [yshui/compton#181]
I just noticed a problem with Freesync after removing the following line from my Compton config:

    detect-rounded-corners = true;

Freesync only works if that option is there. With the option removed, Freesync stops working.

I assume what's happening is that Compton's unredirection does not work if I do not use that detect_rounded_corners option, and that's then the cause for Freesync not working.

The setup is the following:

* Hardware:
    * AMD RX480
    * single monitor at 144Hz with Freesync
* ArchLinux
* XFCE (xfwm4 4.12.5)
* Mesa 19.1.0-rc4
* llvm 9 git
* xf86-video-amdgpu 19.0.1

Compton:

    $ compton --version
    v6-rc1-148-g4a74b4f

I start compton like this:

    compton --experimental-backends

With the following config:

    backend = "glx";
    # backend = "xrender";
    vsync = true;
    
    use-damage = true;
    
    # glx-no-stencil = true;
    # glx-no-rebind-pixmap = true;
    # glx-swap-method = -1;
    
    shadow = true;
    
    shadow-radius = 16;
    shadow-offset-x = -16;
    shadow-offset-y = -12;
    shadow-opacity = 0.35;
    
    # detect-rounded-corners = true;
    
    shadow-exclude = [
        "class_g = 'Xfwm4'",
        "(class_g = 'Firefox' || class_g = 'Nightly') && window_type = 'utility'",
        "_GTK_FRAME_EXTENTS@:c",
        # "window_type = 'normal' && !I3_FLOATING_WINDOW@:c",
    ];
    
    inactive-opacity = 1;
    active-opacity = 1;
    frame-opacity = 1;
    inactive-opacity-override = false;
    
    blur-background = false;
    # blur-background-frame = true;
    # blur-background-fixed = true;
    # blur-kern = "7x7box";
    # blur-background-exclude = [
    #     "window_type = 'dock'",
    #     "window_type = 'desktop'",
    #     "_GTK_FRAME_EXTENTS@:c"
    # ];
    
    fading = false;
    # fade-delta = 4;
    fade-in-step = 0.2;
    fade-out-step = 0.2;
    # no-fading-openclose = true;
    
    fade-exclude = [ ];
    
    mark-wmwin-focused = true;
    mark-ovredir-focused = true;
    use-ewmh-active-win = true;
    
    detect-client-opacity = true;
    
    unredir-if-possible = true;
    
    unredir-if-possible-exclude = [
        "_NET_WM_BYPASS_COMPOSITOR@:c = 2",
        "class_g = 'MComix'",
        "class_g = 'vlc'",
        # "class_g = 'Firefox'",
        # "class_g = 'Nightly'",
    ];
    
    focus-exclude = [ ];
    
    detect-transient = true;
    detect-client-leader = true;
    
    wintypes:
    {
        tooltip = { full-shadow = true; fade = true; shadow = false; opacity = 0.8; focus = true; };
        dock    = { shadow = false; };
        dnd     = { shadow = false; };
    };

**Comment by Ropid** [comment]
I think it's really 'unredirection' that's not working, it's not just some weird freesync problem. To prove this, I experimented by running compton with a bunch of different command lines with Mesa's fps counter enabled:

    GALLIUM_HUD=simple,fps compton --config /dev/null --experimental-backends --backend glx --unredir-if-possible

    GALLIUM_HUD=simple,fps compton --config /dev/null --experimental-backends --backend glx --unredir-if-possible --detect-rounded-corners

    GALLIUM_HUD=simple,fps compton --config /dev/null --backend glx --unredir-if-possible --detect-rounded-corners

    GALLIUM_HUD=simple,fps compton --config /dev/null --backend glx --unredir-if-possible

I then started glxgears and forced its window into fullscreen with a hotkey. The glxgears window should then normally get unredirected and Mesa's fps counter should not be visible. This only works right here for me for the command lines that had "--detect-rounded-corners". On the ones without the option, the window stays redirected and the fps counter stays visible.

**Comment by Ropid** [comment]
Thinking about this some more, I guess this "detect-rounded-corners" option maybe only exists because xfwm4 is strange? In that case this here isn't really a problem? I'll close the issue.

**Comment by yshui** [comment]
@Ropid This option is there because otherwise windows with rounded corners won't be considered as "fullscreen".
