### ISSUE TITLE
Screen Tearing On Top Of The Videos After Upgrade to X.Org Server 1.20.5

### ISSUE THREAD

**Issue by javashin** [yshui/compton#183]
On Linux , tested on Arch And Gentoo.

X.Org Server 1.20.5 and Xf86-video-intel + compton causes screen tearing on top of videos 
not happen with 1.20.4 something changed i have to move and modesetting + glamor with compton works fine

**Comment by rien333** [comment]
Yeah, screen tearing definitely seems worse on X.Org 1.20.5 (on Arch, running on modesetting). If somebody has a fix around please do tell!

**Comment by FrancescoCappio** [comment]
Same problem in Arch Linux. I noticed screen tearing mostly while scrolling (in Firefox, but also in other apps). For the moment I downgraded to X.org 1.20.4 and the problem is gone but obviously it is not a good solution

**Comment by javashin** [comment]
compton compiled from next branch , compton --experimental-backends --backend glx with modesetting and  X.org 1.20.5 works fine here no tearing on arch and gentoo

**Comment by rien333** [comment]
@javashin that seems to work a little better, but still worse than I remember it to be. For example, `sxiv` seem to flash a lot when resizing images and fullscreen video's still have significant tearing. However, non-fullscreen video's seem to work a little better with the ` --experimental-backends` flag you suggested.

**Comment by javashin** [comment]
sxiv works fine here on gentoo i dont see any flickering or tearing on any videos on mpv firefox youtube or chromium youtube everything is fine also im using mate-desktop with marco window manager and everything is just fine with modesetting new xorg and compton --experimental-backends --backend glx and this on xorg.conf 

Section "Device" 
    Identifier "intel" 
    Driver "modesetting" 
    Option "AccelMethod" "glamor"
   Option "DRI" "3" 
  Option      "TearFree" "false"

**Comment by rien333** [comment]
My xorg.conf looks kinda different, I'll try yours and report back in a bit.

**Comment by rien333** [comment]
Again, slightly better, but downgrading to Xorg 1.20.4 still gives much better results. 
For example, qutebrowser and mpv play this screen tearing test video without problems when on 1.20.4:
https://www.youtube.com/watch?v=MfL_JkcEFbE

**Comment by javashin** [comment]
mpv -vo vaapi https://www.youtube.com/watch?v=MfL_JkcEFbE played fine
but im telling i have mate-desktop using marco which was compiled with xpresent  x11-libs/libXpresent.
try the configuration i told before but with mate-desktop or just install marco window manager and look there is no tearing anywhere

**Comment by javashin** [comment]
modesetting is fine for me but i use xf86-video-intel which is why im worried , i get screen tearing on top of the videos with intel ddx but not with modesetting and im always using mate-desktop with marco and compton

**Comment by rien333** [comment]
For what it's worth, I run bspwm, but I don't really suspect the issue lies there, nor do I think mate/marco is doing something super interesting in regard to this issue (although the GNOME project does have a compositor of it's own, I think?). 

`mpv` had problems running aforementioned video regardless of what I supplied to `-vo`,  as you seemed to suggest. FIY, the mpv docs recommend against using `--vo=vaapi`.
(see https://mpv.io/manual/master/#video-output-drivers-vaapi)

> modesetting is fine for me but i use xf86-video-intel which is why im worried

I actually get tearing with both.

**Comment by FrancescoCappio** [comment]
In my case the problem is with i3 so I don't think it is wm-related

**Comment by yshui** [comment]
If there is strong evidence supporting that downgrading xorg to 1.20.4 fixes your problem, you should open a ticket on the Arch Linux issue tracker.

And maybe on Xorg issue tracker as well.

**Comment by aufkrawall** [comment]
I can confirm this with xorg-git + xf86-video-intel-git on Gemini Lake, totally breaks new xrender Present vsync.
modesetting of xorg-git works, but it still has a stutter issue with mpv (not related to any compositor).

I suppose we should report this to the xf86-video-intel DDX devs.
(AMD, please provide us with cheap and modern entry level notebooks as an alternative...)

**Comment by aufkrawall** [comment]
Hm, old GLX backend vsync works fine here.

**Comment by javashin** [comment]
@aufkrawall with  xf86-video-intel DDX ?

**Comment by aufkrawall** [comment]
Yes.

**Comment by javashin** [comment]
Hello This Has Nothing To Do With Compton , I just Installed Opensuse Gnome With Intel xf86 ddx and xorg session the screen tearing on top of the videos is present so Xorg-server 1.20.5 broke the intel ddx driver we have to make a bugzilla for the  xorg-server and intel ddx devs thanks , for now the modesettting driver with glamor works fine with all the compositors EG, compton , mutter etc. closing this one here .

**Comment by javashin** [comment]
bug report here https://bugs.freedesktop.org/show_bug.cgi?id=110894 to any people who want the intel ddx driver fixed join me

**Comment by javashin** [comment]
Hi After Opening The Bug Everything Can Be Fixed Reverting The Commit 
commit 87491ced98705a14be2bb5a3ce7e41cb5ffc11d0
Author: Michel Dänzer <michel.daenzer@amd.com>
Date:   Mon Mar 25 12:32:48 2019 +0100

    present/scmd: Check that the flip and screen pixmap pitches match
    
    If they don't, flipping will result in corrupted display.
    
    Test case:
    
    * Run Xorg at 1920x1080 with no window manager
    * glxgears -geometry 2048x1080
    (Cherry picked from commit ef91da2757050652c724f6e674e8b1acf5d0cb31


on xorg-server 1.20 stable branch .

**Comment by rien333** [comment]
Does that mean the X.org developers are going to incorporate a fix?

**Comment by aufkrawall** [comment]
@rien333 
> Does that mean the X.org developers are going to incorporate a fix?

I think we'll have to wait for further feedback from Chris Wilson. Probably the faulty xserver commit will just get reverted, but that's just a guess.

**Comment by javashin** [comment]
i dont really know but , this affect directly the xf86-video-intel ddx directly and Chris Wilson is on it . 

yes what @aufkrawall  says .

**Comment by javashin** [comment]
for now 

git clone https://gitlab.freedesktop.org/xorg/xserver -b server-1.20-branch xorg-server-stable ; cd xorg-server-stable ; git revert 87491ced98705a14be2bb5a3ce7e41cb5ffc11d0 ; and compile

**Comment by FrancescoCappio** [comment]
Thank you. Fixed following your instructions. I hope the upstream bug will be fixed in next release so that we don't need to continue compiling manually

**Comment by aufkrawall** [comment]
There is now a MR to revert the commit:
https://gitlab.freedesktop.org/xorg/xserver/merge_requests/225

**Comment by rien333** [comment]
I downgraded to Xorg 1.20.4 to avoid the tearing, but 1.20.4 is now incompatible with the other Arch Linux upstream packages. For anyone else having this problem, just add the following to the xorg-server-git `PKGBUILD` file: 

```bash
prepare() {
  cd "${_pkgbase}"
  git revert --no-edit ef91da2757050652c724f6e674e8b1acf5d0cb31
}
```

This will revert the commit that is also mentioned in the Xorg merge request concerning this problem. Probably kinda obvious, but maybe I can help out a newbie.

**Comment by javashin** [comment]
This Being happening again on last tip of 1.20 branch from git
https://bugs.freedesktop.org/show_bug.cgi?id=110894

**Comment by javashin** [comment]
but i discovered that happen with xfwm4 from xfce4 4.14 which uses opengl now is not just related to compton

**Comment by aufkrawall** [comment]
Can't confirm, no tearing here with compton-git, xorg-git and xf86-video-intel-git. :)

**Comment by yshui** [comment]
@javashin Present *_is_* implemented in the experiemental xrender backend.

this tearing is likely to be a xorg bug, but sounds like they already fixed the one introduced in 1.20.5, so i am not very sure.

**Comment by rien333** [comment]
I also haven't experienced any tearing as of late, using the same git packages as @aufkrawall .

**Comment by javashin** [comment]
@aufkrawall  xorg-git git master or 1.20-branch ?

**Comment by javashin** [comment]
im aloso using xf86-video-intel-git

**Comment by javashin** [comment]
im compiling xorg-server master compton-git -b next and intel ddx git

**Comment by aufkrawall** [comment]
Sorry, didn't read carefully enough and missed the branch part.

**Comment by javashin** [comment]
ok

**Comment by javashin** [comment]
yes gone with everything from git thanks

**Comment by javashin** [comment]
@aufkrawall  have you used wayland sway gnome etc ? Xwayland is all broken in xorg-server-git

**Comment by javashin** [comment]
i was doing something wrong i cloned the xorg-server 1.20-branch  and compiled the code and now i got everything fine .
