### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by Fandekasp** [yshui/compton#185]
### Platform
Arch linux

### Environment
i3-gaps

### Compton version
v6.2

### Compton configuration:
```
cat .config/compton.conf 
backend = "glx";

#opacity-rule = [ "97:name *= 'Chrome'" ];
opacity-rule = [
    "95:class_g *= 'google-calendar-nativefier'",
    "95:class_g *= 'gmail-nativefier'",
    "95:class_g = 'Anki'"
];
```

### Request
Anki is a QT5 application, but after customizing the qt5 theme with qt5ct, I understood that Anki overrides the default theme to set its own grayish color.
I would like it to be solarized, hence I was wondering if it's possible to set some compton rule  to tint some color into another one. I couldn't figure this out by reading the manpage.

**Comment by yshui** [comment]
This is not relevant to compton.

The closest thing I could think of is: https://github.com/vn971/linux-color-inversion

**Comment by Fandekasp** [comment]
@yshui why wouldn't it be relevant to compton? This is a compositor, and the link you shared cites compiz, another compositor with a Color Filter plugin.

I'm probably not clear on the differences of compton versus compiz composition ...

**Comment by yshui** [comment]
compton is not responsible for what color scheme/theme is used by other applications.
