### ISSUE TITLE
experimental xrender - unredir crash

### ISSUE THREAD

**Issue by aufkrawall** [yshui/compton#189]
When I start vkquake in fullscreen, it tries some senseless resolution switch due to Intel driver not being able to properly handle the notebook's display. Compton then seems to crash only with `--unredir-if-possible = true`.
Attached is a crash dump and the Compton executable (debug symbols hopefully included).
[compton.zip](https://github.com/yshui/compton/files/3268523/compton.zip)

**Comment by yshui** [comment]
Triaged: resolution changed when compton is unredirected. `configure_root` didn't properly handle that case.

**Comment by yshui** [comment]
@aufkrawall  Should be fixed in `next`, can you confirm?

**Comment by aufkrawall** [comment]
@yshui I can confirm it's fixed, thank you. I once reported supposedly the same issue with fullscreen games running in wine, will test this case tomorrow. But I'm really confident it's fixed too, which would make the new xrender backend 100% stable and also otherwise free of hassle for me. :)

**Comment by yshui** [comment]
@aufkrawall good to hear

**Comment by aufkrawall** [comment]
@yshui The wine issue is fixed as well. :)

**Comment by aufkrawall** [comment]
@yshui The issue has reappeared with this commit:
https://github.com/yshui/compton/commit/eecee130b8d7f5b5e9bb735a1e7979c35177729f
