### ISSUE TITLE
Visual Artifacts on certain gtk window

### ISSUE THREAD

**Issue by BurhanDanger** [yshui/compton#19]
### Platform
Archlinux

### GPU, drivers, and screen setup
GPU, drivers, and screen setup: i915 (intel i5-4210U CPU @ 1.70GHz)
modsettings
i3 on xorg(xorg-server 1.20.1-1), mesa 18.2.2-1

### Compton version
v3-rc1-3-gf84336a ( compton-git 2:566_Next.1.gf84336a_2018.10.16-1 )

### Compton configuration:
N/A

### Current Behavior
On **Floating mode** in **i3** windows xp like Visual Artifacts can be seen in certain windows while moving.

### Preview
https://ptpb.pw/YjfZ (Bad audio warning)

**Comment by yshui** [comment]
@BurhanDanger Can you try `v3-rc2`?

**Comment by BurhanDanger** [comment]
It look ok with that.
