### ISSUE TITLE
i3lock on multiscreen leads to compton crash

### ISSUE THREAD

**Issue by philippera** [yshui/compton#196]
This crash only happens when I have an external screen connected to my laptop. It only happens when i3lock locks the screens.

### Platform
Arch Linux
hardware: Dell XPS 15 9530

### GPU, drivers, and screen setup
External screen: BenQ Ex3203R
Graphics drivers: bumblebee with Intel 4th Gen (i915 driver)/
Nvidia GeForce GT 750M (nvidia driver)
Configured side by side with xrandr
```
$ glxinfo -B      
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0x416)
    Version: 19.0.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

### Environment
i3-gaps

### Compton version
v6.2
```
$ compton --diagnostics                      
**Version:** v6.2

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /etc/xdg/compton.conf
```

### Steps of reproduction
1. Launch compton with no options
2. Lock screen with i3lock
3. Unlock screen -> compton is dead

### Expected behavior
Compton should still be running after the unlock

### Current Behavior
Compton dies on the second that i3lock is launched.

### Stack trace
error message when dying:
```
x_new_id FATAL ERROR ] We seems to have run of XIDs. This is either a bug in the X server, or a resource leakage in compton. Please open an issue about this problem. compton will die.
[1]    615 abort (core dumped)  ./compton
```

gdb stacktrace:
```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f61c167982f in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f61c0ebf940 (LWP 615))]
(gdb) backtrace
#0  0x00007f61c167982f in raise () from /usr/lib/libc.so.6
#1  0x00007f61c1664672 in abort () from /usr/lib/libc.so.6
#2  0x000056048cce2a8d in x_new_id.part.7.cold ()
#3  0x000056048ccfe6c8 in paint_one ()
#4  0x000056048ccfeb8e in paint_all ()
#5  0x000056048cce7385 in _draw_callback.isra.19 ()
#6  0x000056048cce7640 in draw_callback ()
#7  0x00007f61c23e3993 in ev_invoke_pending () from /usr/lib/libev.so.4
#8  0x00007f61c23e72dd in ev_run () from /usr/lib/libev.so.4
#9  0x000056048cce4025 in main ()
```

**Comment by yshui** [comment]
Did you left compton running for a long time?

This is probably #184

**Comment by philippera** [comment]
No it happens all the time no matter the scenario.

**Comment by philippera** [comment]
As additional information: I don t get this problem with the upstream code from chjj/compton

**Comment by yshui** [comment]
How long did you left the screen locked before this happens?

**Comment by philippera** [comment]
Anytime. Can be 5 seconds or many hours. Compton crashes exactly at the moment the screen is being locked (I checked in the logs with timestamps).

**Comment by yshui** [comment]
Can you paste your compton configuration here? Thanks.

**Comment by philippera** [comment]
I don t use any.

**Comment by philippera** [comment]
I just pulled the latest code change and after rebuilding it is now working!

**Comment by philippera** [comment]
Great thx a lot! Do you know what the problem could have been? :D

**Comment by yshui** [comment]
@philippera oh, you were using v6.2.

I am not sure, a lot has changed since v6.2.

Glad it's fixed :)
