### ISSUE TITLE
Compton pauses my animated wallpaper

### ISSUE THREAD

**Issue by Baitinq** [yshui/compton#199]
Hi, I am using compton with dwm on arch linux.

For the last days I have been trying to implement an animated wallpaper on my desktop by using gifview (gifview --animate -w root wallpaper.gif) but I have noticed every I start compton the wallpaper freezes. Is there anyway to prevent this, I have looked in the manual page but I couldnt find anything regarding this. Thanks a lot.

**Comment by yshui** [comment]
compton cannot work with applications that draws on the root window.

**Comment by Banbeucmas** [comment]
I used something similar, hope it helps

`#!/bin/bash

_screen() {
    xwinwrap -ov -g $1 -- mpv --fullscreen\
        --on-all-workspaces \
        --no-stop-screensaver \
        --loop-file --no-audio --no-osc --no-osd-bar -wid WID --quiet \
        "$2" --background="$3" --video-zoom="$4" &
}

killall xwinwrap

sleep 0.5

for i in $( xrandr -q | grep ' connected' | grep -oP '\d+x\d+\+\d+\+\d+')
do
    _screen $i "$1" "${2:-#000000}" "${3:-0}"
done`

**Comment by Baitinq** [comment]
Thank you @Banbeucmas ive tried and it works, im just confused about the reasoning of why that script works but gifsicle doesnt. Doesnt compton simply not support working with applications that draw on the root window?

**Comment by yshui** [comment]
@Baitinq gifsicle draws on the root window, which is not supported. xwinwrap puts a window into the background
