### ISSUE TITLE
Ask chjj to be the new maintainer of compton

### ISSUE THREAD

**Issue by Anthony25** [yshui/compton#21]
Hi @yshui,
As your fork seems to be really active and fixes a lot of bugs and performance issues that compton has, did you have asked @chjj to be the new maintainer of compton?

If you want to continue to maintain compton in the near future, it would be really beneficial for the community, as his repo has more users than yours.

Thanks a lot for your work!

**Comment by yshui** [comment]
@Anthony25 One good thing of the open source community is that you don't need someone's permission to become the "maintainer" of something ;)

**Comment by Anthony25** [comment]
Of course, but it wasn't the meaning on my issue. Here you are in a situation where all distributions base their packaging on the @chjj repository, which already has a quite big community. I can't say for sure that @chjj would accept to give you his repository, but as it seems to be unmaintained, I doubt he wouldn't regarding the work you already did on compton.

I don't really understand your answer, to be honest, so I'm really sorry if my 1st comment was not clear enough. I didn't open this issue because I thought that you can't fork something without asking the maintainer, I did to ask you if already asked @chjj to take his repository instead of continuing to work on your fork. It's just a visibility/community related question (plus keeping the opened/closed issues, etc.), not about some rights or legitimacy regarding compton.
However, I would totally understand if you have your reasons to continue on your fork.

Thanks again for your work

**Comment by yshui** [comment]
@Anthony25 I got your point, but let me ensure you there is no need to do that. Some distros have already picked up this repo, among them, most notably, is Arch Linux. And I fully expect others to follow suit.

**Comment by Anthony25** [comment]
Ok, thanks for you answer ;)

If I can help to contribute, I certainly will.
