### ISSUE TITLE
Using experimental backends and xr_glx_hybrid segfaults

### ISSUE THREAD

**Issue by rien333** [yshui/compton#210]
If I use the flags `--experimental-backends` and `--backend xr_glx_hybrid` together compton segfaults. I'm not sure if this combination is even supported, but it could be a bug. 

### Platform
```
$ uname -mor
5.2.3-arch1-1-ARCH x86_64 GNU/Linux
```
### GPU, drivers, and screen setup

Monitor: Laptop Monitor
GPU: Intel UHD Graphics 620 (Kabylake GT2)
Driver: ~~xf86-video-intel-git~~ Modesetting (for some reason my intel driver fails without error)

```
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
    Version: 19.1.3
    Accelerated: yes
    Video memory: 3058MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
My wm is bspwm, I have no no DE.

### Compton version
Both the newest HEAD and v7.

### Steps of reproduction

1. 
```
$ compton --experimental-backends --config /dev/null --backend xr_glx_hybrid --show-all-xerrors
Segmentation fault (core dumped)
```

### Expected behavior

Compton starts or at least outputs why the combination of `--experimental-backends` and `--backend xr_glx_hybrid` doesn't work.

### Current Behavior

Compton crashes/segfaults. For some reason `xr_glx_hybrid` works best of all backends when not running with the `--experimental-backends` flag.

**Comment by aufkrawall** [comment]
Regarding failed loading of xf86-video-intel-git for you: Have you compiled xorg-server-git after compiling xf86-video-intel-git? When there is an ABI change, the driver needs to be compiled against that new xorg-server as well.

**Comment by rien333** [comment]
> Regarding failed loading of xf86-video-intel-git for you: Have you compiled xorg-server-git after compiling xf86-video-intel-git? When there is an ABI change, the driver needs to be compiled against that new xorg-server as well.

Yeah I did struggle with ABI versions initially, but I fixed it using the method you suggested. Turns out, I can't really get the intel driver to load properly (without a clear error), even after having matching ABI versions. 

Anyway, Xorg.0.log shows that I fall back to modesetting, so it's highly likely that my initial observation that I was using xf86-video-intel-git was wrong. In the mean time, I have downgraded to xorg 1.20.4, where the issue is still present.

**Comment by yshui** [comment]
You are correct that xr_glx_hybrid is not supported. Nonetheless compton shouldn't crash.

**Comment by yshui** [comment]
@rien333 Fix pushed

**Comment by rien333** [comment]
Works fine!

**Comment by rien333** [comment]
Works okay, but note that the error is not visible when running compton with `-b`.

**Comment by yshui** [comment]
@rien333 that's expected. the error is not visible is because the error happens after the daemonization, the warnings you saw are generated before that.

to see all the errors when using `-b`, you have to use a `--log-file`.
