### ISSUE TITLE
Dbus interface stopped working after 7.0 release

### ISSUE THREAD

**Issue by kurnevsky** [yshui/compton#219]
### Platform

Arch Linux

### GPU, drivers, and screen setup

xf86-video-intel 2.99.917+865+g60022507
mesa 19.1.3

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0xa16)
    Version: 19.1.3
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

### Environment

xmonad

### Compton version

**Version:** v7.1

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/kurnevsky/.config/compton.conf

### Drivers (inaccurate):

Intel

### Compton configuration:

https://github.com/kurnevsky/dotfiles/blob/master/.config/compton.conf
https://github.com/kurnevsky/dotfiles/blob/35447d47922cb0528aa7ee098a762324ac1bc2e4/.xinitrc#L30

### Steps of reproduction

dbus-send --dest=com.github.chjj.compton._0 / com.github.chjj.compton.win_set uint32:[windows_id] string:invert_color_force uint16:1

### Expected behavior

The window colors should be inverted.

### Current Behavior

Nothing happens.

**Comment by yshui** [comment]
Use:

```
dbus-send --print-reply --dest=com.github.chjj.compton._0 / com.github.chjj.compton.win_set uint32:[windows_id] string:invert_color_force uint32:1
```
Please do note the dbus interface doesn't have a stable interface at the moment.
