### ISSUE TITLE
compton-convgen needs a manpage

### ISSUE THREAD

**Issue by wxl** [yshui/compton#225]
It doesn't need to be particularly fancy, but a manpage for compton-convgen would be great and would keep Lintian from complaining about `binary-without-manpage`.

I'd drum something up based on the default arguments, but I'm not really qualified to write an adequate description.

---

BTW, an aside: Lintian also complains about the language-specific extension.  Since you have it shebanged, it's really not necessary…

**Comment by yshui** [comment]
compton-convgen is being phased out. If you use `--experimental-backends` you can use the much nicer blur configuration syntax as described [here](https://github.com/yshui/compton/blob/next/man/compton.1.asciidoc#blur)
