### ISSUE TITLE
Windows sometimes disappear

### ISSUE THREAD

**Issue by TiZ-EX1** [yshui/compton#231]
### Platform
Xubuntu 18.04 amd64

### GPU, drivers, and screen setup
Intel HD Graphics 530, two identical monitors both connected via displayport, side-by-side via xrandr.

```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2)  (0x1912)
    Version: 19.0.8
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.0.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
XFCE 4.12ish (Xubuntu 18.04 pulls some 4.13 components). xfwm4, with its own compositor of course disabled.

### Compton version
```
**Version:** v7.3

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/tiz/xdg/config/compton.conf

### Drivers (inaccurate):

modesetting
```

### Compton configuration:
I start compton with --experimental-backends.

```
# Basic config
backend = "glx";
dbus = true;
vsync = true;
detect-client-opacity = true;

# Fading
fading = true;
fade-delta = 5;
fade-in-step = 0.02;
fade-out-step = 0.02;
no-fading-openclose = false;

# Shadow
shadow = true;
shadow-opacity = 0.65;
shadow-radius = 7
shadow-offset-x = -7;
shadow-offset-y = -6
shadow-exclude = [
	"name = 'Notification'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'dnd'",
	"class_g = 'Conky'",
	"class_g ?= 'notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
]

# Opacity / Blur
opacity-rule = [
	"90:window_type = 'popup_menu'",
	"90:window_type = 'dropdown_menu'"
]
blur-background = true;
blur-background-frame = true;
blur: {
	method: "box";
	size: 3;
	deviation: 5.0;
}
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'dnd'",
	"class_g = 'Conky'",
	"_GTK_FRAME_EXTENTS@:c"
]
```

### Steps of reproduction
Haven't figured out any way to reliably reproduce it, sorry.

### Expected behavior
Windows don't randomly disappear.

### Current Behavior
Sometimes windows will randomly disappear, seemingly in response to nothing at all. You can't get them to show back up even by switching windows; it seems like you have to get the window's content to change somehow.

### Stack trace
None yet

### Other details
It seems like I can get it to happen reliably with DBeaver Community Edition, an Eclipse platform app.

I was mainly using experimental backends to get the new blur config syntax, but I'm only using 3x3box so I don't *really* need it. I'll see if this behavior persists on the old backend.

**Comment by yshui** [comment]
can you attach a log file captured when the problem happens? (remember to set `--log-level=debug`).

if you can somehow capture a apitrace of the problem it would be really helpful

**Comment by TiZ-EX1** [comment]
I haven't been able to reproduce this issue on either backend. Sorry about that.

**Comment by yshui** [comment]
@TiZ-EX1 feel free to reopen if you start seeing it again.
