### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by anonaii** [yshui/compton#24]
### Platform
Kubuntu Desktop 18.04 amd64

### Expected behavior
After installing all the dependencies, it would take a little bit and compile fine

### Current Behavior
It spits out the this [error](https://pastebin.com/raw/daqzBnfx)

**Comment by yshui** [comment]
It seems to compile fine. Were you not able to find the binary?

**Comment by anonaii** [comment]
Oh wait, I'm dumb. I thought the warnings were straight up errors, plus the binary was in build/src rather than build/bin
