### ISSUE TITLE
Enable use-damage by default

### ISSUE THREAD

**Issue by Isopod** [yshui/compton#242]
I don't know when exactly this started, but Compton became really laggy and stuttery for me over the last year or so. It had been bothering me for a while, but I didn't know what caused it. Yesterday I finally found the option that fixed it: Setting use-damage to true. Now I get the full 60 fps again, while before it must have been something like 30 and was very inconsistent. I think this option should be set by default since it makes such a massive difference.

I use an Intel HD 4600 with two monitors and i3wm.

**Comment by aufkrawall** [comment]
I agree. Even if there still were a few corner cases, having it enabled by default would surely be helpful to generate feedback for them.

**Comment by yshui** [comment]
OK, I don't have a strong objection for this.

**Comment by liskin** [comment]
I was just wondering, are none of you folks experiencing visual glitches with `use-damage`? Like https://github.com/yshui/compton/issues/237?

**Comment by aufkrawall** [comment]
I haven't noticed such an issue inside my Plasma sessions yet. I can reproduce a "looks like tearing" issue in context menus when playing a video, but even Windows DWM show this.

**Comment by Isopod** [comment]
I have not experienced any glitches. But I am using a very basic config, no blurring or shadows or anything like that.
