### ISSUE TITLE
Experimental backends: Performance very bad in VirtualBox

### ISSUE THREAD

**Issue by scrouthtv** [yshui/compton#253]
Using the ```--experimental-backends``` flag on the newest version in a VM, I get very bad performance:

![comptonlaggy](https://user-images.githubusercontent.com/23227405/67161960-c986ad00-f35f-11e9-8661-f6e73022ae72.gif)
(In this example I first try to move a window around with ```compton --experimental-backends```, in my tests after some time it would move around but not fast at all. Then I disable compton and it works again)

![image](https://user-images.githubusercontent.com/23227405/67161673-02715280-f35d-11e9-938a-c3205386b77a.png)
(2D Acceleration works only for Windows as far as I know)

I have the guest additions installed & am using the ```xf86-video-vmware``` driver.

**Comment by yshui** [comment]
@scrouthtv try disabling the blur.

**Comment by scrouthtv** [comment]
@yshui way better. the performance with kernel blur on glx backend is just as bad...

**Comment by yshui** [comment]
@scrouthtv which is not that surprising as VirtualBox probably doesn't have good 3D acceleration

**Comment by rafay99-epic** [comment]
So Brother, if I use real hardware and not virtual machine then the performance would be better. Right?
