### ISSUE TITLE
GTK window on KDE doesnt update when focus is lost

### ISSUE THREAD

**Issue by clapbr** [yshui/compton#28]
### Platform
Manjaro Linux x86_64 unstable
### GPU, drivers, and screen setup
AMD RX 580 with latest mesa-git
### Environment
KDE Plasma with Compton as compositor
### Compton version
git-master and git-next have the issue
v2.0-2 (from official manjaro repo) doesn't
### Compton configuration:
Tried switching every config possible and bug still triggers, even with default everything
### Steps of reproduction
Open any GTK application under KDE Plasma, then open any other window that covers it. If you switch back to GTK app it's window stay partly blank/unrefreshed until you move it.

### Other details
https://www.youtube.com/watch?v=trB5aqFAMOM&feature=youtu.be - video of reproduction
I don't show in the video, but if I hover the cursor slowly over the taskbar, wait the thumbnail to appear and then click again to switch the bug doesn't trigger at all.

**Comment by yshui** [comment]
Does compton print out anything when you do that?

**Comment by clapbr** [comment]
> Does compton print out anything when you do that?
nope, 0 errors
> Very interesting... BTW I'm pretty sure Chromium is GTK too, and this doesn't happen to that?
Electron-based apps and chromium seems unaffected. They use GTK indeed, but they are a ultra special case considering how complex their rendering engine is.

> And this does not happen to KDE applications? What if you test (if you have time) this with GTK and KDE applications on GNOME?
All interactions between KDE look normal. I use a few simple GTK3 apps and they all have the issue. I can test gnome soon but I am a bit busy atm.

**Important update:** Not sure why when I tested a couple days ago both backends (glx vs xrender) had the issue or maybe I didn't clear the conf properly. Just recompiled the next branch and now **I can consistently reproduce on xrender but glx looks fine.**

**Comment by yshui** [comment]
> I can consistently reproduce on xrender but glx looks fine.

This is a very useful information, thanks.

**Comment by yshui** [comment]
I can reproduce this locally now.

> but if I hover the cursor slowly over the taskbar, wait the thumbnail to appear and then click again to switch the bug doesn't trigger at all.

It does trigger, it's just when the preview window closes, the gtk window is refreshed.

**Comment by clapbr** [comment]
> It does trigger, it's just when the preview window closes, the gtk window is refreshed.

Hmm true, just tested it.

Btw, maybe you can bisect it against the version that doesnt show this bug (v2), not familiar with the code to know how much changed since that.

**Comment by yshui** [comment]
@clapbr The head of `next` should fix this problem. Can you test?

**Comment by clapbr** [comment]
Fixed indeed. Thanks a lot, that was fast as the new compton!
