### ISSUE TITLE
Screen becomes empty

### ISSUE THREAD

**Issue by ChrisLahaye** [yshui/compton#30]
Thank you for your great work. Please let me know if I can help by providing any additional information or performing tests.

### Platform
Linux arch 4.18.16-1-ck-skylake #1 SMP PREEMPT Sat Oct 20 08:37:58 EDT 2018 x86_64 GNU/Linux

### GPU, drivers, and screen setup
```
130 chris@arch ~/dotfiles/compton (git)-[master] % glxinfo | grep -i vendor                  
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center

chris@arch ~/dotfiles/compton (git)-[master] % lspci -k | grep -EA3 'VGA|3D|Display'     :(
lspci: Unable to load libkmod resources: error -12
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
        DeviceName: Onboard IGD
        Subsystem: Hewlett-Packard Company HD Graphics 530
        Kernel driver in use: i915
```

### Environment
XFCE4

### Compton version
v3 and v3-rc2-16-g06d8792

### Compton configuration:
Default configuration and /etc/xdg/compton.conf.example
Tried any combination of options

### Steps of reproduction
1. compton --config /dev/null

### Expected behavior
Windows to be visible

### Current Behavior
Screen becomes empty

### Other details
https://youtu.be/WrTd4yi8FcA

I remember having this problem on your fork a long while ago, then it was fixed for a while, now it is back again.

**Comment by yshui** [comment]
Have you tried the glx backend?

**Comment by yshui** [comment]
OK, there seems to be some problem in the window stacking code. I will look into it.

**Comment by ChrisLahaye** [comment]
> Have you tried the glx backend?

Yes, same results

> OK, there seems to be some problem in the window stacking code. I will look into it.

Thank you, well appreciated

**Comment by yshui** [comment]
What happens when you have more windows open? What window manager are you use? (I was assuming xfwm4).

**Comment by ChrisLahaye** [comment]
> What happens when you have more windows open? What window manager do you use? (I was assuming xfwm4).

I am indeed using xfwm4. I get the same results independent of the number of windows or screens. 

In the screen recording, the first part is without configuration, here it disappears instantly (same as with the shipped configuration sample). The second part is with my own configuration (https://gist.github.com/ChrisLahaye/1f11ce1d1748889064df1010254984ce), here it disappears when opening an overlay (plank, notification) or menu (context menu, whisker).

**Comment by yshui** [comment]
I cannot reproduce this on a new xfce4 install. So I'm afraid you will have to help me debugging this issue.

Can you run `xwininfo -root -tree` before running `compton --config /dev/null`, and paste the output here? Please also include compton's output.

**Comment by ChrisLahaye** [comment]
Output of `xwininfo -root -tree`: [tree.txt](https://github.com/yshui/compton/files/2525548/tree.txt)
Output of `compton --config /dev/null`: `restack_win(0x03e00eea, 0x02e08277): Failed to found new above window.` and then the screen becomes empty.

**Comment by yshui** [comment]
A wild guess, but if you kill `xfce4-panel` (which will kill your panel) before starting `compton`, does it still happen? 

Also what happens if you kill `redshift` before starting `compton`?

**Comment by ChrisLahaye** [comment]
Same results with xfce4-panel and redshift killed.

**Comment by ChrisLahaye** [comment]
[log.txt](https://github.com/yshui/compton/files/2527223/log.txt)
As attachment the log. Thanks again

**Comment by yshui** [comment]
@ChrisLahaye from the log file I can see compton did try to paint something, somehow nothing is painted on screen....

You said this happen on GLX as well, right? So if you are familiar with [apitrace](https://github.com/apitrace/apitrace), could you use that to capture a trace of compton with the GLX backend? (It will capture all window content, so don't open too many windows to minimize the size of the capture).

**Comment by ChrisLahaye** [comment]
[compton-next.trace.log](https://github.com/yshui/compton/files/2529542/compton-next.trace.log)
[compton-debug.trace.log](https://github.com/yshui/compton/files/2529543/compton-debug.trace.log)

As attachment the traces. Did my best to minimize the size.

**Comment by yshui** [comment]
Sorry, do you happen to capture `compton`'s output when you captured these traces?

**Comment by yshui** [comment]
If you are going to do the capture again, could you do the following things at the same time:

* Run under `apitrace` and get the trace
* `--config /dev/null --backend glx`
* Build from `debug-30` (it is updated with a few more commits)
* Capture the outputs of `compton`

Thanks!

**Comment by ChrisLahaye** [comment]
`apitrace trace compton --config /dev/null --backend glx > output.log`
[output.txt](https://github.com/yshui/compton/files/2531987/output.txt)
[compton.trace.txt](https://github.com/yshui/compton/files/2531988/compton.trace.txt)

Thanks again for your efforts

**Comment by yshui** [comment]
No, thank you for sticking with me.

But sorry, I wasn't clear enough. You need to capture the output with `>output.log 2>&1`, otherwise you loss everything printed on stderr.

**Comment by ChrisLahaye** [comment]
Oops

`apitrace trace compton --config /dev/null --backend glx 2>&1 > output.log`
[output.txt](https://github.com/yshui/compton/files/2533391/output.txt)
[compton.trace.txt](https://github.com/yshui/compton/files/2533392/compton.trace.txt)

**Comment by yshui** [comment]
@ChrisLahaye Sorry, but the order of redirection is important. It has to be `>output.log 2>&1`, not `2>&1 > output.log`

**Comment by ChrisLahaye** [comment]
Ugh didn't know the difference, should have just followed the instructions :+1: 

`apitrace trace compton --config /dev/null --backend glx >output.log 2>&1`
[compton.trace.txt](https://github.com/yshui/compton/files/2534282/compton.trace.txt)
[output.txt](https://github.com/yshui/compton/files/2534283/output.txt)

**Comment by ChrisLahaye** [comment]
@yshui cool thanks, let me know when you have updated the branch

**Comment by yshui** [comment]
I updated the branch. This time you *don't* need to run `apitrace`

**Comment by ChrisLahaye** [comment]
[output.log.txt](https://github.com/yshui/compton/files/2538403/output.log.txt)

**Comment by yshui** [comment]
Hmm, do you have any idea why all your window is considered transparent. Can't seems to find a reason why compton would do that...

**Comment by ChrisLahaye** [comment]
No idea, I generated the log and tried without any programs running. I will try later with another GTK theme, maybe the theme uses transparency?

**Comment by yshui** [comment]
I don't think that is the case. This will be much easier if I can reproduce this bug, but now I guess I will have to add more debug prints.

I am going to implement proper logging and stuff so future bug reporters won't need to go through this again.

**Comment by ChrisLahaye** [comment]
Checked if I used any transparency which was not the case and changing themes also didn't work.

**Comment by yshui** [comment]
@ChrisLahaye I pumped the `debug-30` branch with more debug messages. Please give it a run when you got time.

**Comment by ChrisLahaye** [comment]
@yshui 

`compton --config /dev/null --backend glx >output.log.txt 2>&1`
[output.log.txt](https://github.com/yshui/compton/files/2542405/output.log.txt)

**Comment by yshui** [comment]
You can either remove things like `-ffast-math` or `-Ofast` from your CFLAGS, or you can try the current head of `next`. That should fix you problem.

**Comment by ChrisLahaye** [comment]
@yshui you are right, my compiler options enabled fast math, adding `-fno-fast-math` fixed it. How did you figure this out? Thanks a lot though I really appreciate your efforts to help me and the work you are doing.

**Comment by yshui** [comment]
@ChrisLahaye So in the logs I see windows get opacity of `nan` even if I have `!isnan` guards in place. And that is usually related to `-ffast-math`.
