### ISSUE TITLE
Message is printed repeatedly: 'delayed_draw_callback(): 0.000000'

### ISSUE THREAD

**Issue by xyproto** [yshui/compton#31]
Hi,

I'm maintaining the compton package for Arch Linux, and someone reported this bug: https://bugs.archlinux.org/task/60647

> I have a Nvidia card and am using the Nouveau driver and i3wm. compton-2.0-2 runs well on my system.
>
> When running compton 3.0-1 in an X session (i3wm), the screen flickers erratically and the system is unusable.
>
> The following message is printed repeatedly: 'delayed_draw_callback(): 0.000000'
> 
> Additional Information:
> - Kernel: 4.18.16-arch1-1-ARCH
> - Package Version: 3.0-1
> - Steps to reproduce: Start compton

Feature request:

Could the `delayed_draw_callback()` messages be less verbose, or silenced?

The default Arch Linux configuration for compton does not trigger the message, but many people will upgrade compton and continue to use their old configuration which does trigger this behavior.

**Comment by yshui** [comment]
This is fixed in `next` branch.

For time being I would suggest you to not use `swopti`. Sorry for the inconvenience.

**Comment by xyproto** [comment]
And thanks for maintaining compton! :)

**Comment by yshui** [comment]
@xyproto Hmmm. The bug report is a bit confusing. Is he complaining about the flickering (sounds like a bug), or is he complaining about the debug message?

The latter should definitely be solved by disabling `swopti`, the former needs more investigation....

**Comment by xyproto** [comment]
When testing here, the debug message is gone and things look ok (at least to me) when using the next branch.

The experiences are guaranteed to differ depending on the system configuration, though.

**Comment by yshui** [comment]
@xyproto it would be really nice if you can get him to file a bug here for the flickering problem, so we can get more details on that.
