### ISSUE TITLE
Opacity-rule doesn't work

### ISSUE THREAD

**Issue by xversion1** [yshui/compton#38]
// The template below is for reporting bugs. For feature requests and others, feel free to delete irrelevant entries.

### Platform
Arch Linux

### GPU, drivers, and screen setup
Intel, don't know, two monitors configured side-by-side with xrandr

### Environment
Openbox

### Compton version
// You can run `compton --version` to get that
v3-rc2-18-gc0d7f9d

### Compton configuration:
```
// Paste your configuration here
# Shadows
# -------
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
clear-shadow = true;
shadow-radius = 7;
shadow-offset-x = -8;
shadow-offset-y = -4;
shadow-opacity = 0.7;
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'xfce4-notifyd'",
    "name *= 'VLC'",
    "name *= 'albert'",
    "name *= 'compton'",
    "name *= 'Chromium'",
    "name *= 'Chrome'",
    "class_g = 'Conky'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'"
];

# Opacity
# -------
menu-opacity = 0.9;
frame-opacity = 0.9;
inactive-opacity = 0.9;
active-opacity = 1.0;
#inactive-opacity-override = true;
opacity-rule = [ 
	"100:name *?= 'vlc'",
	"100:class_g *= 'Xfce4-terminal'", 
	"100:class_g *= 'gthumb'" 
];

# Other
# -----
paint-on-overlay = true;

# Window type settings
# --------------------
wintypes:
{
    tooltip =
    {
        shadow = false;
        opacity = 0.95;
        focus = true;
    };
};
```

### Steps of reproduction
// If you can reliably reproduce this bug, please describe the quickest way to do so
// This information will greatly help us diagnosing and fixing the issue.

1.
2.

### Expected behavior
inactive-opacity doesn't apply on certain apps' windows
### Current Behavior
Every inactive windows are applied transparent.
### Other details
// If your problem is visual, you are encouraged to record a short video when the problem occurs and link to it here.

**Comment by yshui** [comment]
I can't seem to reproduce this issue. I tried your config, start vlc and then switch to another window, vlc is totally opaque.

**Comment by xversion1** [comment]
> I can't seem to reproduce this issue. I tried your config with openbox, start vlc and then switch to another window, vlc is totally opaque.

Could you try gthumb?

**Comment by yshui** [comment]
@xversion1 You should use `100:class_i *= 'gthumb'` or `100:class_g *= 'Gthumb'` or `100:class_g *?= 'gthumb'`
