### ISSUE TITLE
clear-shadow is removed as an option, and is always enabled now

### ISSUE THREAD

**Issue by WernerFP** [yshui/compton#45]
### Platform
Arch Linux, Kernel: 4.18.16-arch1-1-ARCH x86_64

### GPU, drivers, and screen setup
NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 410.66 

### Environment
Openbox 3.6.1

### Compton version
v2/v3
### Issue
Removing this option has an unpleasant side effect.
### Compton configuration snippet:
 ```
# Firefox dropdown menus: proper shadow just without clear-shadow
clear-shadow = false;
 ```
### Expected behavior (v2)
![clear-shadow-false](https://user-images.githubusercontent.com/22373662/48159888-b60d3e00-e2d6-11e8-97d9-6202ffc82712.png)
### Current Behavior (v3)
![clear-shadow-true](https://user-images.githubusercontent.com/22373662/48159793-7a727400-e2d6-11e8-9e66-616e0b54a6f8.png)
A workaround is possible…
 ```
wintypes:
{
  dropdown_menu = { shadow = false; };
};
 ```
... but I'd be pleased if we got the clear-shadow option back.

**Comment by yshui** [comment]
The proper solution is to handle shaped window properly. That will hopefully be implemented soon.

**Comment by yshui** [comment]
Looks like the firefox menu does not set its shape. I reported this to upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1505588

**Comment by WernerFP** [comment]
Thank you yshui. It's like you said - clear-shadow has a negative effect on semi-transparent windows (IMHO acceptable with soft shadows):
```
###########
# Backend #
###########
backend = "glx";
paint-on-overlay = true;       # most other compositors paint on the overlay window nowadays
glx-no-stencil = true;         # usually increases performance quite significantly (around 15%)
glx-no-rebind-pixmap = true;   # useful if you have a window with content rapidly changing
glx-copy-from-front = false;   # worst glx-swap-method
glx-swap-method = 3;           # use a triple-buffer (2 = double-buffer, default is undefined)
vsync = "opengl-swc";          # opengl-swc/opengl-mswc: buffer-swap VSync methods
# unredir-if-possible = true;  # true -> maybe flickering or tearing fullscreen

##########
# Shadow #
##########
shadow = true;                # enabled client-side shadows on windows.
no-dock-shadow = true;        # avoid drawing shadows on dock/panel windows.
no-dnd-shadow = true;         # don't draw shadows on DND windows.
# Firefox dropdown menus: proper shadow just without clear-shadow
clear-shadow = false;          # v3+ : clear-shadow is removed as an option, and is always enabled now
shadow-radius = 12             # blur radius - (default 12) - center xy = radius * 1.5 negative value
shadow-offset-x = -18;         # the left offset for shadows (default -15)
shadow-offset-y = -14;         # the top offset for shadows (default -15)
shadow-opacity = 0.4;
detect-rounded-corners = true;
```
`clear-shadow = false` is not ideal and `clear-shadow = true` is not ideal either. So I plead for retention of the individual option until there is a better solution.

By the way, many thanks for your work on compton!

**Comment by yshui** [comment]
@WernerFP I want to at least make `clear-shadow` a `wintypes` option, but I don't want to risk releasing it in v4, so you might need to stay on `next` for a bit.

I will get to it ASAP.

**Comment by WernerFP** [comment]
Just to finish off:
`full-shadow` works very well on my computers and I can't see any side effects.
Only the Firefox toolbar menu "_Bookmarks Menu_" is a different window type: `popup_menu` instead of `utility`.
```
wintypes: {
    utility = { full-shadow = true; };
    popup_menu = { full-shadow = true; }; # Firefox Bookmarks Menu
};
```
