### ISSUE TITLE
Steam wine systray menu doesn't show up with compon enabled

### ISSUE THREAD

**Issue by clapbr** [yshui/compton#53]
~ >>> inxi -bM                                                                                                                                                     [1]
System:    Host: mjb Kernel: 4.19.2-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.14.3 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Gigabyte product: N/A v: N/A serial: <root required> 
           Mobo: Gigabyte model: B150M-D3H DDR3-CF v: x.x serial: <root required> UEFI: American Megatrends v: F6 
           date: 03/14/2016 
CPU:       Quad Core: Intel Core i5-6400 type: MCP speed: 3302 MHz min/max: 800/3300 MHz 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.3 driver: amdgpu unloaded: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.27.0 4.19.2-1-MANJARO LLVM 7.0.0) 
           v: 4.5 Mesa 19.0.0-devel (git-7e9fc11ff8) 
Network:   Device-1: Intel Ethernet I219-V driver: e1000e 
Drives:    Local Storage: total: 1.59 TiB used: 86.70 GiB (5.3%) 
Info:      Processes: 199 Uptime: 34m Memory: 15.60 GiB used: 1.31 GiB (8.4%) Shell: zsh inxi: 3.0.27

### Compton version
v4-rc1-14-gf834cf2

### Compton configuration:
--backend=glx --vsync=opengl

### Steps of reproduction
1. Open Steam under wine on Plasma with compton running
2. Click or right-click the systray icon to open Steam menu.

### Expected behavior
Menu is showed correctly, as it does with no compositor or in other DEs.

### Current Behavior
Nothing happens.

### Other details
It happens only on Plasma for some reason, not in xfce or gnome. When compton is on, the icon itself goes from ugly (black background) to beautiful but it stops working and if you close steam without exiting it stays on systray forever until you kill wine.

**Comment by yshui** [comment]
Sounds more like a plasma problem...

> if you close steam without exiting it stays on systray forever

This is expected behavior of steam.

**Comment by clapbr** [comment]
Yeah, its plasmas fault, this can be closed. Guys on reddit helped a lot https://www.reddit.com/r/wine_gaming/comments/9y3lpk/wine_steam_on_kde_plasma_no_systray_menu/
thanks
