### ISSUE TITLE
feature request: Implement an option to ignore certain overlay windows when screen is not redirected

### ISSUE THREAD

**Issue by aufkrawall** [yshui/compton#58]
`unredir-if-possible` shows brief flickering when switching compositing on and off. This is harmless when exiting or entering to a fullscreen window e.g. via alt + tab.

But when an overlay of the desktop environment is shown while in fullscreen, e.g. KDE Plasma volume slider evoked via a keyboard button, the brief flickering is very obvious and ugly.

The user may find it's the lesser evil to lose transparency functionality in such situations instead of having to experience flicker. For such reasons, please implement an option to turn off transparency functionality so that compositing remains turned off when an overlay element is rendered on top off a fullscreen window with `unredir-if-possible = yes` .

If the user wants to retain transparency functionality for fullscreen windows, they can also use `unredir-if-possible-exclude`, which is better anyway as it prevents stutter when the overlay appears.

**Comment by yshui** [comment]
I changed the title to better reflect what I think you want.

My plan is to add a wintype option that lets compton ignore certain windows (meaning: not redirect the screen again just for them, but they will still pop up normally) when the screen is not redirected.

**Comment by yshui** [comment]
@aufkrawall Can you try this: https://github.com/yshui/compton/pull/60? Or branch `redir-ignore`.

**Comment by aufkrawall** [comment]
Thanks!
I added it to my config and Compton didn't complain about an unkown entry. Though Wine DXVK games still flicker in fullscreen when an opaque volume OSD is rendered on top.
I also tried starting Compton with `--redir-ignore`, but it doesn't recognize this option.

**Comment by yshui** [comment]
@aufkrawall Can you make sure you added `redir-ignore` to the correct `wintypes`? You can find out by using `xprop` on the OSD window.

BTW, I updated the branch, you might need to checkout again.

**Comment by aufkrawall** [comment]
Could you please provide me with a config template? I tried to extract what I need from `compton.1.asciidoc` but failed.

**Comment by yshui** [comment]
Assuming the osd window is of type `utility`, you need to put

```
wintypes: {
    utility: {redir-ignore=true;}
}
```

Into your config file.

Is the description in man page confusing?

**Comment by aufkrawall** [comment]
Thanks a lot, `wintype: normal` works. :+1: 

I'm not really good in anything script alike, so I probably can't judge if the man page is confusing. I'll reread it and try to comprehend it better with the example you provided. I think it wouldn't hurt to frequently have a few concrete examples in between.

**Comment by yshui** [comment]
@aufkrawall Hmm, are you sure `normal` is the right type? Because setting `redir-ignore` on `normal` might cause the screen to stay unredirected even when it shouldn't

**Comment by aufkrawall** [comment]
Yes, I tried every category and only `normal` worked. Probably non-optimal declaration of the KDE Plasma window?
The volume slider "window2 btw. can't be grabbed via xprop, cursors clicks right through it.

(I personally prefer to make a fullscreen window always stay unredirected anyway unless the application or Compton config tells the compositor otherwise.)

**Comment by yshui** [comment]
> Probably non-optimal declaration of the KDE Plasma window?
Might be the case.

> The volume slider "window" btw. can't be grabbed via xprop, cursor clicks right through it.
Hmm, looks like xprop is not the best tool for this. Might be a good idea to create a specialize tool for generating matching rules and getting window type...

**Comment by yshui** [comment]
@aufkrawall I will merge that and close this for now. If anything unexpected comes up, fell free to reopen.
