### ISSUE TITLE
Disabling blur radius does not produce sharp shadows.

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [yshui/compton#61]
I set my blur radius to '0' and I still have fizzy edges to the shadows. Is there any way to make them sharp like xcompmgr?

**Comment by yshui** [comment]
I looked into the shadow code, and found that it has been there since forever (i.e. since original xcompmgr days). Apparently nobody has ever had a problem with it being wrong (yes, if radius = 0, the shadow should be sharp) until now.

Looking into how to fix this.

**Comment by yshui** [comment]
@dubbadubbadubbacha the latest `next` branch should fix this, can you test?

**Comment by dubbadubbadubbacha** [comment]
Hi, thanks. I tried building on FreeBSD but I get:

<code>
src/meson.build:1:0: ERROR:  C library 'ev' not found
</code>

**Comment by yshui** [comment]
@dubbadubbadubbacha You need `libev`, I am not sure but you can probably install that using whatever package manager FreeBSD uses.

FYI, you can find the whole list of dependencies you need in the [README](README.md).

**Comment by dubbadubbadubbacha** [comment]
Would it be possible to provide a patch?

**Comment by dubbadubbadubbacha** [comment]
It still fails on FreeBSD with libev installed

**Comment by yshui** [comment]
> Would it be possible to provide a patch?

What do you mean.

> It still fails on FreeBSD with libev installed

It would help if you can provide more information. Like how it fails.

**Comment by dubbadubbadubbacha** [comment]
A .diff file to patch whichever file you edited. 

Here is a more detailed error message:

<code>
Code:
 int main(int argc, char **argv) { return 0; }
Compiler stdout:
 
Compiler stderr:
 /usr/bin/ld: cannot find -lev
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Running compile:
Working directory:  /tmp/tmpqzdtntnp
Command line:  cc /tmp/tmpqzdtntnp/testfile.c -pipe -D_FILE_OFFSET_BITS=64 -c -o /tmp/tmpqzdtntnp/output.obj -O0 --print-search-dirs 

Code:
 
Compiler stdout:
 programs: =/usr/bin
libraries: =/usr/lib/clang/6.0.0:/usr/lib

Compiler stderr:
 

src/meson.build:1:0: ERROR:  C library 'ev' not found
</code>

**Comment by yshui** [comment]
@dubbadubbadubbacha Are you sure libev is correctly installed? Is there a `libev.so` or `libev.a` in `/usr/lib`?

**Comment by dubbadubbadubbacha** [comment]
Yup. libs are installed at /usr/local/lib in FreeBSD

**Comment by yshui** [comment]
Ah, I don't think meson looks there for libraries by default...

**Comment by dubbadubbadubbacha** [comment]
Naturally, the compilers on FreeBSD will look in their proper locations I guess. Is there anything I can edit in the build or Makefile?

**Comment by yshui** [comment]
@dubbadubbadubbacha I don't have a FreeBSD system, so I don't know how much help I can provide. But reading meson's code (if you know python) to figure out where it finds the libraries, might be useful.

**Comment by yshui** [comment]
Also, try compile a simple program with `-lev` and see if that compiles.

**Comment by dubbadubbadubbacha** [comment]
OK thanks. That's a bit advanced for me but I'll give it a try.

**Comment by yshui** [comment]
@dubbadubbadubbacha Any luck building compton?

**Comment by dubbadubbadubbacha** [comment]
Nah. That libev is the culprit. I'll have to either wait for the maintainer to update or figure out how to port it properly myself. I may do the latter.

**Comment by yshui** [comment]
@dubbadubbadubbacha As a follow up, did you get any luck building compton since last time?

**Comment by yshui** [comment]
Since the problem reported originally is fixed. I will close this issue.

If you still have problem building compton, please open another issue for that. @dubbadubbadubbacha
