### ISSUE TITLE
Worse screen tearing with recent versions

### ISSUE THREAD

**Issue by Avi-D-coder** [yshui/compton#70]
### Platform
Arch Linux 4.19.10-arch1-1-ARCH
Compton built from git.

### GPU, drivers, and screen setup
Intel Corporation HD Graphics 620 (rev 02)
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
    Version: 18.3.1
    Accelerated: yes
    Video memory: 3058MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.3.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
### Environment
i3

### Compton setup
```
**Version:** v4-rc1-32-g90e1974

### Extensions:

* Name Pixmap: Yes
* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: None
```
### Compton configuration:
```
compton -CG --config /dev/null --backend glx
```

### Steps of reproduction
1. Built from latest commit on next branch at `Wed 05 Dec 2018 04:42:36 PM EST`  small amount of tearing in random locations in chrome when scrolling GitHub and others sites.
2. Packages built from latest commit on next branch at `Sun 16 Dec 2018 08:40:47 PM EST` and present `Fri 21 Dec 2018 01:10:08 AM EST` major tearing line 3/4 up screen in chrome when scrolling GitHub and others sites. The tearing is worse than without compton running.

I am not sure what commit caused the issue, I will try to bisect tomorrow.

**Comment by dikiaap** [comment]
There are some changes at #66 and I have screen tearing when using glx backend with the vsync flag is "none"

Try by adding `--vsync vsync-method` to the command has fixed my issue

List of V-sync method:
https://github.com/yshui/compton/commit/de1cce21badc436bf501e1f865536688c34a4693#diff-a21d418da0483bb78bcc4380d067ff7fL134

**Comment by yshui** [comment]
@dikiaap @Avi-D-coder Yep. compton has started explicitly disabling vsync when `vsync` is set to `none`. Previously vsync might be enabled by default by your video drivers, and is causing people who don't want vsync some unwanted lag.

**Comment by Avi-D-coder** [comment]
### So I did some experimenting.

The two least tearing configs with either `xf86-video-intel or the `modesetting` driver are:
1. ##### opengl-swc:
    `compton -CG --config /dev/null --backend glx --vsync opengl-swc --glx-swap-method -1  --glx-no-stencil --sw-opti`

2. ##### opengl drm:
    `compton -CG --config /dev/null --backend glx --vsync drm --glx-swap-method -1`

With `xf86-video-intel`  `opengl-swc` and `drm` produces many very small tears when scrolling.
With `modesetting` neither produce decent results. `opengl-swc` produces many small tears. 

What is strange is that `drm` + `opengl` + `modesetting` produces the clearest easiest to read output when scrolling and the best gpu/cpu performance. The problem is there it also produces a very clear diagonal tear line descending from the top right.

**Comment by yshui** [comment]
Can you explain what you meant by "many small tears"? That sounds like some kind of visual artifact to me. If you have screenshots/recordings, that will be great.

**Comment by Avi-D-coder** [comment]
With the `modesetting` driver and drm: https://youtu.be/jM9KHHYsNT8

The tearing did not record very well.
The other configs produce similar tearing, but more evenly spread-out around the screen.

**Comment by yshui** [comment]
@Avi-D-coder So it is not a horizontal line that goes across the entire screen?

Can you try not setting `glx-swap-method`?

**Comment by Avi-D-coder** [comment]
+ `modesetting` + `drm` = tear line across whole chrome window at least partially at a diagonal.
+ Without compton = horizontal tear line across whole chrome window.
+ With any other driver config combination varying amount of small tears not across the whole window usually. 
These tear lines don't stay in the same area like the bigger tears, but do make it hard to read text if I am scrolling. It almost looks like flickering, but not quite.

 As long as the text is not under a big tear line I normally can read it while scrolling with `modesetting` + `drm` or no compton.

**Comment by jrudess** [comment]
I'm also seeing new tearing issues with Nvidia.  My test case is amazon video in chromium (not full screen).  Bisect led to e2182bb00bb418d616dc047d1f2c280e952f8df3

But sometimes the tearing takes a while to observe, so there is some chance I've marked a bad commit as good during the bisect.

**Comment by jrudess** [comment]
The following patch appears to resolve the tearing issues with head of next branch:

```
diff --git a/src/vsync.c b/src/vsync.c
index 4ea17d2..d680576 100644
--- a/src/vsync.c
+++ b/src/vsync.c
@@ -269,8 +269,8 @@ void (*const VSYNC_FUNCS_DEINIT[NUM_VSYNC])(session_t *ps) = {
  */
 bool vsync_init(session_t *ps) {
   // Mesa turns on swap control by default, undo that
-  if (bkend_use_glx(ps))
-    vsync_opengl_swc_swap_interval(ps, 0);
+  // if (bkend_use_glx(ps))
+  //  vsync_opengl_swc_swap_interval(ps, 0);

   if (ps->o.vsync && VSYNC_FUNCS_INIT[ps->o.vsync]
       && !VSYNC_FUNCS_INIT[ps->o.vsync](ps)) {
```

**Comment by yshui** [comment]
@jrudess Are you sure you explicitly enabled vsync in your config file?

**Comment by yshui** [comment]
can you try vsync = opengl-swc?

**Comment by jrudess** [comment]
opengl-swc appears to resolve tearing for me

**Comment by yshui** [comment]
I guess this is evidence that "vsync = opengl" never worked. People got vsync just because it was enabled by default by Mesa.

**Comment by aufkrawall** [comment]
Well, it definitely worked for me some time ago. :)
But since it's bugged nowadays and users usually want vsync, perhaps `swc` should be the default setting?
I also wonder if `opengl-oml` is actually beneficial for any cases.

**Comment by yshui** [comment]
> perhaps `swc` should be the default setting?

That is my plan too.

> I also wonder if `opengl-oml` is actually beneficial for any cases.

It is useful for something, but not as a reliable vsync method.

**Comment by tuyenpm9** [comment]
unfortunately, opengl-swc doesn't work well with intel HD 620 with xf86-video-intel driver. If I use `opengl` and try to record video using ffmpeg, result a good video quality - no tearing. But same ffmpeg command but compton using `opengl-swc` result a bad tearing video - frames are broken and images totally tear out.

If I don't record a video using ffmpeg, I barely can see the difference, just a little lag of images.

**Comment by Streetwalrus** [comment]
`opengl-swc` is the same as what mesa previously enabled by default with _all_ vsync methods, including `none`. Leaving it enabled with other methods would be detrimental to performance (can result in dropped frames).
If you experience tearing with SWC then it's most likely not compton's fault.
All other methods use non-atomic sync+swaps which is prone to breakage and can be detrimental to performance.
SWC (at least on mesa) queues an asynchronous swap and leaves syncing up to the driver. It will only block if the last frame hasn't already been swapped to the display. This is always what we want.

**Comment by yshui** [comment]
@Avi-D-coder A couple of things here:

1. Are you sure, that `compton --config /dev/null --vsync opengl-swc --backend glx` doesn't solve your problem.
2. If a screen capture doesn't record the tearing well, maybe you can point a camera to your screen.
3. Were you able to do a bisect to find the offending commit?

**Comment by Avi-D-coder** [comment]
Sorry I haven't gotten a chance to bisect yet. `compton -CG --config /dev/null --backend glx --vsync opengl-swc --glx-swap-method -1  --glx-no-stencil --vsync-use-glfinish` seems to be good enough for now.

There is still an occasional tear when playing a video and scrolling, but the situation improved drastically around the time I updated to linux 4.20.
Thank you.

**Comment by maximbaz** [comment]
@yshui I've just got an update for `v5.0` on Arch Linux and experienced this bug, interestingly the issue didn't reproduce with 

```
compton --config /dev/null --vsync opengl-swc --backend glx
```

like you suggested, but it did reproduce with `compton` when my config file only contained two lines:

```
backend = "glx";
vsync = "opengl-swc";
```

This lead me to believe that v5 is not properly reading config files. I've seen that you fixed this recently, so I compiled compton from `next` branch and sure enough the bug no longer reproduce.

Could you please cut off a new release? It looks like a serious regression in `v5.0` comparing to `v4.0`.

**Comment by yshui** [comment]
@maximbaz I might be that compton is not reading your config file. `compton --diagnostics` will tell you which config file is used.

**Comment by maximbaz** [comment]
That confirms the issue!

On v5:

```
* Config file used: /etc/xdg//compton.conf
```

On `next` branch:

```
* Config file used: /home/maximbaz/.config/compton/compton.conf
```
