### ISSUE TITLE
[Q] Keep border of window?

### ISSUE THREAD

**Issue by tuyenpm9** [yshui/compton#71]
// The template below is for reporting bugs. For feature requests and others, feel free to delete irrelevant entries.

### Platform
Archlinux 

### GPU, drivers, and screen setup
Intel 620

### Environment
Just X

### Compton version
v4-rc1-68-g46b50b4

### Compton configuration:
Default one

### Steps of reproduction

1. open mpv at specific region of screen, not fullscreen --> windows has border
2. press f on mpv window ->get fullscreen -> press f again to back to window
3. now border disappear

### Expected behavior
I'd like to keep border after step 3 for consistency.

**Comment by yshui** [comment]
What is the window manager you are using? Can you attach a screenshot before and after the border disappears?
