### ISSUE TITLE
-C/--no-dock-shadow has been set, yet lemonbar has shaddows

### ISSUE THREAD

**Issue by onodera-punpun** [yshui/compton#79]
### Platform
// CRUX version 3.4

### GPU, drivers, and screen setup
AMD with AMDGPU

### Environment
Openbox

### Compton version
Git master

### Compton configuration:
`compton -b --backend xrender -cCG -l -12 -t -10 -o 0.15`

### Expected behavior
No shadows on lemonbar

### Current Behavior
Shadows on lemonbar

### Other details
This didn't happen with the before-fork compton

**Comment by onodera-punpun** [comment]
Sorry, I don't have compton compiled with libconfig, I'll try this later tonight.

**Comment by yshui** [comment]
@onodera-punpun Can you try the `wintypes` branch? It should fix your problem.

**Comment by yshui** [comment]
@onodera-punpun Have you tried put it in the config file?

**Comment by yshui** [comment]
@onodera-punpun OK, _now_ it should fix your problem

**Comment by onodera-punpun** [comment]
This indeed fixes it, thanks a lot!
