### ISSUE TITLE
frame-opacity just partially opaque

### ISSUE THREAD

**Issue by Baerbeisser** [yshui/compton#81]
Platform: Manjaro, Artix
GPU: Pentium Sandbridge iGPU, Vega 56
Compton version: 4.0-1
Confirmed on Manjaro & Manjaro Live on both systems and Artix on Vega with different Themes and Frame Styles, with and without nocsd-Patch, with and without blurring.
This issue appeared with the last update 1 - 2 Months ago. `compton-tryone-git` from AUR works.

### Simple config for testing:
```
menu-opacity = 0.96;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 0.65;
inactive-dim = 0.0;

blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;
blur-kern = "7x7box";
```

### Steps of reproduction

1. Install compton from community
2. Paste above config in ~/config/compton.conf
3. Run compton with `compton --daemon`

### Expected behavior
Frame and title should be opaque

### Current Behavior
Just a small part top of the title and left side of the frame are opaque.

### Pictures!
Theme: Adwaita
Frame: Daola

![adwaita-daloa_enabled](https://user-images.githubusercontent.com/22264628/50492706-1a17cd00-0a11-11e9-8389-ad53ba9358c9.png)
![adwaita-daloa_disabled](https://user-images.githubusercontent.com/22264628/50492746-606d2c00-0a11-11e9-842a-a5fb58581000.png)

Same, but with tryone's version:
![adwaita-daloa_tryone_enabled](https://user-images.githubusercontent.com/22264628/50492806-a1654080-0a11-11e9-8b21-057948f1449d.png)
![adwaita-daloa_tryone_disabled](https://user-images.githubusercontent.com/22264628/50492813-afb35c80-0a11-11e9-82a7-750ccc6f7243.png)

**Comment by yshui** [comment]
This should've been fixed in the latest `next` branch

**Comment by ncmprhnsbl** [comment]
hint: aur: compton-git builds yshui/next ;)

**Comment by yshui** [comment]
@Baerbeisser Yes, the next update should fix this.

If the performance is a concern, you can open another issue.

Closing.
