### ISSUE TITLE
Build fails with "new backends" disabled

### ISSUE THREAD

**Issue by Streetwalrus** [yshui/compton#83]
### Compton version
34eb14f

### Steps of reproduction
Build without passing `-Dnew_backends=true` to meson
 
### Expected behavior
Build succeeds

### Current Behavior
Build fails with the following because `src/backend/backend.c` is not included.
```
/usr/bin/ld: src/25a6634@@compton@exe/backend_backend_common.c.o: in function `paint_all_new':
/home/streetwalrus/source/compton/build/../src/backend/backend_common.c:245: undefined reference to `backend_list'
collect2: error: ld returned 1 exit status
```

**Comment by yshui** [comment]
Thanks for reporting
