### ISSUE TITLE
config error 

### ISSUE THREAD

**Issue by blockhead100** [yshui/compton#939]
![image](https://user-images.githubusercontent.com/55167737/203623378-1eaccf5c-c81a-4848-b2c4-984d0db2d7ec.png)
I dont see any thing bad with:
![image](https://user-images.githubusercontent.com/55167737/203623545-610517fc-268a-477f-82f3-62bd08759a91.png)

### Platform
Pop!_OS 22.04 LTS

### GPU, drivers, and screen setup
no gpu one screen

### Environment
i3-gaps and poly bar

### picom version
V9
<details>
<summary>Diagnostics</summary>

[ 11/23/2022 10:42:41.066 parse_config_libconfig FATAL ERROR ] Error when reading configuration file 
 /home/bryce/.config/picom/picom.conf", line 92: syntax error
[ 11/23/2022 10:42:41.066 main FATAL ERROR ] Failed to create new session.

</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

</details>

### Steps of reproduction
1. input my config with picom v9
2.run

### Current Behavior

[ 11/23/2022 10:42:41.066 parse_config_libconfig FATAL ERROR ] Error when reading configuration file "/home/bryce/.config/picom/picom.conf", line 92: syntax error
[ 11/23/2022 10:42:41.066 main FATAL ERROR ] Failed to create new session.

**Comment by blockhead100** [comment]
my config did not attach for a bad file type error. here:
[picom.txt](https://github.com/yshui/picom/files/10078317/picom.txt)

**Comment by r0-zero** [comment]
Hello

Popos is debian based and use ubuntu packages. In apt, unfortunately libconfig package is old and that is why you have errors. If you download and make the libconfig from github, your issue will get resolved

**Comment by yshui** [comment]
My guess is you have to remove the extra comma?

**Comment by r0-zero** [comment]
Oh in 89, yeah you are right. I used to have this issue on ubuntu jumped without reading :D

**Comment by blockhead100** [comment]
where is this extra comma?

**Comment by yshui** [comment]
line 89
