### ISSUE TITLE
Screen Tearing with M&B Warband

### ISSUE THREAD

**Issue by siyia2** [yshui/compton#95]
### Platform
Gentoo

### GPU, drivers, and screen setup
Radeon 535 mobile,vega3
llvm 7.0.1 mesa 18.3.2
### Environment
xfce4 4.12.5

### Compton version
Next and Master
### Compton configuration:
```
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
clear-shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;

shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'VirtualBox'",
	"class_g = 'Chromium'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"! name~=''",
	"_GTK_FRAME_EXTENTS@:c"
];

# Opacity
menu-opacity = 0.87;
inactive-opacity = 1.0;
frame-opacity = 0.95;
inactive-opacity-override = false;
alpha-step = 0.06;

opacity-rule = [ "80:class_g = 'XTerm'" ];

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 60;
sw-opti = false;
unredir-if-possible = true;
unredir-if-possible-exclude = [ "class_g = 'smplayer'",
"class_g = 'firefox'" ];
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];

# GLX backend
vsync = "opengl-mswc";
paint-on-overlay = true;
vsync-use-glfinish= true;
glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;
glx-swap-method = "buffer-age";
glx-use-gpushader4 = true;
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = true; focus = true; };
};
```

### Steps of reproduction
start mount and blade warband with radeon 535 play a map there is always screen tearing at the top of screen, regardless of in-game vsync on/off

### Expected behavior
No screen tearing with in-game vsync on
### Current Behavior
Screen tearing with in-game vsync on

### Other details
All other games work fine with compton-next/master and in-game vsync on, mount and blade warband works without screen tearing with the old compton and my current config.If i use vega 3 gpu with compton-next/master no screen tearing, it happens only with mount and blade+radeon 535+compton-next/master.

**Comment by siyia2** [comment]
Just tried it no change at all

**Comment by yshui** [comment]
@siyia2 Wild guess: what if you disable `vsync-use-glfinish`

**Comment by aufkrawall** [comment]
Wasn't it ignored anyway when specified in config file only?

**Comment by siyia2** [comment]
i ll try to test glfinish off ,but it is important to note that the old compton works fine with radeon 535 and M&B

**Comment by siyia2** [comment]
Tested with glfinish off no change at all,if i launch the specific game without unredir-if-possible the game never graphically launches

**Comment by aufkrawall** [comment]
Compton can't prevent tearing in fullscreen when there is `--unredir-if-possible = true`.

I btw. noticed some weird behavior on xfce where `--unredir-if-possible = true`breaks after alt + tabbing out of games, Compton then simply stays activated (not unredirected) when changing back into the fullscreen window.
I could provoke this behavior instantly, while it never occured at any time during months of usage with KDE Plasma.

Funny thing is Gnome-Mutter shows exactly the same behavior, might be some GTK issue.

**Comment by yshui** [comment]
@siyia2 With `unredir-if-possible = true`, compton does _nothing_ when something is fullscreen. So I think this _probably_ isn't compton's fault. Plus, I does not have the ability to reproduce this problem, since this game doesn't have a free Linux demo.

So if you think this is really a compton issue, you would have to do a bisect of compton yourself. Your effort will be appreciated though.

**Comment by siyia2** [comment]
i am sure it is compton-next fault it's the only thing that changes and causes that issue

**Comment by yshui** [comment]
@siyia2 OK. There are a few things you could do. First, can you run compton with `--log-level=trace` and attached the output here? Also, if you can, please do a bisect so we can know the offending commit.

**Comment by siyia2** [comment]
--log-level=trace when it happens?

**Comment by yshui** [comment]
@siyia2 Sorry for not being clear. But yes, '--log-level=trace', then run the game until the tearing happens.

**Comment by siyia2** [comment]
could you please fix the make file of clean-opt branch of compton, i will test and start to bisect from there

**Comment by siyia2** [comment]
sorry it's not the make file that has problem but a couple of the source files

**Comment by yshui** [comment]
@siyia2 Why are you using that branch?

**Comment by siyia2** [comment]
--log-trace does not exist as  a compton function,however running compton/netx from the terminal and playin M&B Warband didn't cause tearing

**Comment by yshui** [comment]
@siyia2 Sorry but I am not sure what you mean. does the `next` branch of compton not causing tearing anymore?

**Comment by siyia2** [comment]
if i boot xfce4 with no compositor and then run compton/next from terminal no tearing which is weird

**Comment by siyia2** [comment]
ok i think i figured it out,some sort of race condition when booting xfce4 caused the malfunction with compton-next,if i delay compton's startup by 2s i cannot reproduce the tearing in M&B.

**Comment by yshui** [comment]
@siyia2 Can you check if compton is actually running when you delay its start?

**Comment by yshui** [comment]
> --log-trace does not exist 

It is `--log-level=trace`

**Comment by siyia2** [comment]
yea i didnt have apitrace installed i will test again because it doesnt make sense an post back

**Comment by siyia2** [comment]
yea i am 100% sure it's what i told and i am sure compton runs in both cases:

Screen Tear=start compton immediately with xfce4 and use secondary dedicated gpu for M&B

No Tear=start compton with at least 2s delay  in xfce4 and use secondary dedicated gpu for M&B

**Comment by siyia2** [comment]
i also get compton: unrecognized option '--log-level=trace'

**Comment by yshui** [comment]
@siyia2 You are probably running an older version of compton, current next should have --log-level

**Comment by siyia2** [comment]
https://github.com/yshui/compton

i pressed download

**Comment by siyia2** [comment]
delayin compton at startup always fixes the tearing for M&B all else equal i reproduced it 5 times

**Comment by siyia2** [comment]
are there any requirements for running --log-level=trace?i can run it with the same compton-next on my arch box but not on my gentoo laptop

**Comment by yshui** [comment]
Check if you are running the same version of compton (`compton --version`)

**Comment by siyia2** [comment]
i get unrecognised option --version

**Comment by siyia2** [comment]
ok regardless of that, delaying compton's-next start with xfce 4.12.5 fixes the issue 100% i opened.

**Comment by siyia2** [comment]
ok my bad i had 2 compton installations on my system and delayin compton-next caused old compton to start that's why the issue was solved here is the trace log wehn it happens

[trace.txt](https://github.com/yshui/compton/files/2813354/trace.txt)

**Comment by yshui** [comment]
@siyia2 just to confirm, does `unredir-if-possible = false` solve your problem?

**Comment by siyia2** [comment]
yes totally with compton-next,i guess i will exclude M&B from unredir-if-possible = false in my config, what was confusing was that i had both compton old and next start and couldnt reproduce the problem,other games with unredir-if-possible = false work fine.

**Comment by yshui** [comment]
@siyia2 So, a reasonable hypothesis would be that `unredir-if-possible` doesn't actually work correctly in _older_ versions of compton, so the screen is not actually unredirected when you start the game. Thus vsync works in the game with older versions of compton.

With `compton-next`, the screen is properly unredirected thus vsync stops to work.

**Comment by siyia2** [comment]
ok i think i can close this issue,also why the -next branch is not bumped to v5?it is still reported as v4

**Comment by yshui** [comment]
I am _quite_ certain -next is at `v5-rc4`

**Comment by siyia2** [comment]
ok all good, sorry for the confusion
