### ISSUE TITLE
Config parsing error

### ISSUE THREAD

**Issue by Crandel** [yshui/compton#96]
### Platform
Ubuntu Desktop 18.04 amd64

### GPU, drivers, and screen setup
```
$ glxinfo -B                
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  (0x5916)
    Version: 18.0.5
    Accelerated: yes
    Video memory: 3058MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment
WM: i3-wm

### Compton version
```
$ compton --version                      
v5
```
### Compton configuration:
[my config](https://github.com/Crandel/home/blob/master/.config/compton.conf)
### Steps of reproduction
```
$ compton --config ~/.config/compton.conf -b      
[ 01/29/2019 11:07:01.109 parse_config_libconfig ERROR ] Error when reading configuration file "/home/vitalii.drevenchuk/.config/compton.conf", line 71: syntax error
```

### Expected behavior
Meaningful error message

### Current Behavior
Unknown error message, not able to fix config

**Comment by yshui** [comment]
This is a very good point, but unfortunately, this is what the config parsing library compton uses (libconfig) reports when it encounter errors.

I would like some informative error messages as well, but it probably can't easily be done without switching out libconfig for something else.

**Comment by Crandel** [comment]
OK, so maybe you could help to fix this issue? It appear after I update compton from v4 to v5. Config was not changed

**Comment by yshui** [comment]
@Crandel I can load the config file in your git repo with no problem. Maybe you have some local changes to it?

**Comment by Crandel** [comment]
Hmm, strange. This is exactly config I have. OK, I will try to investigate it by myself. Thanks

**Comment by yshui** [comment]
@Crandel Could be different versions of libconfig.

**Comment by Crandel** [comment]
I have
```
libconfig++-dev/bionic,now 1.5-0.4 amd64 [installed]
libconfig++9v5/bionic,now 1.5-0.4 amd64 [installed,automatic]
libconfig-dev/bionic,now 1.5-0.4 amd64 [installed,automatic]
libconfig-doc/bionic,bionic,now 1.5-0.4 all [installed,automatic]
libconfig-general-perl/bionic,bionic,now 2.63-1 all [installed,automatic]
libconfig9/bionic,now 1.5-0.4 amd64 [installed,automatic]
```

**Comment by x70b1** [comment]
I have something similar:

In my config is `blur-kern = "7x7box";`:
```
[ 01.02.2019 20:21:48.447 parse_matrix ERROR ] Trailing characters in matrix string.
[ 01.02.2019 20:21:48.447 parse_config_libconfig FATAL ERROR ] Cannot parse "blur-kern"
```

But if I use `compton --config ~/.config/compton/config --blur-kern="7x7box"` it works.
So something is broken here.

```
Name                     : compton-git
Version                  : 2:790_Next.4.g3f5a4d5_2019.01.31-1
```
```
Name                     : libconfig
Version                  : 1.7.2-1
```

**Comment by yshui** [comment]
@x70b1 can you provide your whole config file?

**Comment by x70b1** [comment]
Already this fails:

```
#  .config/compton/config

blur-kern = "7x7box";
```
But you can't reproduce it?

**Comment by yshui** [comment]
@x70b1 Hmm, really strange. I get an error when using my distros' compton (Archlinux), but not from the compton I built from the same commit.

**Comment by x70b1** [comment]
Damn.

**Comment by yshui** [comment]
@x70b1 Run `compton --diagnostics` to make sure the config file used is what you expect.

**Comment by x70b1** [comment]
Yes, the config path is correct. Actually I have no idea too. Arch switched the upstream repo from chjj/compton to yshui/compton some days ago. After that my blur-setting fails.

`blur-kern = "";` is parsable - but is not what I wanted. 
Also the blur value from the manpage `7,7,0.000003,0.000102,0.0008 ....` fails in my config. 

A parameter `--blur-kern` works fine. That seems to be my workaround.

**Comment by yshui** [comment]
@x70b1 Hmm, I have an idea. What is your locale? Can you paste the output of `locale`?

**Comment by x70b1** [comment]
```
LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
```

**Comment by yshui** [comment]
@x70b1 So this is why... I will see how I can fix it.

**Comment by x70b1** [comment]
Is the `matrix` value something that is locale specific?

**Comment by yshui** [comment]
@x70b1 Yep, because `7,7` is now a real number equals to 77 divided by 10.

**Comment by yshui** [comment]
@x70b1 Fixed in `next`. But I think this problem probably doesn't relate to @Crandel's problem, so I will flag our conversation off-topic

**Comment by x70b1** [comment]
Works now. Thanks a lot for your great job! :+1:

**Comment by yshui** [comment]
@Crandel What is the output of `locale` on your system?

**Comment by Crandel** [comment]
Sorry for delay
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by yshui** [comment]
OK, I am out of ideas.

**Comment by yshui** [comment]
I forgot I haven't tried your version of libconfig yet.

Turns out it is indeed a libconfig problem. libconfig 1.5 has this problem, while 1.7.2 is perfectly fine.

Not sure what I can do.

**Comment by yshui** [comment]
BTW, to fix your problem, just remove the extra comma at the end of each list.

e.g.

```


shadow-exclude = [
    "class_g ~= 'Firefox'",
    "class_g ~= 'Viber'",
    "class_g ~= 'vlc'",
];
```

Should be

```


shadow-exclude = [
    "class_g ~= 'Firefox'",
    "class_g ~= 'Viber'",
    "class_g ~= 'vlc'"
];
```

**Comment by severen** [comment]
Related: When Compton (or libconfig) fails to parse the config, Compton will still run anyway. IMO the Compton's behaviour should be to exit with a non-zero exit code. This is especially helpful if you run Compton as a systemd user service and what to check if it has failed with `systemctl --user --failed`.

As an anecdote I noticed earlier today that shadows and fading weren't working, leading me to believe that Compton had crashed, but when I ran `systemctl --user --failed`, nothing came up.

**Comment by yshui** [comment]
@severen Good point.

**Comment by yshui** [comment]
@severen Done

**Comment by Crandel** [comment]
@yshui I delete commas and it works, thank you very much
