### ISSUE TITLE
selectively turn off vsync/enable tearing for certain games

### ISSUE THREAD

**Issue by SoniEx2** [yshui/compton#964]
### Platform
Arch Linux x86_64

### GPU, drivers, and screen setup
Intel HD Graphics 2500 + AMD Radeon RX 6500 XT
Mesa 22.2.3-1
Single screen (1080p60)

### Environment
awesome-wm

### picom version
vgit-98a5c

### Other details
we would like to turn off vsync in certain games, while the rest of the OS follows vsync. is that possible? current approach is to kill picom when gaming.

**Comment by yshui** [comment]
you can turn of vsync for the whole system while certain game is running. See `unredir-if-possible`, `NET_WM_BYPASS_COMPOSITOR`
