### ISSUE TITLE
Fullscreen application on one monitor disables all effects of picom on another monitor

### ISSUE THREAD

**Issue by OriginCode** [yshui/compton#966]
### Platform

AOSC OS (10.0.0) x86_64

### GPU, drivers, and screen setup

NVIDIA GeForce RTX 2060 Mobile, nvidia driver 525.60.11, two monitors configured side-by-side with xrandr

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 6144 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 5191 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.60.11
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 525.60.11
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.60.11
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

i3-gaps

### picom version

v10
<details>
<summary>Diagnostics</summary>

**Version:** v10

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/origincode/.config/picom.conf

### Drivers (inaccurate):

NVIDIA

### Backend: glx

* Driver vendors:
 * GLX: NVIDIA Corporation
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2

### Backend: egl

* Driver vendors:
 * EGL: NVIDIA
 * GL: NVIDIA Corporation
* GL renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
backend = "glx";
use-damage = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
unredir-if-possible = true;
xrender-sync-fence = true;

fading = true;
fade-delta = 2;
#inactive-opacity = 0.75;

shadow = true                  # Enabled client-side shadows on windows
shadow-radius = 10;                # The blur radius for shadows (default 12)
shadow-offset-x = -10;               # The left offset for shadows (default -15)
shadow-offset-y = -10;               # The top offset for shadows (default -15)

corner-radius = 10;

#blur:
#{
#    method = "gaussian";
#    size = 10;
#    deviation = 10.0;
#};

blur-background-exclude = [
    "window_type = 'desktop'",
    "window_type = 'popup_menu'",
    "_GTK_FRAME_EXTENTS@:c"
];

shadow-exclude = [
#    "!I3_FLOATING_WINDOW@:c",
#    "class_g ?= 'polybar'",
#    "class_g ?= 'rofi'",
]

rounded-corners-exclude = [
    "!I3_FLOATING_WINDOW@:c",
#    "class_g ?= 'polybar'",
]

opacity-rule = [
	"90:class_g = 'i3bar'",
];
    
wintypes:
{
    notify = { full-shadow = true };
#    dock = { shadow = false };
    dnd = { shadow = true };
    menu = { shadow = true };
	dropdown_menu = { shadow = false };
	popup_menu = { shadow = false };
	utility = { shadow = false };
};

```
</details>

### Steps of reproduction

1. Open up a fullscreen application on one monitor

### Expected behavior

Effects remain on another monitor. Including transparency, shadow and rounded corners.

### Current Behavior

Transparency, shadow and rounded corners disappear when a fullscreen window is opened on another monitor.

**Comment by absolutelynothelix** [comment]
i believe it's because of `unredir-if-possible` is set to `true`. does setting it to `false` fix the issue?

**Comment by OriginCode** [comment]
> i believe it's because of `unredir-if-possible` is set to `true`. does setting it to `false` fix the issue?

Yes it works. Thank you! Closing now.

**Comment by absolutelynothelix** [comment]
i don’t think that it’s desired behavior. i’d reopen and see what @yshui will say.

**Comment by OriginCode** [comment]
> i don’t think that it’s desired behavior. i’d reopen and see what @yshui will say.

Reopening.

**Comment by yshui** [comment]
this is intended behavior. if you don't want fullscreen window to cause unredirect, use `no-ewmh-fullscreen`

**Comment by absolutelynothelix** [comment]
@yshui, if you have, say, three monitors side-by-side, it’s a bit weird that one fullscreen window disables compositor entirely. well, if it’s really intended behavior and user supposed to use `no-ewmh-fullscreen`, then this issue can be closed, since my question was answered.
