### ISSUE TITLE
Xfce4-panel 4.18 not initialized at the begin of the session transparency missing.

### ISSUE THREAD

**Issue by sushi2503** [yshui/compton#973]
### Platform
Archlinux up to date.

### GPU, drivers, and screen setup
Intel UHD 630 embedded GPU  
Mesa 22.3.1-1
 glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 630 (CFL GT2) (0x3e92)
    Version: 22.3.1
    Accelerated: yes
    Video memory: 15731MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.3.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Environment
Xfce4 4.18

### picom version
vgit-98a5c

picom --diagnostics
**Version:** vgit-98a5c

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: No
  (Another compositor is already running)
* Config file used: /home/pilote/.config/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)

#################################
#                                Backend                                         #
################################# 

#Backend to use: "xrender", "glx" or "xr_glx_hybrid".
#GLX backend is typically much faster but depends on a sane driver.

backend = "glx";
glx-no-stencil = true;
vsync = true;
#use-damage = false;

#################################
#                                  Fading                                          #
#################################

# Fade windows in/out when opening/closing and when opacity changes,
#  unless no-fading-openclose is used.
fading = true;

# Opacity change between steps while fading in. (0.01 - 1.0, defaults to 0.028)
fade-in-step = 0.03;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
fade-out-step = 0.03;

# The time between steps in fade step, in milliseconds. (> 0, defaults to 10)
fade-delta = 10;

# Specify a list of conditions of windows that should not be faded.
fade-exclude = [ 
  "class_g = 'Conky'",
  "window_type = 'desktop'" 
];

# Do not fade on window open/close.
# no-fading-openclose = false

# Do not fade destroyed ARGB windows with WM frame. Workaround of bugs in Openbox, Fluxbox, etc.
# no-fading-destroyed-argb = false

#################################
#                                      Focus                                       #
#################################

# Specify a list of conditions of windows that should always be considered focused.
focus-exclude = [
 "class_g = 'mpv'",
 "window_type = 'utility'"
];

#################################
#                      Transparency / Opacity                          #
#################################

# Opacity of inactive windows. (0.1 - 1.0, defaults to 1.0)
inactive-opacity = 0.7;

# Opacity of window titlebars and borders. (0.1 - 1.0, disabled by default)
frame-opacity = 0.7;

# Default opacity for active windows. (0.0 - 1.0, defaults to 1.0)
active-opacity = 1.0;

# Dim inactive windows. (0.0 - 1.0, defaults to 0.0)
inactive-dim = 0.6;

# Use fixed inactive dim value, instead of adjusting according to window opacity.
#inactive-dim-fixed = true;

# Let inactive opacity set by -i override the '_NET_WM_OPACITY' values of windows.
#inactive-opacity-override = false;

# Specify a list of opacity rules, in the format `PERCENT:PATTERN`, 
# like `50:name *= "Firefox"`. picom-trans is recommended over this. 
# Note we don't make any guarantee about possible conflicts with other 
# programs that set '_NET_WM_WINDOW_OPACITY' on frame or client windows.

opacity-rule = [
"90:class_g = 'Xfce-polkit'",
"85:class_g = 'Xfce4-session-settings'",
"85:class_g = 'Xfce4-appfinder'",
"85:class_g = 'Wrapper-2.0'",
"85:class_g = 'Xfce4-appearance-settings'",
"85:class_g = 'Xfce4-display-settings'",
"85:class_g = 'Xfce4-keyboard-settings'",
"55:class_g = 'Conky'"
];

#################################
#                              Wintypes rules                                #
#################################

wintypes:
{
normal = { shadow = true; full-shadow = true; };
tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = true; };
dock = { shadow = false; };
dnd = { shadow = false; };
popup_menu = { opacity = 0.85; shadow = true; full-shadow = true; };
dropdown_menu = { opacity = 0.85; shadow = true; full-shadow = true; };
notify = { opacity = 0.90; shadow = true; full-shadow = true; };
utility = { opacity = 0.90; shadow = true; full-shadow = true; };
combo = { opacity = 0.85; shadow = true; full-shadow = true; };
dialog = { opacity = 0.85; shadow = true; full-shadow = true; };
};

#################################
#                                 Shadows                                       #
#################################

shadow = true;
shadow-radius = 20;
shadow-offset-x = -13;
shadow-offset-y = -13;
shadow-opacity = 0.9;
shadow-exclude = [
 "class_g = 'Conky'" 
];

#################################
#                            Rounded corners                              #
#################################

corner-radius = 9;

### Steps of reproduction

Start a session.

### Expected behavior

Applying transparency to panels at the start of the session.

### Current Behavior

Not applying transparency to panels at the start of the session.

### Other details
Since the last xfce4-panel upgrade 4.16 to 4.18 the panels are not "initialized" at the start of the session and remain in plain black color instead of being transparent. I have to replace the panels (xfce4-panel -r) at the begin of the session to get them transparent.
With xfwm4 compositor there is no such problem and my panels get initialized/transparent at the start of the session without to replace them.

If you need more info, let me know.

Thanks.

**Comment by erydit** [comment]
I confirm the issue  on Manjaro with Xfce 4.18.
Picom v 10.2-1

**Comment by Monsterovich** [comment]
@sushi2503 The xfce4-panel always has some problems with transparency. You can try to use a 1x1 png with a transparent pixel instead of setting a transparent color.

**Comment by sushi2503** [comment]
@Monsterovich : Are you telling about your experience with the xfce4-panel ?

I never had any problem of transparency with them (xfwm4 compositor nor picom). As explained in my first post, the panels stay transparent with the xfwm4 compositor but not with picom. So it sounds like a problem or a setting with picom.

P.S. Picom v 10.2-1 since the last Archlinux update.

**Comment by Monsterovich** [comment]
> Are you telling about your experience with the xfce4-panel ?

Yes, I had a lot of issues with transparency, such as random graphical artifacts on the xfce4 panel, which were solved by setting a png image instead of color. My suspicion also falls on gtk3, because I don't remember having such issues when xfce was on gtk2.

**Comment by hexh250786313** [comment]
I have same issue. But I don't think it's strongly relative to picom. Because it can still become transparent when I ajust the opacity (entry / leave) slider. It is to say, picom is still available for xfce4-panel but except background option. Actually it happened after the xfce4 4.18 update which I think the problem is caused by.

**Comment by sushi2503** [comment]
@Monsterovich : For me it's the first transparency problem with picom/xfce4-panel. Anyway, till the reason get known I just add xfce4-panel -r in settings > session start > autostart and it's doing the job fine.

@hexh : Let see where the problem comes from... Maybe a picom dev/maintainer will take a look at this issue.

**Comment by pierovera** [comment]
I'm using picom 10.2-1 and xfce4-panel 4.18.0-1

@Monsterovich I tried the 1x1 transparent PNG trick but it still doesn't seem to work. I tried restarting picom but it didn't change anything. I also never had any issues with XFCE 4.16 and earlier when using a solid transparent color.

@hexh250786313 I also have this behavior where I can adjust the transparency with the enter/leave slider, but not with the background option, whether using solid color or an image.

**Comment by absolutelynothelix** [comment]
it's an xfce4-panel's issue, not picom's. looks like it chooses it's depth based on presence of a compositor: if there is no compositor running when it starts it will choose 24-bit depth (no transparency), otherwise it will choose 32-bit depth (transparency) and won't update it later.

~consider reporting this behavior upstream: https://gitlab.xfce.org/xfce/xfce4-panel~
upstream report: https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/672

as a workaround either start picom before the xfce4-panel or restart xfce4-panel after picom has started (something like `picom -b && xfce4-panel -r`).

**Comment by hexh250786313** [comment]
@absolutelynothelix I have tried it and xfce4-panel performed as you said that transparency was back after I restarted xfce4-panel.Thanks for your reporting!

**Comment by absolutelynothelix** [comment]
~also, in theory (i haven't tested that myself yet) you may use the `force-win-blend` option but it will negatively affect the overall performance.~ doesn't seem to work :(

**Comment by absolutelynothelix** [comment]
the issue was fixed upstream and the fix should be a part of xfce4-panel 4.18.2. until a new release of xfce4-panel you have to use one of the workarounds described above. this issue can be closed.

**Comment by absolutelynothelix** [comment]
xfce4-panel 4.18.2 was released a few months ago.
