### ISSUE TITLE
Release scheme

### ISSUE THREAD

**Issue by yshui** [yshui/compton#99]
## Problem

I originally wanted a simple release scheme: a release number that is incremented by 1 everytime a release is made, and the same number will be used as the version number.

But after a number of releases, I noticed a pattern: we do two kinds of releases, bug fix releases and "feature" releases. (Well, obviously this pattern is not new. This is mostly me being new to the world of software releases). 

Originally I thought the `next` branch will serve as a perpetual beta, and most major bugs will be eliminated during the `rc` phase. But it turns out to be too optimistic, each "feature" release is usually paired with an influx of bug reports. And I need to push out bug fixes quick, so I have to make a bugfix release shortly after the "feature" release. Both releases increments the version number, so the distinction between "feature" and bugfix releases just got lost to the user.

## Solution

Add a minor version number, bugfix releases only increment the minor version number, "feature" releases reset the minor version number to 0, and increment the major version number by 1.

(Yeah, I know. So original and creative /s)

## Implementation progress

Will be rolled out in next release (`v5.1`, will likely happen in 2 weeks).

**Comment by siyia2** [comment]
superb!

**Comment by Banbeucmas** [comment]
Oh yes. Congratz

**Comment by x70b1** [comment]
Here is more about it: [semver.org](https://semver.org/)

**Comment by yshui** [comment]
@x70b1 I am aware. I was just thinking maybe we don't need the full three levels of version numbers.

**Comment by x70b1** [comment]
That was just a hint. If you don't need the complete package it's okay. :wink:

**Comment by dikiaap** [comment]
The release date on GitHub release page also needs correction. [Compton v5.0](https://github.com/yshui/compton/releases/tag/v5) was released on December 9, 2018 which should be January 20, 2019. Iirc, this also happened in the previous release.
