### ISSUE TITLE
Incorrect detection of full-screen window in some applications when using unredir-if-possible

### ISSUE THREAD

**Issue by Monsterovich** [yshui/compton#998]
I noticed that in some applications, even when using a normal window, the compositing is turned off.

And it's not just applications that use the SDL library. I thought that flameshot app is also affected by this problem, but then I found out that it has a fullscreen window state (which is `_NET_WM_STATE_FULLSCREEN` atom in X I guess?). Ok, fair enough.

```
  Window manager hints:
      Client accepts input or input focus: Yes
      Initial state is Normal State
      Window type:
          Utility
           Kde Net Wm Window Type Override
          Normal
      Window state:
          Above
          Fullscreen
          Stays On Top
```

This is acceptable but not for the case below.

I made a simple SDL application that triggers unredirection.

```C++
// g++ sdl-fullscreen.cpp -lSDL2 -o sdl-fullscreen
#include <SDL2/SDL.h>

int main(int argc, char *argv[])
{
    // returns zero on success else non-zero
    if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
        printf("error initializing SDL: %s\n", SDL_GetError());
    }
    SDL_Window* win = SDL_CreateWindow("SDL Window", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, 0);

    bool close = false;
    while (!close) {
        SDL_Event event;

        while (SDL_PollEvent(&event)) {
            switch (event.type) {
                case SDL_QUIT:
                    // handling of close button
                    close = true;
                    break;
                }
        }
    }

    return 0;
}
```

`xwininfo -all` says it's a normal window, no fullscreen hints.

```
  Window manager hints:
      Client accepts input or input focus: Yes
      Displayed on desktop 1
      Window type:
          Normal
      Process id: 80541 on host dell
      Frame extents: 1, 1, 34, 1
```

What the hell is going on with the detection of a full screen windows?

I'm testing this on latest version of picom from `next` branch. Just set `unredir-if-possible` to true and run the app above.

**Comment by Monsterovich** [comment]
Another interesting thing is that applications like `glxgears` or `glmark2` don't trigger compositing to be disabled when the `unredir-if-possible ` option is enabled. Same with wine applications running in windowed mode.

P.S. SDL1 apps are not affected by this bug either.

**Comment by yshui** [comment]
SDL2 apps set the `_NET_WM_BYPASS_COMPOSITOR` property.

**Comment by Monsterovich** [comment]
> SDL2 apps set the `_NET_WM_BYPASS_COMPOSITOR` property.

I don't understand, you meant it's an SDL2 issue?

It turns out there is a workaround for this problem. https://github.com/libsdl-org/SDL/issues/3802

**Comment by tryone144** [comment]
> I don't understand, you meant it's an SDL2 issue?

This is exactly the expected behaviour. However you might argue that in this specific case, settings `_NET_WM_BYPASS_COMPOSITOR` causes differences in the appearance. (See the [spec](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm46443276543696))

**Comment by Monsterovich** [comment]
> > I don't understand, you meant it's an SDL2 issue?
> 
> This is exactly the expected behaviour. However you might argue that in this specific case, settings `_NET_WM_BYPASS_COMPOSITOR` causes differences in the appearance. (See the [spec](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm46443276543696))

But even in the above spec it says that... 

> The compositing manager MAY bypass compositing for both fullscreen and non-fullscreen windows if bypassing is requested, but MUST NOT bypass if it would cause differences from the composited appearance. 

Disabling compositing when a non full-screen window appears disables compositing on all other windows as well.
Is this the right approach? Just look at what THIS looks like.

![изображение](https://user-images.githubusercontent.com/3750982/213013492-eaecd9b6-0881-4003-94f9-2af398128966.png)

The window behind the plank widget is not even visible because transparency is disabled.

**Comment by tryone144** [comment]
> Disabling compositing when a non full-screen window appears disables compositing on all other windows as well.
> Is this the right approach? Just look at what THIS looks like.

Yes, this is exactly the point I was trying to make. :wink:
But since picom draws on its own overlay window, I am not sure we can only redirect *some* windows...

On the other hand, the logic to check whether unredirecting (or bypassing) is feasible or "allowed" would be to only unredirect if there is only a single fullscreen window visible that has no transparency / rounded-corners / ... (?) and this one is the one on top. Complicating things further, because dialog or other overlay windows might be rendered on top of the fullscreen window and may or may not have a different appearance based on compositing. And switching compositing on / off will cause a visual glitch.
Fading / animations / focus effects / etc. is a completely different can of worms...

On a different note, have you tried using `unredir-if-possible-exclude` to ignore non-fullscreen windows?

**Comment by Monsterovich** [comment]
> On a different note, have you tried using unredir-if-possible-exclude to ignore non-fullscreen windows?

It seems to be working.

```ini
unredir-if-possible-exclude = [
    "_NET_WM_STATE@:a != '_NET_WM_STATE_FULLSCREEN'"
];
```

@yshui You can even put it in the default config sample. Probably. Disabling compositing is mostly only needed in full-screen windows for extra performance/for freesync to work, etc.

**Comment by Monsterovich** [comment]
Update: I recommend to disable this atom for SDL completely because it also affects transparent windows that are overlayed on the full screen window. I don't know how to fix this.

```bash
export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0
```


![изображение](https://user-images.githubusercontent.com/3750982/214701400-309d8b6e-18c0-408a-b49a-18d4dc1df5a7.png)

This (https://github.com/yshui/picom/issues/680) suggestion is not bad after all.
