### ISSUE TITLE
Rounded Corner Exclude Not Working

### ISSUE THREAD

**Issue by Bcez** [yshui/compton#999]
### Platform
EndevourOS Cassini

### GPU, drivers, and screen setup

Xfce4 with xfwm4

Title explains it all

Config
`round-borders-exclude = [
  "class_g = 'xfce4-panel'",
  "class_g = 'dockx'"
];`

**Comment by absolutelynothelix** [comment]
1) it’s `rounded-corners-exclude`;
2) xfce applications usually have `class_g` starting from a capital letter, so either change `xfce4-panel` to `Xfce4-panel`, or `class_g` to `class_i`.

**Comment by Bcez** [comment]
worked ty
